0 0 dataAuditErrors
317 0 GRESDTDI20_REV: ESDTDI20 Revision must be == 3.0 !
320 0 GRESDTDI25_REV: ESDTDI25 Revision must be == 2.0 !
323 0 GRESDFDI25_REV: ESDFDI25 Revision must be == 2.0 !
326 0 GRESDFDI50_REV: ESDFDI50 Revision must be == 2.0 !
329 0 GRESDTDI50_REV: ESDTDI50 Revision must be == 3.0 !
402 0 SBLK without OP
477 0 ESDPDIDN device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv sn dp sp
499 0 ESDVPNPNW device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv dn sn dp sp
518 0 ESDNDIDN device touching ns pi rn nw nr pr bb tg ng pc bp rr rp pd op rxhv sn dp sp
545 0 ESDNDSX device touching ns pi rn nw nr pr bb tg ng pc bp rr rp pd op rxhv dn sn dp sp
602 0 esdtdi50 anod wiring not allowed through PC !
610 0 esdfdi25/50 anod wiring not allowed through PC !
642 0 ESDFDI device touching ns pi rn nr pr bb tg ng rr rp pd op
657 0 ESDTDI device touching ns pi rn nw nr pr bb tg ng pc rr rp pd op dp
665 0 efuse device without bp
684 0 efuse device touching ns rx pi rn nw nr pr bb tg ng rr rp pd op rxhv dn sn dp sp
764 0 VPNP/VNPN device touching ns pi rn nw nr pr bb tg ng pc rr rp pd op
788 0 High Voltage Resistor device (hvnwres) touching sp,dp
790 0 High Voltage Resistor device (hvpwres) touching sn
830 0 High Voltage Resistor device touching ns pi rn nr pr bb tg ng pc rr rp pd
863 0 HAVAR device touching pi,nw,nr,pr,dg,pc,rr,rp,pd,op
865 0 HAVAR device outside ns or bb
901 0 SBD device must be covered by DN
922 0 SBDI device touching ns pi nw nr pr tg ng pc rr rp op rxhv sn dp sp
946 0 DI Diode device without bp
963 0 DI Diode device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv sn dp sp
983 0 DIVPNP device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv dn sn dp sp
1027 0 DIPI Diode device touching ns pi rn nr pr bb tg ng pc rr rp pd op rxhv sn dp sp
1029 0 DIPI Diode device touching nw,bp
1091 0 pcapi or pcapim devices touching ns pi rn nr pr bb ng rr rp pd op rxhv sn dp sp
1141 0 mosvar, mosvarm or pcdcapm devices touching ns,jd,pi,rn,nr,pr,dg,bp,rr,rp,pd,op
1190 0 P+ diffusion in ncap nwell found
1216 0 pcdcap devices touching ns pi rn nr pr ng bp rr rp pd op rxhv dn sn dp sp
1581 0 Dual gate poly device without M1/CA connection
1742 0 N+ Diffused Resistor device touching ns,nw,nr,pr
1974 0 FET device touching ns,jd,rn,bb,rr,rp,pd,op
2058 0 FET HV device touching  ns,pi,rn,nr,pr,bb,rr,rp,pd,op
2119 0 Diffused Resistor device touching bb,dg,pc
2217 0 Polysilicon Resistor device touching rx,rn,dg
2223 0 Polysilicon Resistor device not covered by P+ implant
2229 0 Polysilicon Resistor device BB touching pi,ns,nr,pr,dg
2248 0 P Poly resistor RR BB touching pi,ns,nw,nr,pr,dg
2255 0 P Poly resistor RP BB touching pi,ns,nw,nr,pr,dg
2394 0 (AM res) not covered by mask AM
2396 0 (MT res) not covered by mask MT
2398 0 (M4 res) not covered by mask M4
2400 0 (M3 res) not covered by mask M3
2402 0 (M2 res) not covered by mask M2
2404 0 (M1 res) not covered by mask M1
2483 0 Overlapping transmission lines - terminals must abut filters
2526 0 inductor device without bb
2539 0 inductor device touching ns,jd,pi,rn,nw,nr,pr,dg,pc,rr,rp,pd,op
2616 0 M3 and M4 inside enhanced Inductor model must have the same dimension as MT
2620 0 M3/M4 inside standard inductor model is not allowed
2684 0 Missing v2 vias on symind coils between m2 and m3
2686 0 Missing v3 vias on symind coils between m3 and m4
2688 0 Missing v4 vias on symind coils between m4 and mt
2690 0 Missing v2 vias on symind coils between m2 and m3
2692 0 Missing v3 vias on symind coils between m3 and m4
2694 0 Missing v4 vias on symind coils between m4 and mt
2696 0 Missing ft vias on symind coils between mt and am
2698 0 Missing ft vias on symind coils between mt and am
2700 0 Missing ft vias on ind coils between mt and am
2721 0 AM signal wire exiting symetrical inductor straddling metal coil outside the pin
2725 0 Center tap signal wire exiting symetrical inductor outside CT pin
2729 0 Center tap signal wire exiting symetrical inductor outside CT pin
2912 0 AM signal wire not exiting transmission line at port, shorted, or open
2933 0 M4 signal wire not exiting transmission line at port, shorted, or open
2951 0 MT signal wire not exiting transmission line at port, shorted, or open
2975 0 M3 signal wire not exiting transmission line at port, shorted, or open
2996 0 M2 signal wire not exiting transmission line at port, shorted, or open
3142 0 No FT via over HT
3143 0 No FT via over QT
3164 0 MODEL concern - K1 resistor not totally over STI substrate
3168 0 K1 resistor device touching rxhv sn dp sp
3925 0 nw_StampErrorConnect
3929 0 nw_StampErrorFloat
3930 0 nw_StampErrorMult
3933 0 bb_StampErrorConnect
3937 0 bb_StampErrorMult
3940 0 nw_StampErrorConnect
3944 0 nw_StampErrorFloat
3945 0 nw_StampErrorMult
3948 0 sn_StampErrorConnect
3952 0 sn_StampErrorFloat
3953 0 sn_StampErrorMult
3956 0 rn_StampErrorConnect
3960 0 rn_StampErrorFloat
3961 0 rn_StampErrorMult
3964 0 ncap_nw_StampErrorConnect
3968 0 ncap_nw_StampErrorFloat
3969 0 ncap_nw_StampErrorMult
3972 0 DIPI_nw_StampErrorConnect
3976 0 DIPI_nw_StampErrorFloat
3977 0 DIPI_nw_StampErrorMult
3980 0 well_StampErrorConnect
3984 0 well_StampErrorFloat
3985 0 well_StampErrorMult
3988 0 pi_StampErrorConnect
3992 0 pi_StampErrorFloat
3993 0 pi_StampErrorMult
3996 0 dn_StampErrorConnect
4004 0 dn_StampErrorFloat
4006 0 dn_StampErrorMult
4009 0 sbdi_dn_StampErrorConnect
4013 0 sbdi_dn_StampErrorFloat
4015 0 sbdi_dn_StampErrorMult
4018 0 pwell_StampErrorConnect
4022 0 pwell_StampErrorFloat
4023 0 pwell_StampErrorMult
4025 0 substrate_ptap_StampErrorCon
4030 0 substrate_StampErrorCon
4037 0 sub_nti_StampErrorCon
4045 0 Mixed voltage net found : 3V3 or 5V diffusion is connected to 1.8V gate
4050 0 Mixed voltage net found : High Voltage diffusion is connected to Low Voltage gate
4052 0 ptap connected to POWER net found !
4054 0 pwtap connected to POWER net found !
4059 0 forward biased ptie device found ! [tdpdnw/diodepnw] 
4064 0 forward biased ntie device found ! [tdndsx,tdndpw/diodenx,diodendpw] 
4067 0 forward biased pwdn device found ! [wdpwdn / diodepwdn] 
4069 0 NW ring not connected to a power net found !
12094 0 ###### SIX levels of metal M1-M2-M3-M4-MT-AM #####
13528 0 malformed device vnpn_dev
13529 0 malformed device vpnp_dev
13530 0 malformed device nfet20hs_dev
13531 0 malformed device nfet50hs_dev
13532 0 malformed device nfet20mh_dev
13533 0 malformed device nfeti20h_dev
13534 0 malformed device nfeti20t_dev
13535 0 malformed device nfeti25m_dev
13536 0 malformed device nfeti50h_dev
13537 0 malformed device nfeti50m_dev
13538 0 malformed device nfeti50t_dev
13539 0 malformed device pfet20hs_dev
13540 0 malformed device pfet50hs_dev
13541 0 malformed device pfet20h_dev
13542 0 malformed device pfet20t_dev
13543 0 malformed device pfet25m_dev
13544 0 malformed device pfet50h_dev
13545 0 malformed device pfet50m_dev
13546 0 malformed device pfet50t_dev
13547 0 malformed device nfeti_dn_dev_b
13548 0 malformed device nfet6_dn_dev_b
13549 0 malformed device nfeti_dn_dev
13550 0 malformed device nfet6_dn_dev
13551 0 malformed device nfeti_dn_dev_HVT_b
13552 0 malformed device nfet6_dn_dev_HVT_b
13553 0 malformed device nfeti_dn_dev_HVT
13554 0 malformed device nfet6_dn_dev_HVT
13555 0 malformed device nfeti_dn_dev_TG
13556 0 malformed device nfet6_dn_dev_TG
13557 0 malformed device nfeti_dn_mul
13558 0 malformed device nfet6_dn_mul
13559 0 malformed device nfeti_dn_mul_HVT
13560 0 malformed device nfet6_dn_mul_HVT
13561 0 malformed device nfeti_dn_mul_TG
13562 0 malformed device nfet6_dn_mul_TG
13563 0 malformed device nfet_dev
13564 0 malformed device nfet_dev_b
13565 0 malformed device nfet_mul
13566 0 malformed device nfeti_dev
13567 0 malformed device nfeti_dev_b
13568 0 malformed device nfeti_mul
13569 0 malformed device nfet6_dev
13570 0 malformed device nfet6_mul
13571 0 malformed device nfet_dev_TG
13572 0 malformed device nfet_mul_TG
13573 0 malformed device nfeti_dev_TG
13574 0 malformed device nfeti_mul_TG
13575 0 malformed device nfet6_dev_TG
13576 0 malformed device nfet6_mul_TG
13577 0 malformed device nfet_dev_HVT
13578 0 malformed device nfet_mul_HVT
13579 0 malformed device nfet_dev_HVT_b
13580 0 malformed device nfet_dev_SHVT
13581 0 malformed device nfet_mul_SHVT
13582 0 malformed device nfet_dev_SHVT_b
13583 0 malformed device nfeti_dev_HVT
13584 0 malformed device nfeti_mul_HVT
13585 0 malformed device nfeti_dev_HVT_b
13586 0 malformed device pfeti_dn_dev_b
13587 0 malformed device pfet5_dn_dev_b
13588 0 malformed device pfeti_dn_dev
13589 0 malformed device pfet5_dn_dev
13590 0 malformed device pfeti_dn_mul
13591 0 malformed device pfet5_dn_mul
13592 0 malformed device pfeti_dn_dev_HVT_b
13593 0 malformed device pfet5_dn_dev_HVT_b
13594 0 malformed device pfeti_dn_dev_HVT
13595 0 malformed device pfet5_dn_dev_HVT
13596 0 malformed device pfeti_dn_mul_HVT
13597 0 malformed device pfet5_dn_mul_HVT
13598 0 malformed device pfeti_dn_dev_TG
13599 0 malformed device pfet5_dn_dev_TG
13600 0 malformed device pfeti_dn_mul_TG
13601 0 malformed device pfet5_dn_mul_TG
13602 0 malformed device pfet_dev
13603 0 malformed device pfet_dev_b
13604 0 malformed device pfet_mul
13605 0 malformed device pfet_dev_TG
13606 0 malformed device pfet_mul_TG
13607 0 malformed device pfet_dev_HVT
13608 0 malformed device pfet_dev_HVT_b
13609 0 malformed device pfet_mul_HVT
13610 0 malformed device pfet_dev_SHVT
13611 0 malformed device pfet_dev_SHVT_b
13612 0 malformed device pfet_mul_SHVT
13613 0 malformed device nfRFi_dn_dev
13614 0 malformed device nfRF6_dn_dev
13615 0 malformed device nfRFi_dn_mul
13616 0 malformed device nfRF6_dn_mul
13617 0 malformed device nfRFi_dev
13618 0 malformed device nfRF6_dev
13619 0 malformed device nfRF_dev
13620 0 malformed device nfRFi_mul
13621 0 malformed device nfRF6_mul
13622 0 malformed device nfRF_mul
13623 0 malformed device pfRFi_dn_dev
13624 0 malformed device pfRF5_dn_dev
13625 0 malformed device pfRFi_dn_mul
13626 0 malformed device pfRF5_dn_mul
13627 0 malformed device pfRF_dev
13628 0 malformed device pfRF_mul
13629 0 malformed device SBD
13630 0 malformed device DI_diode
13631 0 malformed device DIPI_diode
13632 0 malformed device DI_VPNP
13633 0 malformed device mosvar_dev
13634 0 malformed device mosvar50_dev
13635 0 malformed device pcdcap50_dev
13636 0 malformed device ncap_dev
13637 0 malformed device pcdcapt_dev
13638 0 malformed device pjfet_dev
13639 0 malformed device rnw6pc_dev_no_bp
13641 0 malformed device res6pc_dev_no_bp
13642 0 malformed device rnw6pc_dev
13644 0 malformed device res6pc_dev
13645 0 malformed device rnw6rr_dev
13647 0 malformed device res6rr_dev
13648 0 malformed device rnw6rp_dev
13650 0 malformed device res6rp_dev
13652 0 malformed device hvnwres_dev
13653 0 malformed device hvpwres_dev
13655 0 malformed device res6n_dev
13656 0 malformed device res6n_3_dev
13657 0 malformed device res6n_5_dev
13658 0 malformed device res6p_dev
13659 0 malformed device res6p_3_dev
13660 0 malformed device res6p_4_dev
13662 0 malformed device res6n_sblk
13663 0 malformed device res6n_3_sblk
13664 0 malformed device res6n_5_sblk
13665 0 malformed device res6p_sblk
13666 0 malformed device res6p_3_sblk
13667 0 malformed device res6p_4_sblk
13668 0 malformed device k1_dev_bb
13670 0 malformed device k1_dev_sx
13671 0 malformed device esdnsh_dev
13672 0 malformed device esdpsh_dev
13673 0 malformed device esdnsh_dev_dn
13674 0 malformed device esdpsh_dev_dn
13675 0 malformed device sub_dev
13677 0 malformed device ntie_device
13678 0 malformed device ptie_device
13679 0 malformed device nwsx_device
13680 0 malformed device ntie_in_sp
13681 0 malformed device dnsx_device
13682 0 malformed device pwdn_device
13683 0 malformed device corrPoint_dev_M2
13684 0 malformed device corrPoint_dev_PD
13685 0 malformed device corrPoint_dev_ND
13686 0 malformed device corrPoint_dev_PC
13687 0 malformed device corrPoint_dev_M1
13688 0 malformed device ESD_pdnw_diode
13689 0 malformed device ESD_pdnw_diode_GR
13690 0 malformed device ESD_ndsx
13691 0 malformed device ESD_ndsx_GR
13692 0 malformed device esdfdi50_dev
13693 0 malformed device esdfdi25_dev
13694 0 malformed device esdtdi25_dev
13695 0 malformed device esdtdi20_dev
13696 0 malformed device esdtdi50_dev
13697 0 malformed device MIMpi
13698 0 malformed device MIMdn
13699 0 malformed device MIMnw
13700 0 malformed device MIMsx
13701 0 malformed device MIMhdpi
13702 0 malformed device MIMhddn
13703 0 malformed device MIMhdnw
13704 0 malformed device MIMhdsx
13705 0 malformed device DUALMIMpi
13706 0 malformed device DUALMIMdn
13707 0 malformed device DUALMIMnw
13708 0 malformed device DUALMIMsx
13709 0 malformed device DUALMIMhdpi
13710 0 malformed device DUALMIMhddn
13711 0 malformed device DUALMIMhdnw
13712 0 malformed device DUALMIMhdsx
13714 0 malformed device vncap_top1
13715 0 malformed device vncap_tnw1
13717 0 malformed device vncap_topt
13718 0 malformed device vncap_tnwt
13720 0 malformed device vncap_top2
13721 0 malformed device vncap_tnw2
13723 0 malformed device vncap_top3
13724 0 malformed device vncap_tnw3
13726 0 malformed device vncap_top4
13727 0 malformed device vncap_tnw4
13729 0 malformed device vncap_top1_hv
13730 0 malformed device vncap_tnw1_hv
13732 0 malformed device vncap_topt_hv
13733 0 malformed device vncap_tnwt_hv
13735 0 malformed device vncap_top2_hv
13736 0 malformed device vncap_tnw2_hv
13738 0 malformed device vncap_top3_hv
13739 0 malformed device vncap_tnw3_hv
13741 0 malformed device vncap_top4_hv
13742 0 malformed device vncap_tnw4_hv
13743 0 malformed device am_transmission
13744 0 malformed device ind2_mtam_m1
13745 0 malformed device ind2_mtam_bb
13746 0 malformed device symind3_amam_bb
13747 0 malformed device symind2_amam_bb
13748 0 malformed device symind3_amam_m1
13749 0 malformed device symind2_amam_m1
13750 0 malformed device padOverDev
13751 0 malformed device bondPpc
13752 0 malformed device bondPm1
13753 0 malformed device bondPbb
13754 0 malformed device efuse
13759 0 malformed device coupledA
13764 0 malformed device singleEndA
13768 0 malformed device coupledT
13772 0 malformed device singleEndT
13775 0 malformed device coupled4
13778 0 malformed device singleEnd4
13780 0 malformed device coupled3
13782 0 malformed device singleEnd3
13783 0 malformed device coupled2
13784 0 malformed device singleEnd2
15539 0 unstable device for am_RES_min_Device_277
15540 0 unpreserved device am_RES_min_Device_277
15541 0 unstable device for m4_RES_min_Device_276
15542 0 unpreserved device m4_RES_min_Device_276
15543 0 unstable device for m4_RES_min_Device_274
15544 0 unpreserved device m4_RES_min_Device_274
15545 0 unstable device for m3_RES_min_Device_273
15546 0 unpreserved device m3_RES_min_Device_273
15547 0 unstable device for m3_RES_min_Device_271
15548 0 unpreserved device m3_RES_min_Device_271
15549 0 unstable device for m2_RES_min_Device_270
15550 0 unpreserved device m2_RES_min_Device_270
15551 0 unstable device for m2_RES_min_Device_268
15552 0 unpreserved device m2_RES_min_Device_268
15553 0 unstable device for mt_RES_min_Device_267
15554 0 unpreserved device mt_RES_min_Device_267
15555 0 unstable device for mt_RES_min_Device_265
15556 0 unpreserved device mt_RES_min_Device_265
15557 0 unstable device for m1_RES_min_Device_264
15558 0 unpreserved device m1_RES_min_Device_264
15559 0 unstable device for m1_RES_min_Device_262
15560 0 unpreserved device m1_RES_min_Device_262
15561 0 unstable device for singleEnd2_shield1
15562 0 unpreserved device singleEnd2_shield1
15563 0 unstable device for coupled2_shield1
15564 0 unpreserved device coupled2_shield1
15565 0 unstable device for singleEnd3_shield2
15566 0 unpreserved device singleEnd3_shield2
15567 0 unstable device for singleEnd3_shield1
15568 0 unpreserved device singleEnd3_shield1
15569 0 unstable device for coupled3_shield2
15570 0 unpreserved device coupled3_shield2
15571 0 unstable device for coupled3_shield1
15572 0 unpreserved device coupled3_shield1
15573 0 unstable device for singleEnd4_shield3
15574 0 unpreserved device singleEnd4_shield3
15575 0 unstable device for singleEnd4_shield2
15576 0 unpreserved device singleEnd4_shield2
15577 0 unstable device for singleEnd4_shield1
15578 0 unpreserved device singleEnd4_shield1
15579 0 unstable device for coupled4_shield3
15580 0 unpreserved device coupled4_shield3
15581 0 unstable device for coupled4_shield2
15582 0 unpreserved device coupled4_shield2
15583 0 unstable device for coupled4_shield1
15584 0 unpreserved device coupled4_shield1
15585 0 unstable device for singleEndT_shield4
15586 0 unpreserved device singleEndT_shield4
15587 0 unstable device for singleEndT_shield3
15588 0 unpreserved device singleEndT_shield3
15589 0 unstable device for singleEndT_shield2
15590 0 unpreserved device singleEndT_shield2
15591 0 unstable device for singleEndT_shield1
15592 0 unpreserved device singleEndT_shield1
15593 0 unstable device for coupledT_shield4
15594 0 unpreserved device coupledT_shield4
15595 0 unstable device for coupledT_shield3
15596 0 unpreserved device coupledT_shield3
15597 0 unstable device for coupledT_shield2
15598 0 unpreserved device coupledT_shield2
15599 0 unstable device for coupledT_shield1
15600 0 unpreserved device coupledT_shield1
15601 0 unstable device for singleEndA_shieldT
15602 0 unpreserved device singleEndA_shieldT
15603 0 unstable device for singleEndA_shield4
15604 0 unpreserved device singleEndA_shield4
15605 0 unstable device for singleEndA_shield3
15606 0 unpreserved device singleEndA_shield3
15607 0 unstable device for singleEndA_shield2
15608 0 unpreserved device singleEndA_shield2
15609 0 unstable device for singleEndA_shield1
15610 0 unpreserved device singleEndA_shield1
15611 0 unstable device for coupledA_shieldT
15612 0 unpreserved device coupledA_shieldT
15613 0 unstable device for coupledA_shield4
15614 0 unpreserved device coupledA_shield4
15615 0 unstable device for coupledA_shield3
15616 0 unpreserved device coupledA_shield3
15617 0 unstable device for coupledA_shield2
15618 0 unpreserved device coupledA_shield2
15619 0 unstable device for coupledA_shield1
15620 0 unpreserved device coupledA_shield1
15621 0 unstable device for efuse_Device_231
15622 0 unpreserved device efuse_Device_231
15623 0 unstable device for bondPbb_Device_230
15624 0 unpreserved device bondPbb_Device_230
15625 0 unstable device for bondPm1_Device_229
15626 0 unpreserved device bondPm1_Device_229
15627 0 unstable device for bondPpc_Device_228
15628 0 unpreserved device bondPpc_Device_228
15629 0 unstable device for padOverDev_Device_227
15630 0 unpreserved device padOverDev_Device_227
15631 0 unstable device for symind2_amam_m1_Device_226
15632 0 unpreserved device symind2_amam_m1_Device_226
15633 0 unstable device for symind3_amam_m1_Device_225
15634 0 unpreserved device symind3_amam_m1_Device_225
15635 0 unstable device for symind2_amam_bb_Device_224
15636 0 unpreserved device symind2_amam_bb_Device_224
15637 0 unstable device for symind3_amam_bb_Device_223
15638 0 unpreserved device symind3_amam_bb_Device_223
15639 0 unstable device for ind2_mtam_bb_Device_222
15640 0 unpreserved device ind2_mtam_bb_Device_222
15641 0 unstable device for ind2_mtam_m1_Device_221
15642 0 unpreserved device ind2_mtam_m1_Device_221
15643 0 unstable device for am_transmission_Device_220
15644 0 unpreserved device am_transmission_Device_220
15645 0 unstable device for vncap_tnw4_hv_Device_219
15646 0 unpreserved device vncap_tnw4_hv_Device_219
15647 0 unstable device for vncap_top4_hv_pwell
15648 0 unpreserved device vncap_top4_hv_pwell
15649 0 unstable device for vncap_top4_hv_subs
15650 0 unpreserved device vncap_top4_hv_subs
15651 0 unstable device for vncap_tnw3_hv_Device_216
15652 0 unpreserved device vncap_tnw3_hv_Device_216
15653 0 unstable device for vncap_top3_hv_pwell
15654 0 unpreserved device vncap_top3_hv_pwell
15655 0 unstable device for vncap_top3_hv_subs
15656 0 unpreserved device vncap_top3_hv_subs
15657 0 unstable device for vncap_tnw2_hv_Device_213
15658 0 unpreserved device vncap_tnw2_hv_Device_213
15659 0 unstable device for vncap_top2_hv_pwell
15660 0 unpreserved device vncap_top2_hv_pwell
15661 0 unstable device for vncap_top2_hv_subs
15662 0 unpreserved device vncap_top2_hv_subs
15663 0 unstable device for vncap_tnwt_hv_Device_210
15664 0 unpreserved device vncap_tnwt_hv_Device_210
15665 0 unstable device for vncap_topt_hv_pwell
15666 0 unpreserved device vncap_topt_hv_pwell
15667 0 unstable device for vncap_topt_hv_subs
15668 0 unpreserved device vncap_topt_hv_subs
15669 0 unstable device for vncap_tnw1_hv_Device_207
15670 0 unpreserved device vncap_tnw1_hv_Device_207
15671 0 unstable device for vncap_top1_hv_pwell
15672 0 unpreserved device vncap_top1_hv_pwell
15673 0 unstable device for vncap_top1_hv_subs
15674 0 unpreserved device vncap_top1_hv_subs
15675 0 unstable device for vncap_tnw4_Device_204
15676 0 unpreserved device vncap_tnw4_Device_204
15677 0 unstable device for vncap_top4_pwell
15678 0 unpreserved device vncap_top4_pwell
15679 0 unstable device for vncap_top4_subs
15680 0 unpreserved device vncap_top4_subs
15681 0 unstable device for vncap_tnw3_Device_201
15682 0 unpreserved device vncap_tnw3_Device_201
15683 0 unstable device for vncap_top3_pwell
15684 0 unpreserved device vncap_top3_pwell
15685 0 unstable device for vncap_top3_subs
15686 0 unpreserved device vncap_top3_subs
15687 0 unstable device for vncap_tnw2_Device_198
15688 0 unpreserved device vncap_tnw2_Device_198
15689 0 unstable device for vncap_top2_pwell
15690 0 unpreserved device vncap_top2_pwell
15691 0 unstable device for vncap_top2_subs
15692 0 unpreserved device vncap_top2_subs
15693 0 unstable device for vncap_tnwt_Device_195
15694 0 unpreserved device vncap_tnwt_Device_195
15695 0 unstable device for vncap_topt_pwell
15696 0 unpreserved device vncap_topt_pwell
15697 0 unstable device for vncap_topt_subs
15698 0 unpreserved device vncap_topt_subs
15699 0 unstable device for vncap_tnw1_Device_192
15700 0 unpreserved device vncap_tnw1_Device_192
15701 0 unstable device for vncap_top1_pwell
15702 0 unpreserved device vncap_top1_pwell
15703 0 unstable device for vncap_top1_subs
15704 0 unpreserved device vncap_top1_subs
15705 0 unstable device for DUALMIMhdsx_Device_189
15706 0 unpreserved device DUALMIMhdsx_Device_189
15707 0 unstable device for DUALMIMhdnw_Device_188
15708 0 unpreserved device DUALMIMhdnw_Device_188
15709 0 unstable device for DUALMIMhddn_Device_187
15710 0 unpreserved device DUALMIMhddn_Device_187
15711 0 unstable device for DUALMIMhdpi_Device_186
15712 0 unpreserved device DUALMIMhdpi_Device_186
15713 0 unstable device for DUALMIMsx_Device_185
15714 0 unpreserved device DUALMIMsx_Device_185
15715 0 unstable device for DUALMIMnw_Device_184
15716 0 unpreserved device DUALMIMnw_Device_184
15717 0 unstable device for DUALMIMdn_Device_183
15718 0 unpreserved device DUALMIMdn_Device_183
15719 0 unstable device for DUALMIMpi_Device_182
15720 0 unpreserved device DUALMIMpi_Device_182
15721 0 unstable device for MIMhdsx_Device_181
15722 0 unpreserved device MIMhdsx_Device_181
15723 0 unstable device for MIMhdnw_Device_180
15724 0 unpreserved device MIMhdnw_Device_180
15725 0 unstable device for MIMhddn_Device_179
15726 0 unpreserved device MIMhddn_Device_179
15727 0 unstable device for MIMhdpi_Device_178
15728 0 unpreserved device MIMhdpi_Device_178
15729 0 unstable device for MIMsx_Device_177
15730 0 unpreserved device MIMsx_Device_177
15731 0 unstable device for MIMnw_Device_176
15732 0 unpreserved device MIMnw_Device_176
15733 0 unstable device for MIMdn_Device_175
15734 0 unpreserved device MIMdn_Device_175
15735 0 unstable device for MIMpi_Device_174
15736 0 unpreserved device MIMpi_Device_174
15737 0 unstable device for esdtdi50_dev_Device_173
15738 0 unpreserved device esdtdi50_dev_Device_173
15739 0 unstable device for esdtdi20_dev_Device_172
15740 0 unpreserved device esdtdi20_dev_Device_172
15741 0 unstable device for esdtdi25_dev_Device_171
15742 0 unpreserved device esdtdi25_dev_Device_171
15743 0 unstable device for esdfdi25_dev_Device_170
15744 0 unpreserved device esdfdi25_dev_Device_170
15745 0 unstable device for esdfdi50_dev_Device_169
15746 0 unpreserved device esdfdi50_dev_Device_169
15747 0 unstable device for ESD_ndsx_dn_Device_168
15748 0 unpreserved device ESD_ndsx_dn_Device_168
15749 0 unstable device for ESD_ndsx_GR_Device_167
15750 0 unpreserved device ESD_ndsx_GR_Device_167
15751 0 unstable device for ESD_ndsx_Device_166
15752 0 unpreserved device ESD_ndsx_Device_166
15753 0 unstable device for ESD_pdnw_dn_Device_165
15754 0 unpreserved device ESD_pdnw_dn_Device_165
15755 0 unstable device for ESD_pdnw_diode_GR_Device_164
15756 0 unpreserved device ESD_pdnw_diode_GR_Device_164
15757 0 unstable device for ESD_pdnw_diode_Device_163
15758 0 unpreserved device ESD_pdnw_diode_Device_163
15759 0 unstable device for corrPoint_dev_M1_Device_162
15760 0 unpreserved device corrPoint_dev_M1_Device_162
15761 0 unstable device for corrPoint_dev_PC_Device_161
15762 0 unpreserved device corrPoint_dev_PC_Device_161
15763 0 unstable device for corrPoint_dev_ND_Device_160
15764 0 unpreserved device corrPoint_dev_ND_Device_160
15765 0 unstable device for corrPoint_dev_PD_Device_159
15766 0 unpreserved device corrPoint_dev_PD_Device_159
15767 0 unstable device for corrPoint_dev_M2_Device_158
15768 0 unpreserved device corrPoint_dev_M2_Device_158
15769 0 unstable device for pwdn_device_Device_157
15770 0 unpreserved device pwdn_device_Device_157
15771 0 unstable device for dnsx_device_Device_156
15772 0 unpreserved device dnsx_device_Device_156
15773 0 unstable device for ntie_in_sp_Device_155
15774 0 unpreserved device ntie_in_sp_Device_155
15775 0 unstable device for nwsx_device_Device_154
15776 0 unpreserved device nwsx_device_Device_154
15777 0 unstable device for ptie_device_Device_153
15778 0 unpreserved device ptie_device_Device_153
15779 0 unstable device for ntie_device_Device_151
15780 0 unpreserved device ntie_device_Device_151
15781 0 unstable device for ntie_device_Device_152
15782 0 unpreserved device ntie_device_Device_152
15783 0 unstable device for sub_dev_Device_150
15784 0 unpreserved device sub_dev_Device_150
15785 0 unstable device for esdpsh_dev_dn_Device_149
15786 0 unpreserved device esdpsh_dev_dn_Device_149
15787 0 unstable device for esdnsh_dev_dn_Device_148
15788 0 unpreserved device esdnsh_dev_dn_Device_148
15789 0 unstable device for esdpsh_dev_Device_147
15790 0 unpreserved device esdpsh_dev_Device_147
15791 0 unstable device for esdnsh_dev_Device_146
15792 0 unpreserved device esdnsh_dev_Device_146
15793 0 unstable device for k1_dev_sx_pwell
15794 0 unpreserved device k1_dev_sx_pwell
15795 0 unstable device for k1_dev_sx_subs
15796 0 unpreserved device k1_dev_sx_subs
15797 0 unstable device for k1_dev_bb_Device_143
15798 0 unpreserved device k1_dev_bb_Device_143
15799 0 unstable device for res6p_4_sblk_Device_142
15800 0 unpreserved device res6p_4_sblk_Device_142
15801 0 unstable device for res6p_3_sblk_Device_141
15802 0 unpreserved device res6p_3_sblk_Device_141
15803 0 unstable device for res6p_sblk_Device_140
15804 0 unpreserved device res6p_sblk_Device_140
15805 0 unstable device for res6n_5_sblk_Device_139
15806 0 unpreserved device res6n_5_sblk_Device_139
15807 0 unstable device for res6n_3_sblk_Device_138
15808 0 unpreserved device res6n_3_sblk_Device_138
15809 0 unstable device for res6n_sblk_pwell
15810 0 unpreserved device res6n_sblk_pwell
15811 0 unstable device for res6n_sblk_subs
15812 0 unpreserved device res6n_sblk_subs
15813 0 unstable device for res6p_4_dev_Device_135
15814 0 unpreserved device res6p_4_dev_Device_135
15815 0 unstable device for res6p_3_dev_Device_134
15816 0 unpreserved device res6p_3_dev_Device_134
15817 0 unstable device for res6p_dev_Device_133
15818 0 unpreserved device res6p_dev_Device_133
15819 0 unstable device for res6n_5_dev_Device_132
15820 0 unpreserved device res6n_5_dev_Device_132
15821 0 unstable device for res6n_3_dev_Device_131
15822 0 unpreserved device res6n_3_dev_Device_131
15823 0 unstable device for res6n_dev_pwell
15824 0 unpreserved device res6n_dev_pwell
15825 0 unstable device for res6n_dev_subs
15826 0 unpreserved device res6n_dev_subs
15827 0 unstable device for hvpwres_dev_Device_128
15828 0 unpreserved device hvpwres_dev_Device_128
15829 0 unstable device for hvnwres_dev_pwell
15830 0 unpreserved device hvnwres_dev_pwell
15831 0 unstable device for hvnwres_dev_subs
15832 0 unpreserved device hvnwres_dev_subs
15833 0 unstable device for res6rp_dev_pwell
15834 0 unpreserved device res6rp_dev_pwell
15835 0 unstable device for res6rp_dev_subs
15836 0 unpreserved device res6rp_dev_subs
15837 0 unstable device for rnw6rp_dev_Device_123
15838 0 unpreserved device rnw6rp_dev_Device_123
15839 0 unstable device for res6rr_dev_pwell
15840 0 unpreserved device res6rr_dev_pwell
15841 0 unstable device for res6rr_dev_subs
15842 0 unpreserved device res6rr_dev_subs
15843 0 unstable device for rnw6rr_dev_Device_120
15844 0 unpreserved device rnw6rr_dev_Device_120
15845 0 unstable device for res6pc_dev_pwell
15846 0 unpreserved device res6pc_dev_pwell
15847 0 unstable device for res6pc_dev_subs
15848 0 unpreserved device res6pc_dev_subs
15849 0 unstable device for rnw6pc_dev_Device_117
15850 0 unpreserved device rnw6pc_dev_Device_117
15851 0 unstable device for res6pc_dev_no_bp_pwell
15852 0 unpreserved device res6pc_dev_no_bp_pwell
15853 0 unstable device for res6pc_dev_no_bp_subs
15854 0 unpreserved device res6pc_dev_no_bp_subs
15855 0 unstable device for rnw6pc_dev_no_bp_Device_114
15856 0 unpreserved device rnw6pc_dev_no_bp_Device_114
15857 0 unstable device for pjfet_dev_Device_113
15858 0 unpreserved device pjfet_dev_Device_113
15859 0 unstable device for pcap50_dev_Device_112
15860 0 unpreserved device pcap50_dev_Device_112
15861 0 unstable device for pcap_dev_Device_111
15862 0 unpreserved device pcap_dev_Device_111
15863 0 unstable device for pcdcapt_dev_Device_110
15864 0 unpreserved device pcdcapt_dev_Device_110
15865 0 unstable device for ncap_dev_Device_109
15866 0 unpreserved device ncap_dev_Device_109
15867 0 unstable device for pcdcap50_dev_Device_108
15868 0 unpreserved device pcdcap50_dev_Device_108
15869 0 unstable device for mosvar50_dev_Device_107
15870 0 unpreserved device mosvar50_dev_Device_107
15871 0 unstable device for mosvar_dev_Device_106
15872 0 unpreserved device mosvar_dev_Device_106
15873 0 unstable device for DI_VPNP_Device_105
15874 0 unpreserved device DI_VPNP_Device_105
15875 0 unstable device for DIPI_diode_Device_104
15876 0 unpreserved device DIPI_diode_Device_104
15877 0 unstable device for DI_diode_Device_103
15878 0 unpreserved device DI_diode_Device_103
15879 0 unstable device for SBD_Device_102
15880 0 unpreserved device SBD_Device_102
15881 0 unstable device for pfRF_mul_Device_101
15882 0 unpreserved device pfRF_mul_Device_101
15883 0 unstable device for pfRF_dev_Device_100
15884 0 unpreserved device pfRF_dev_Device_100
15885 0 unstable device for pfRF5_dn_mul_Device_99
15886 0 unpreserved device pfRF5_dn_mul_Device_99
15887 0 unstable device for pfRFi_dn_mul_Device_98
15888 0 unpreserved device pfRFi_dn_mul_Device_98
15889 0 unstable device for pfRF5_dn_dev_Device_97
15890 0 unpreserved device pfRF5_dn_dev_Device_97
15891 0 unstable device for pfRFi_dn_dev_Device_96
15892 0 unpreserved device pfRFi_dn_dev_Device_96
15893 0 unstable device for nfRF_mul_Device_95
15894 0 unpreserved device nfRF_mul_Device_95
15895 0 unstable device for nfRF6_mul_Device_94
15896 0 unpreserved device nfRF6_mul_Device_94
15897 0 unstable device for nfRFi_mul_Device_93
15898 0 unpreserved device nfRFi_mul_Device_93
15899 0 unstable device for nfRF_dev_Device_92
15900 0 unpreserved device nfRF_dev_Device_92
15901 0 unstable device for nfRF6_dev_Device_91
15902 0 unpreserved device nfRF6_dev_Device_91
15903 0 unstable device for nfRFi_dev_Device_90
15904 0 unpreserved device nfRFi_dev_Device_90
15905 0 unstable device for nfRF6_dn_mul_Device_89
15906 0 unpreserved device nfRF6_dn_mul_Device_89
15907 0 unstable device for nfRFi_dn_mul_Device_88
15908 0 unpreserved device nfRFi_dn_mul_Device_88
15909 0 unstable device for nfRF6_dn_dev_Device_87
15910 0 unpreserved device nfRF6_dn_dev_Device_87
15911 0 unstable device for nfRFi_dn_dev_Device_86
15912 0 unpreserved device nfRFi_dn_dev_Device_86
15913 0 unstable device for pfet_mul_SHVT_Device_85
15914 0 unpreserved device pfet_mul_SHVT_Device_85
15915 0 unstable device for pfet_dev_SHVT_b_Device_84
15916 0 unpreserved device pfet_dev_SHVT_b_Device_84
15917 0 unstable device for pfet_dev_SHVT_Device_83
15918 0 unpreserved device pfet_dev_SHVT_Device_83
15919 0 unstable device for pfet_mul_HVT_Device_82
15920 0 unpreserved device pfet_mul_HVT_Device_82
15921 0 unstable device for pfet_dev_HVT_b_Device_81
15922 0 unpreserved device pfet_dev_HVT_b_Device_81
15923 0 unstable device for pfet_dev_HVT_Device_80
15924 0 unpreserved device pfet_dev_HVT_Device_80
15925 0 unstable device for pfet_mul_TG_Device_79
15926 0 unpreserved device pfet_mul_TG_Device_79
15927 0 unstable device for pfet_dev_TG_Device_78
15928 0 unpreserved device pfet_dev_TG_Device_78
15929 0 unstable device for pfet_mul_Device_77
15930 0 unpreserved device pfet_mul_Device_77
15931 0 unstable device for pfet_dev_b_Device_76
15932 0 unpreserved device pfet_dev_b_Device_76
15933 0 unstable device for pfet_dev_Device_75
15934 0 unpreserved device pfet_dev_Device_75
15935 0 unstable device for pfet5_dn_mul_TG_Device_74
15936 0 unpreserved device pfet5_dn_mul_TG_Device_74
15937 0 unstable device for pfeti_dn_mul_TG_Device_73
15938 0 unpreserved device pfeti_dn_mul_TG_Device_73
15939 0 unstable device for pfet5_dn_dev_TG_Device_72
15940 0 unpreserved device pfet5_dn_dev_TG_Device_72
15941 0 unstable device for pfeti_dn_dev_TG_Device_71
15942 0 unpreserved device pfeti_dn_dev_TG_Device_71
15943 0 unstable device for pfet5_dn_mul_HVT_Device_70
15944 0 unpreserved device pfet5_dn_mul_HVT_Device_70
15945 0 unstable device for pfeti_dn_mul_HVT_Device_69
15946 0 unpreserved device pfeti_dn_mul_HVT_Device_69
15947 0 unstable device for pfet5_dn_dev_HVT_Device_68
15948 0 unpreserved device pfet5_dn_dev_HVT_Device_68
15949 0 unstable device for pfeti_dn_dev_HVT_Device_67
15950 0 unpreserved device pfeti_dn_dev_HVT_Device_67
15951 0 unstable device for pfet5_dn_dev_HVT_b_Device_66
15952 0 unpreserved device pfet5_dn_dev_HVT_b_Device_66
15953 0 unstable device for pfeti_dn_dev_HVT_b_Device_65
15954 0 unpreserved device pfeti_dn_dev_HVT_b_Device_65
15955 0 unstable device for pfet5_dn_mul_Device_64
15956 0 unpreserved device pfet5_dn_mul_Device_64
15957 0 unstable device for pfeti_dn_mul_Device_63
15958 0 unpreserved device pfeti_dn_mul_Device_63
15959 0 unstable device for pfet5_dn_dev_Device_62
15960 0 unpreserved device pfet5_dn_dev_Device_62
15961 0 unstable device for pfeti_dn_dev_Device_61
15962 0 unpreserved device pfeti_dn_dev_Device_61
15963 0 unstable device for pfet5_dn_dev_b_Device_60
15964 0 unpreserved device pfet5_dn_dev_b_Device_60
15965 0 unstable device for pfeti_dn_dev_b_Device_59
15966 0 unpreserved device pfeti_dn_dev_b_Device_59
15967 0 unstable device for nfeti_dev_HVT_b_Device_58
15968 0 unpreserved device nfeti_dev_HVT_b_Device_58
15969 0 unstable device for nfeti_mul_HVT_Device_57
15970 0 unpreserved device nfeti_mul_HVT_Device_57
15971 0 unstable device for nfeti_dev_HVT_Device_56
15972 0 unpreserved device nfeti_dev_HVT_Device_56
15973 0 unstable device for nfet_dev_SHVT_b_Device_55
15974 0 unpreserved device nfet_dev_SHVT_b_Device_55
15975 0 unstable device for nfet_mul_SHVT_Device_54
15976 0 unpreserved device nfet_mul_SHVT_Device_54
15977 0 unstable device for nfet_dev_SHVT_Device_53
15978 0 unpreserved device nfet_dev_SHVT_Device_53
15979 0 unstable device for nfet_dev_HVT_b_Device_52
15980 0 unpreserved device nfet_dev_HVT_b_Device_52
15981 0 unstable device for nfet_mul_HVT_Device_51
15982 0 unpreserved device nfet_mul_HVT_Device_51
15983 0 unstable device for nfet_dev_HVT_Device_50
15984 0 unpreserved device nfet_dev_HVT_Device_50
15985 0 unstable device for nfet6_mul_TG_Device_49
15986 0 unpreserved device nfet6_mul_TG_Device_49
15987 0 unstable device for nfet6_dev_TG_Device_48
15988 0 unpreserved device nfet6_dev_TG_Device_48
15989 0 unstable device for nfeti_mul_TG_Device_47
15990 0 unpreserved device nfeti_mul_TG_Device_47
15991 0 unstable device for nfeti_dev_TG_Device_46
15992 0 unpreserved device nfeti_dev_TG_Device_46
15993 0 unstable device for nfet_mul_TG_Device_45
15994 0 unpreserved device nfet_mul_TG_Device_45
15995 0 unstable device for nfet_dev_TG_Device_44
15996 0 unpreserved device nfet_dev_TG_Device_44
15997 0 unstable device for nfet6_mul_Device_43
15998 0 unpreserved device nfet6_mul_Device_43
15999 0 unstable device for nfet6_dev_Device_42
16000 0 unpreserved device nfet6_dev_Device_42
16001 0 unstable device for nfeti_mul_Device_41
16002 0 unpreserved device nfeti_mul_Device_41
16003 0 unstable device for nfeti_dev_b_Device_40
16004 0 unpreserved device nfeti_dev_b_Device_40
16005 0 unstable device for nfeti_dev_Device_39
16006 0 unpreserved device nfeti_dev_Device_39
16007 0 unstable device for nfet_mul_Device_38
16008 0 unpreserved device nfet_mul_Device_38
16009 0 unstable device for nfet_dev_b_Device_37
16010 0 unpreserved device nfet_dev_b_Device_37
16011 0 unstable device for nfet_dev_Device_36
16012 0 unpreserved device nfet_dev_Device_36
16013 0 unstable device for nfet6_dn_mul_TG_Device_35
16014 0 unpreserved device nfet6_dn_mul_TG_Device_35
16015 0 unstable device for nfeti_dn_mul_TG_Device_34
16016 0 unpreserved device nfeti_dn_mul_TG_Device_34
16017 0 unstable device for nfet6_dn_mul_HVT_Device_33
16018 0 unpreserved device nfet6_dn_mul_HVT_Device_33
16019 0 unstable device for nfeti_dn_mul_HVT_Device_32
16020 0 unpreserved device nfeti_dn_mul_HVT_Device_32
16021 0 unstable device for nfet6_dn_mul_Device_31
16022 0 unpreserved device nfet6_dn_mul_Device_31
16023 0 unstable device for nfeti_dn_mul_Device_30
16024 0 unpreserved device nfeti_dn_mul_Device_30
16025 0 unstable device for nfet6_dn_dev_TG_Device_29
16026 0 unpreserved device nfet6_dn_dev_TG_Device_29
16027 0 unstable device for nfeti_dn_dev_TG_Device_28
16028 0 unpreserved device nfeti_dn_dev_TG_Device_28
16029 0 unstable device for nfet6_dn_dev_HVT_Device_27
16030 0 unpreserved device nfet6_dn_dev_HVT_Device_27
16031 0 unstable device for nfeti_dn_dev_HVT_Device_26
16032 0 unpreserved device nfeti_dn_dev_HVT_Device_26
16033 0 unstable device for nfet6_dn_dev_HVT_b_Device_25
16034 0 unpreserved device nfet6_dn_dev_HVT_b_Device_25
16035 0 unstable device for nfeti_dn_dev_HVT_b_Device_24
16036 0 unpreserved device nfeti_dn_dev_HVT_b_Device_24
16037 0 unstable device for nfet6_dn_dev_Device_23
16038 0 unpreserved device nfet6_dn_dev_Device_23
16039 0 unstable device for nfeti_dn_dev_Device_22
16040 0 unpreserved device nfeti_dn_dev_Device_22
16041 0 unstable device for nfet6_dn_dev_b_Device_21
16042 0 unpreserved device nfet6_dn_dev_b_Device_21
16043 0 unstable device for nfeti_dn_dev_b_Device_20
16044 0 unpreserved device nfeti_dn_dev_b_Device_20
16045 0 unstable device for pfet50t_dev_Device_19
16046 0 unpreserved device pfet50t_dev_Device_19
16047 0 unstable device for pfet50m_dev_Device_18
16048 0 unpreserved device pfet50m_dev_Device_18
16049 0 unstable device for pfet50h_dev_Device_17
16050 0 unpreserved device pfet50h_dev_Device_17
16051 0 unstable device for pfet25m_dev_Device_16
16052 0 unpreserved device pfet25m_dev_Device_16
16053 0 unstable device for pfet20t_dev_Device_15
16054 0 unpreserved device pfet20t_dev_Device_15
16055 0 unstable device for pfet20h_dev_Device_14
16056 0 unpreserved device pfet20h_dev_Device_14
16057 0 unstable device for pfet50hs_dev_Device_13
16058 0 unpreserved device pfet50hs_dev_Device_13
16059 0 unstable device for pfet20hs_dev_Device_12
16060 0 unpreserved device pfet20hs_dev_Device_12
16061 0 unstable device for nfeti50t_dev_Device_11
16062 0 unpreserved device nfeti50t_dev_Device_11
16063 0 unstable device for nfeti50m_dev_Device_10
16064 0 unpreserved device nfeti50m_dev_Device_10
16065 0 unstable device for nfeti50h_dev_Device_9
16066 0 unpreserved device nfeti50h_dev_Device_9
16067 0 unstable device for nfeti25m_dev_Device_8
16068 0 unpreserved device nfeti25m_dev_Device_8
16069 0 unstable device for nfeti20t_dev_Device_7
16070 0 unpreserved device nfeti20t_dev_Device_7
16071 0 unstable device for nfeti20h_dev_Device_6
16072 0 unpreserved device nfeti20h_dev_Device_6
16073 0 unstable device for nfet20mh_dev_Device_5
16074 0 unpreserved device nfet20mh_dev_Device_5
16075 0 unstable device for nfet50hs_dev_Device_4
16076 0 unpreserved device nfet50hs_dev_Device_4
16077 0 unstable device for nfet20hs_dev_Device_3
16078 0 unpreserved device nfet20hs_dev_Device_3
16079 0 unstable device for vpnp_dev_Device_2
16080 0 unpreserved device vpnp_dev_Device_2
16081 0 unstable device for vnpn_dev_Device_1
16082 0 unpreserved device vnpn_dev_Device_1
