0 0 dataAuditErrors
2 0 # INFO: I/O PADS = WIREBOND #
395 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (ng      )
397 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (dn      )
399 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (dp      )
401 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (sn      )
403 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (wx      )
405 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (wy      )
407 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (mn      )
409 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (nn      )
411 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (ng      )
413 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (no      )
415 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (sp      )
417 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (tg      )
419 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagbh)
421 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagbf)
423 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagph)
425 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (bfcus   )
427 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (bhcus   )
429 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (phcus   )
431 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (bpcus   )
433 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (tecus   )
435 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (tfcus   )
437 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (nogen   )
439 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagwx)
441 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagwy)
443 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagte)
445 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagtf)
447 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagsn)
449 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagsp)
451 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (kerfexcl)
453 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (outkern )
455 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (fillkern)
457 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m1exc   )
459 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m2exc   )
461 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m3exc   )
463 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m4exc   )
465 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m5exc   )
467 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (mtexc   )
469 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (pcexc   )
471 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (rxexc   )
473 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (rxhv    )
475 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (sblk    )
477 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (BB)
479 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (BFMOAT)
481 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (BONDPAD)
483 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (MOSVAR)
485 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (BP)
487 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (CA)
489 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (CABAR)
491 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (CAP)
493 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (DG)
495 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (DV)
497 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (E1)
499 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (FT)
501 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (FTBAR)
503 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (HT)
505 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (LVDUMMY)
507 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (K1)
509 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (LOGOBND)
511 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (LV)
513 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M1)
515 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M2)
517 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M3)
519 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M4)
521 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M5)
523 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (MOSVAR)
525 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (MT)
527 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (NS)
529 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (NW)
531 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (NWASP)
533 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (OP)
535 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (PC)
537 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (PCING)
539 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (PD)
541 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (PCFUSE)
543 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (QT)
545 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (RN)
547 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (RP)
549 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (RR)
551 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (RX)
553 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V1)
555 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V1BAR)
557 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V2)
559 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V2BAR)
561 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V3)
563 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V3BAR)
565 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V4)
567 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V4BAR)
569 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V5)
571 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V5BAR)
573 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (AM)
575 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (MA)
577 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (E2)
579 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (ML)
581 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (ng      )
583 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (dn      )
585 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (dp      )
587 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (sn      )
589 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (wx      )
591 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (wy      )
593 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (mn      )
595 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (nn      )
597 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (ng      )
599 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (no      )
601 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (sp      )
603 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (tg      )
605 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagbh)
607 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagbf)
609 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagph)
611 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (bfcus   )
613 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (bhcus   )
615 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (phcus   )
617 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (bpcus   )
619 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (tecus   )
621 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (tfcus   )
623 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (nogen   )
625 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagwx)
627 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagwy)
629 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagte)
631 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagtf)
633 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagsn)
635 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (noniagsp)
637 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (kerfexcl)
639 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (outkern )
641 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (fillkern)
643 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m1exc   )
645 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m2exc   )
647 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m3exc   )
649 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m4exc   )
651 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (m5exc   )
653 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (mtexc   )
655 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (pcexc   )
657 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (rxexc   )
659 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (rxhv    )
661 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (rxhv_tex)
663 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (sblk    )
665 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (BB)
667 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (BFMOAT)
669 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (BONDPAD)
671 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (MOSVAR)
673 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (BP)
675 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (CA)
677 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (CABAR)
679 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (CAP)
681 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (DG)
683 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (DV)
685 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (E1)
687 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (FT)
689 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (FTBAR)
691 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (HT)
693 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (LVDUMMY)
695 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (K1)
697 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (LOGOBND)
699 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (LV)
701 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M1)
703 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M2)
705 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M3)
707 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M4)
709 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (M5)
711 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (MOSVAR)
713 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (MT)
715 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (NS)
717 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (NW)
719 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (NWASP)
721 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (OP)
723 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (PC)
725 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (PCING)
727 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (PD)
729 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (PCFUSE)
731 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (QT)
733 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (RN)
735 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (RP)
737 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (RR)
739 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (RX)
741 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V1)
743 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V1BAR)
745 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V2)
747 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V2BAR)
749 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V3)
751 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V3BAR)
753 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V4)
755 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V4BAR)
757 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V5)
759 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (V5BAR)
761 0 offGridShapeErrors: GRCE001: CHIPEDGE x and y dimensions must be an even number of grid points (2*0.01)
763 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (AM)
765 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (MA)
767 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (E2)
769 0 offGridShapeErrors: GRS1: OFF-GRID VERTEX FOUND! (ML)
770 0 GRS10: Use of PCFUSE Label is NOT ALLOWED
771 0 GRS10: Use of BB    Label is NOT ALLOWED
772 0 GRS10: Use of BF    Label is NOT ALLOWED
773 0 GRS10: Use of BH    Label is NOT ALLOWED
774 0 GRS10: Use of BN    Label is NOT ALLOWED
775 0 GRS10: Use of BP    Label is NOT ALLOWED
776 0 GRS10: Use of CA    Label is NOT ALLOWED
777 0 GRS10: Use of CABAR Label is NOT ALLOWED
778 0 GRS10: Use of DE    Label is NOT ALLOWED
779 0 GRS10: Use of DF    Label is NOT ALLOWED
780 0 GRS10: Use of DG    Label is NOT ALLOWED
781 0 GRS10: Use of DGV   Label is NOT ALLOWED
782 0 GRS10: Use of DI    Label is NOT ALLOWED
783 0 GRS10: Use of DV    Label is NOT ALLOWED
784 0 GRS10: Use of FT    Label is NOT ALLOWED
785 0 GRS10: Use of FTBAR Label is NOT ALLOWED
786 0 GRS10: Use of HT    Label is NOT ALLOWED
787 0 GRS10: Use of JD    Label is NOT ALLOWED
788 0 GRS10: Use of K1    Label is NOT ALLOWED
789 0 GRS10: Use of LV    Label is NOT ALLOWED
790 0 GRS10: Use of M1    Label is NOT ALLOWED
791 0 GRS10: Use of M2    Label is NOT ALLOWED
792 0 GRS10: Use of M3    Label is NOT ALLOWED
793 0 GRS10: Use of M4    Label is NOT ALLOWED
794 0 GRS10: Use of M5    Label is NOT ALLOWED
795 0 GRS10: Use of MT    Label is NOT ALLOWED
796 0 GRS10: Use of NR    Label is NOT ALLOWED
797 0 GRS10: Use of NS    Label is NOT ALLOWED
798 0 GRS10: Use of NW    Label is NOT ALLOWED
799 0 GRS10: Use of NWASP Label is NOT ALLOWED
800 0 GRS10: Use of OP    Label is NOT ALLOWED
801 0 GRS10: Use of PC    Label is NOT ALLOWED
802 0 GRS10: Use of PCING Label is NOT ALLOWED
803 0 GRS10: Use of PH    Label is NOT ALLOWED
804 0 GRS10: Use of PI    Label is NOT ALLOWED
805 0 GRS10: Use of PR    Label is NOT ALLOWED
806 0 GRS10: Use of QT    Label is NOT ALLOWED
807 0 GRS10: Use of RN    Label is NOT ALLOWED
808 0 GRS10: Use of RP    Label is NOT ALLOWED
809 0 GRS10: Use of RR    Label is NOT ALLOWED
810 0 GRS10: Use of RX    Label is NOT ALLOWED
811 0 GRS10: Use of V1    Label is NOT ALLOWED
812 0 GRS10: Use of V1BAR Label is NOT ALLOWED
813 0 GRS10: Use of V2    Label is NOT ALLOWED
814 0 GRS10: Use of V2BAR Label is NOT ALLOWED
815 0 GRS10: Use of V3    Label is NOT ALLOWED
816 0 GRS10: Use of V3BAR Label is NOT ALLOWED
817 0 GRS10: Use of V4    Label is NOT ALLOWED
818 0 GRS10: Use of V4BAR Label is NOT ALLOWED
819 0 GRS10: Use of V5    Label is NOT ALLOWED
820 0 GRS10: Use of V5BAR Label is NOT ALLOWED
821 0 GRS10: Use of E1    Label is NOT ALLOWED
822 0 GRS10: Use of AM    Label is NOT ALLOWED
823 0 GRS10: Use of MA    Label is NOT ALLOWED
824 0 GRS10: Use of E2    Label is NOT ALLOWED
825 0 GRS10: Use of ML    Label is NOT ALLOWED
828 0 ERROR: CA(net) not covered by CA(drawing) found!
831 0 ERROR: CABAR(net) not covered by CABAR(drawing) found!
834 0 ERROR: FT(net) not covered by FT(drawing) found!
837 0 ERROR: NS(net) not covered by NS(drawing) found!
840 0 ERROR: NW(net) not covered by NW(drawing) found!
843 0 ERROR: V1(net) not covered by V1(drawing) found!
846 0 ERROR: V1BAR(net) not covered by V1BAR(drawing) found!
849 0 ERROR: V2(net) not covered by V2(drawing) found!
852 0 ERROR: V2BAR(net) not covered by V2BAR(drawing) found!
855 0 ERROR: V3(net) not covered by V3(drawing) found!
858 0 ERROR: V3BAR(net) not covered by V3BAR(drawing) found!
861 0 ERROR: V4(net) not covered by V4(drawing) found!
864 0 ERROR: V4BAR(net) not covered by V4BAR(drawing) found!
867 0 ERROR: V5(net) not covered by V5(drawing) found!
870 0 ERROR: V5BAR(net) not covered by V5BAR(drawing) found!
873 0 ERROR: DV(net or pin) not covered by DV(drawing) found!
876 0 ERROR: LV(net or pin) not covered by LV(drawing) found!
879 0 ERROR: M1(net or pin) not covered by M1(drawing) found!
882 0 ERROR: M2(net or pin) not covered by M2(drawing) found!
885 0 ERROR: M3(net or pin) not covered by M3(drawing) found!
888 0 ERROR: M4(net or pin) not covered by M4(drawing) found!
891 0 ERROR: M5(net or pin) not covered by M5(drawing) found!
894 0 ERROR: MT(net or pin) not covered by MT(drawing) found!
896 0 ERROR: NW(net or pin) not covered by NW(drawing) found!
899 0 ERROR: RX(net or pin) not covered by RX(drawing) found!
902 0 ERROR: E1(net or pin) not covered by E1(drawing) found!
905 0 ERROR: PC(net) not covered by PC(drawing) found!
909 0 ERROR: PC(pin) not covered by PC(drawing) found!
912 0 ERROR: AM(net or pin) not covered by AM(drawing) found!
915 0 ERROR: E2(net) not covered by E2(drawing) found!
918 0 ERROR: MA(net or pin) not covered by MA(drawing) found!
921 0 ERROR: ML(net or pin) not covered by ML(drawing) found!
922 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (BF)
923 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (BH)
924 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (BN)
925 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (DE)
926 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (DF)
927 0 ERROR: SHAPE(S) ON A NON-DESIGN LEVEL FOUND! (PH)
928 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (E1FILL)
929 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M1FILL)
930 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M2FILL)
931 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M3FILL)
932 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M4FILL)
933 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (M5FILL)
934 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (MTFILL)
935 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (PCFILL)
936 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (RXFILL)
937 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (AMFILL)
938 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (MAFILL)
939 0 ERROR: SHAPE(S) ON AN IBM RESERVED LAYER FOUND! (MLFILL)
942 0 GRPN001: Shape straddling LOGOBND found! (SCGATE)
944 0 GRPN001: Shape straddling LOGOBND found! (BB)
945 0 GRPN001: Shape straddling LOGOBND found! (BF)
947 0 GRPN001: Shape straddling LOGOBND found! (BFMOAT)
948 0 GRPN001: Shape straddling LOGOBND found! (BH)
950 0 GRPN001: Shape straddling LOGOBND found! (BHRES)
951 0 GRPN001: Shape straddling LOGOBND found! (BN)
953 0 GRPN001: Shape straddling LOGOBND found! (BP)
954 0 GRPN001: Shape straddling LOGOBND found! (CA)
955 0 GRPN001: Shape straddling LOGOBND found! (CABAR)
957 0 GRPN001: Shape straddling LOGOBND found! (CAP)
958 0 GRPN001: Shape straddling LOGOBND found! (DE)
959 0 GRPN001: Shape straddling LOGOBND found! (DF)
961 0 GRPN001: Shape straddling LOGOBND found! (DG)
963 0 GRPN001: Shape straddling LOGOBND found! (DI)
964 0 GRPN001: Shape straddling LOGOBND found! (DV)
966 0 GRPN001: Shape straddling LOGOBND found! (HT)
968 0 GRPN001: Shape straddling LOGOBND found! (K1)
969 0 GRPN001: Shape straddling LOGOBND found! (LV)
970 0 GRPN001: Shape straddling LOGOBND found! (M1)
972 0 GRPN001: Shape straddling LOGOBND found! (M1CHEXCL)
973 0 GRPN001: Shape straddling LOGOBND found! (M2)
974 0 GRPN001: Shape straddling LOGOBND found! (M3)
975 0 GRPN001: Shape straddling LOGOBND found! (M4)
976 0 GRPN001: Shape straddling LOGOBND found! (M5)
978 0 GRPN001: Shape straddling LOGOBND found! (MIM_HK)
980 0 GRPN001: Shape straddling LOGOBND found! (MIM_HD)
982 0 GRPN001: Shape straddling LOGOBND found! (MOSVAR)
983 0 GRPN001: Shape straddling LOGOBND found! (MT)
984 0 GRPN001: Shape straddling LOGOBND found! (NS)
985 0 GRPN001: Shape straddling LOGOBND found! (NW)
987 0 GRPN001: Shape straddling LOGOBND found! (NWASP)
989 0 GRPN001: Shape straddling LOGOBND found! (OP)
990 0 GRPN001: Shape straddling LOGOBND found! (PC)
992 0 GRPN001: Shape straddling LOGOBND found! (PCING)
994 0 GRPN001: Shape straddling LOGOBND found! (PD)
996 0 GRPN001: Shape straddling LOGOBND found! (PCFUSE)
997 0 GRPN001: Shape straddling LOGOBND found! (PH)
999 0 GRPN001: Shape straddling LOGOBND found! (PHRES)
1001 0 GRPN001: Shape straddling LOGOBND found! (PI)
1003 0 GRPN001: Shape straddling LOGOBND found! (QT)
1005 0 GRPN001: Shape straddling LOGOBND found! (RN)
1007 0 GRPN001: Shape straddling LOGOBND found! (RP)
1009 0 GRPN001: Shape straddling LOGOBND found! (RR)
1010 0 GRPN001: Shape straddling LOGOBND found! (RX)
1011 0 GRPN001: Shape straddling LOGOBND found! (V1)
1012 0 GRPN001: Shape straddling LOGOBND found! (V1BAR)
1013 0 GRPN001: Shape straddling LOGOBND found! (V2)
1014 0 GRPN001: Shape straddling LOGOBND found! (V2BAR)
1015 0 GRPN001: Shape straddling LOGOBND found! (V3)
1016 0 GRPN001: Shape straddling LOGOBND found! (V3BAR)
1017 0 GRPN001: Shape straddling LOGOBND found! (V4)
1018 0 GRPN001: Shape straddling LOGOBND found! (V4BAR)
1019 0 GRPN001: Shape straddling LOGOBND found! (V5)
1020 0 GRPN001: Shape straddling LOGOBND found! (V5BAR)
1022 0 GRPN001: Shape straddling LOGOBND found! (FTBAR)
1023 0 GRPN001: Shape straddling LOGOBND found! (FT)
1025 0 GRPN001: Shape straddling LOGOBND found! (RXHV)
1027 0 GRPN001: Shape straddling LOGOBND found! (VNCAPM1)
1029 0 GRPN001: Shape straddling LOGOBND found! (VNCAPM2)
1031 0 GRPN001: Shape straddling LOGOBND found! (VNCAPM3)
1033 0 GRPN001: Shape straddling LOGOBND found! (VNCAPM4)
1035 0 GRPN001: Shape straddling LOGOBND found! (VNCAPM5)
1037 0 GRPN001: Shape straddling LOGOBND found! (VNCAPMT)
1038 0 GRPN001: Shape straddling LOGOBND found! (AM)
1042 0 GRPN203: CA to CA space (logo) >= 0.400 um.
1045 0 GRPN502: M1 to M1 space (logo) >= 0.400 um.
1047 0 GRPN502: M1 to M1 notch (logo) >= 0.400 um.
1059 0 GRPN553: V1 to V1 space (logo) >= 0.400 um.
1061 0 GRPN553: V2 to V2 space (logo) >= 0.400 um.
1063 0 GRPN553: V3 to V3 space (logo) >= 0.400 um.
1065 0 GRPN553: V4 to V4 space (logo) >= 0.400 um.
1067 0 GRPN553: V5 to V5 space (logo) >= 0.400 um.
1074 0 GRPN602: M2 to M2 space (logo) >= 0.400 um.
1076 0 GRPN602: M3 to M3 space (logo) >= 0.400 um.
1078 0 GRPN602: M4 to M4 space (logo) >= 0.400 um.
1080 0 GRPN602: M5 to M5 space (logo) >= 0.400 um.
1082 0 GRPN602: MT to MT space (logo) >= 0.400 um.
1084 0 GRPN602: M2 to M2 notch (logo) >= 0.400 um.
1086 0 GRPN602: M3 to M3 notch (logo) >= 0.400 um.
1088 0 GRPN602: M4 to M4 notch (logo) >= 0.400 um.
1090 0 GRPN602: M5 to M5 notch (logo) >= 0.400 um.
1092 0 GRPN602: MT to MT notch (logo) >= 0.400 um.
1093 0 GRPN907: DV over LOGOBND found!
1095 0 # WARNING: NOPLYMD Level found #
1106 0 GRNOPLYMD02: If NOPLYMD exists, NOPLYMD must be drawn exactly coincident with CHIPEDGE.
1108 0 # WARNING: NOIBMCRACKSTOP Level found #
1118 0 GRNOCS02: If NOIBMCRACKSTOP exists, NOIBMCRACKSTOP must be drawn exactly coincident with CHIPEDGE.
1154 0 # INFO: 3 Level Metal (M1+MT+AM) #
1155 0 # INFO: 4 Level Metal (M1+M2+MT+AM) #
1156 0 # INFO: 5 Level Metal (M1+M2+M3+MT+AM) #
1157 0 # INFO: 6 Level Metal (M1+M2+M3+M4+MT+AM) #
1158 0 # INFO: 7 Level Metal (M1+M2+M3+M4+M5+MT+AM) #
1161 0 # INFO: 4 Level Metal (M1+MT+E1+MA) #
1162 0 # INFO: 5 Level Metal (M1+M2+MT+E1+MA) #
1163 0 # INFO: 6 Level Metal (M1+M2+M3+MT+E1+MA) #
1164 0 # INFO: 7 Level Metal (M1+M2+M3+M4+MT+E1+MA) #
1165 0 # INFO: 8 Level Metal (M1+M2+M3+M4+M5+MT+E1+MA) #
1168 0 # INFO: 3 Level Metal (M1+MT+ML) #
1169 0 # INFO: 4 Level Metal (M1+M2+MT+ML) #
1170 0 # INFO: 5 Level Metal (M1+M2+M3+MT+ML) #
1171 0 # INFO: 6 Level Metal (M1+M2+M3+M4+MT+ML) #
1172 0 # INFO: 7 Level Metal (M1+M2+M3+M4+M5+MT+ML) #
1177 0 WARNING: MULTIPLE LAST METAL LEVELS FOUND! (AM or MA or ML)
1498 0 GRPHHOLE7: PHHOLE1 enclosed area >= 0.537 sq.um.
1500 0 GRS2: Shapes with acute angles are not allowed (dn         )
1501 0 GRS2: Shapes with acute angles are not allowed (dp         )
1502 0 GRS2: Shapes with acute angles are not allowed (sn         )
1504 0 GRS2: Shapes with acute angles are not allowed (wx         )
1506 0 GRS2: Shapes with acute angles are not allowed (wy         )
1507 0 GRS2: Shapes with acute angles are not allowed (mn         )
1509 0 GRS2: Shapes with acute angles are not allowed (nn         )
1510 0 GRS2: Shapes with acute angles are not allowed (ng         )
1512 0 GRS2: Shapes with acute angles are not allowed (no         )
1513 0 GRS2: Shapes with acute angles are not allowed (sp         )
1514 0 GRS2: Shapes with acute angles are not allowed (tg         )
1515 0 GRS2: Shapes with acute angles are not allowed (noniagbh   )
1516 0 GRS2: Shapes with acute angles are not allowed (noniagbf   )
1517 0 GRS2: Shapes with acute angles are not allowed (noniagph   )
1518 0 GRS2: Shapes with acute angles are not allowed (bfcus      )
1519 0 GRS2: Shapes with acute angles are not allowed (bhcus      )
1520 0 GRS2: Shapes with acute angles are not allowed (phcus      )
1521 0 GRS2: Shapes with acute angles are not allowed (bpcus      )
1522 0 GRS2: Shapes with acute angles are not allowed (tecus      )
1523 0 GRS2: Shapes with acute angles are not allowed (tfcus      )
1525 0 GRS2: Shapes with acute angles are not allowed (nogen      )
1526 0 GRS2: Shapes with acute angles are not allowed (noniagwx   )
1527 0 GRS2: Shapes with acute angles are not allowed (noniagwy   )
1528 0 GRS2: Shapes with acute angles are not allowed (noniagte   )
1529 0 GRS2: Shapes with acute angles are not allowed (noniagtf   )
1530 0 GRS2: Shapes with acute angles are not allowed (noniagsn   )
1531 0 GRS2: Shapes with acute angles are not allowed (noniagsp   )
1533 0 GRS2: Shapes with acute angles are not allowed (kerfexcl   )
1535 0 GRS2: Shapes with acute angles are not allowed (outkern    )
1537 0 GRS2: Shapes with acute angles are not allowed (fillkern   )
1539 0 GRS2: Shapes with acute angles are not allowed (m1exc      )
1541 0 GRS2: Shapes with acute angles are not allowed (m2exc      )
1543 0 GRS2: Shapes with acute angles are not allowed (m3exc      )
1545 0 GRS2: Shapes with acute angles are not allowed (m4exc      )
1547 0 GRS2: Shapes with acute angles are not allowed (m5exc      )
1549 0 GRS2: Shapes with acute angles are not allowed (mtexc      )
1551 0 GRS2: Shapes with acute angles are not allowed (pcexc      )
1553 0 GRS2: Shapes with acute angles are not allowed (rxexc      )
1556 0 GRS2: Shapes with acute angles are not allowed (sblk       )
1557 0 GRS2: Shapes with acute angles are not allowed (bb         )
1558 0 GRS2: Shapes with acute angles are not allowed (bfmoat     )
1560 0 GRS2: Shapes with acute angles are not allowed (bondpad    )
1561 0 GRS2: Shapes with acute angles are not allowed (mosvar     )
1562 0 GRS2: Shapes with acute angles are not allowed (bp         )
1563 0 GRS2: Shapes with acute angles are not allowed (ca         )
1564 0 GRS2: Shapes with acute angles are not allowed (cabar      )
1565 0 GRS2: Shapes with acute angles are not allowed (cap        )
1566 0 GRS2: Shapes with acute angles are not allowed (dg         )
1567 0 GRS2: Shapes with acute angles are not allowed (dv         )
1568 0 GRS2: Shapes with acute angles are not allowed (e1         )
1569 0 GRS2: Shapes with acute angles are not allowed (ft         )
1570 0 GRS2: Shapes with acute angles are not allowed (ftbar      )
1571 0 GRS2: Shapes with acute angles are not allowed (ht         )
1573 0 GRS2: Shapes with acute angles are not allowed (lvdummy    )
1574 0 GRS2: Shapes with acute angles are not allowed (k1         )
1575 0 GRS2: Shapes with acute angles are not allowed (logobnd    )
1576 0 GRS2: Shapes with acute angles are not allowed (lv         )
1577 0 GRS2: Shapes with acute angles are not allowed (m1         )
1578 0 GRS2: Shapes with acute angles are not allowed (m2         )
1579 0 GRS2: Shapes with acute angles are not allowed (m3         )
1580 0 GRS2: Shapes with acute angles are not allowed (m4         )
1581 0 GRS2: Shapes with acute angles are not allowed (m5         )
1582 0 GRS2: Shapes with acute angles are not allowed (mt         )
1583 0 GRS2: Shapes with acute angles are not allowed (ns         )
1584 0 GRS2: Shapes with acute angles are not allowed (nw         )
1585 0 GRS2: Shapes with acute angles are not allowed (nwasp      )
1586 0 GRS2: Shapes with acute angles are not allowed (op         )
1587 0 GRS2: Shapes with acute angles are not allowed (pc         )
1588 0 GRS2: Shapes with acute angles are not allowed (pcing      )
1589 0 GRS2: Shapes with acute angles are not allowed (pd         )
1590 0 GRS2: Shapes with acute angles are not allowed (pcfuse     )
1591 0 GRS2: Shapes with acute angles are not allowed (qt         )
1592 0 GRS2: Shapes with acute angles are not allowed (rn         )
1593 0 GRS2: Shapes with acute angles are not allowed (rp         )
1594 0 GRS2: Shapes with acute angles are not allowed (rr         )
1595 0 GRS2: Shapes with acute angles are not allowed (rx         )
1596 0 GRS2: Shapes with acute angles are not allowed (v1         )
1597 0 GRS2: Shapes with acute angles are not allowed (v1bar      )
1598 0 GRS2: Shapes with acute angles are not allowed (v2         )
1599 0 GRS2: Shapes with acute angles are not allowed (v2bar      )
1600 0 GRS2: Shapes with acute angles are not allowed (v3         )
1601 0 GRS2: Shapes with acute angles are not allowed (v3bar      )
1602 0 GRS2: Shapes with acute angles are not allowed (v4         )
1603 0 GRS2: Shapes with acute angles are not allowed (v4bar      )
1604 0 GRS2: Shapes with acute angles are not allowed (v5         )
1605 0 GRS2: Shapes with acute angles are not allowed (v5bar      )
1606 0 GRS2: Shapes with acute angles are not allowed (am         )
1607 0 GRS2: Shapes with acute angles are not allowed (e2         )
1830 0 GRS6: Non-Orthogonal pc shape found
1832 0 GRS6: Non-allowed geometric pc shape found under 120V devices
1834 0 GRS6: Non-Orthogonal m1 shape found
1836 0 GRS6: Non-allowed geometric pc shape found under 120V devices
1838 0 GRS6: Non-Orthogonal dn shape found
1840 0 GRS6: Non-allowed geometric pc shape found under 120V devices
1842 0 GRS6: Non-Orthogonal dp shape found
1844 0 GRS6: Non-allowed geometric pc shape found under 120V devices
1846 0 GRS6: Non-Orthogonal sn shape found
1848 0 GRS6: Non-Orthogonal wx     shape found
1850 0 GRS6: Non-Orthogonal wy     shape found
1852 0 GRS6: Non-Orthogonal mn     shape found
1854 0 GRS6: Non-Orthogonal nn     shape found
1856 0 GRS6: Non-Orthogonal ng     shape found
1858 0 GRS6: Non-Orthogonal no     shape found
1860 0 GRS6: Non-Orthogonal sp     shape found
1862 0 GRS6: Non-Orthogonal tg     shape found
1864 0 GRS6: Non-Orthogonal noniagbh shape found
1866 0 GRS6: Non-Orthogonal noniagbf shape found
1868 0 GRS6: Non-Orthogonal noniagph shape found
1870 0 GRS6: Non-Orthogonal bfcus shape found
1872 0 GRS6: Non-Orthogonal bhcus shape found
1874 0 GRS6: Non-Orthogonal phcus shape found
1876 0 GRS6: Non-Orthogonal bpcus shape found
1878 0 GRS6: Non-Orthogonal tecus shape found
1880 0 GRS6: Non-Orthogonal tfcus shape found
1882 0 GRS6: Non-Orthogonal nogen shape found
1884 0 GRS6: Non-Orthogonal noniagwx shape found
1886 0 GRS6: Non-Orthogonal noniagwy shape found
1888 0 GRS6: Non-Orthogonal noniagte shape found
1890 0 GRS6: Non-Orthogonal noniagtf shape found
1892 0 GRS6: Non-Orthogonal noniagsn shape found
1894 0 GRS6: Non-Orthogonal noniagsp shape found
1896 0 GRS6: Non-Orthogonal kerfexcl shape found
1898 0 GRS6: Non-Orthogonal outkern shape found
1900 0 GRS6: Non-Orthogonal fillkern shape found
1902 0 GRS6: Non-Orthogonal m1exc shape found
1904 0 GRS6: Non-Orthogonal m2exc shape found
1906 0 GRS6: Non-Orthogonal m3exc shape found
1908 0 GRS6: Non-Orthogonal m4exc shape found
1910 0 GRS6: Non-Orthogonal m5exc shape found
1912 0 GRS6: Non-Orthogonal mtexc shape found
1914 0 GRS6: Non-Orthogonal pcexc shape found
1916 0 GRS6: Non-Orthogonal rxexc shape found
1918 0 GRS6: Non-Orthogonal sblk    shape found
1920 0 GRS6: Non-Orthogonal bb     shape found
1922 0 GRS6: Non-Orthogonal bfmoat shape found
1924 0 GRS6: Non-Orthogonal bondpad shape found
1926 0 GRS6: Non-Orthogonal mosvar shape found
1928 0 GRS6: Non-Orthogonal bp shape found
1930 0 GRS6: Non-Orthogonal ca shape found
1932 0 GRS6: Non-Orthogonal cabar shape found
1934 0 GRS6: Non-Orthogonal capshape found
1936 0 GRS6: Non-Orthogonal dg shape found
1938 0 GRS6: Non-Orthogonal dv shape found
1940 0 GRS6: Non-Orthogonal e1 shape found
1942 0 GRS6: Non-Orthogonal ft shape found
1944 0 GRS6: Non-Orthogonal ftbar shape found
1946 0 GRS6: Non-Orthogonal ht shape found
1948 0 GRS6: Non-Orthogonal lvdummy shape found
1950 0 GRS6: Non-Orthogonal k1      shape found
1952 0 GRS6: Non-Orthogonal logobnd shape found
1954 0 GRS6: Non-Orthogonal lv shape found
1956 0 GRS6: Non-Orthogonal m2 shape found
1958 0 GRS6: Non-Orthogonal m3 shape found
1960 0 GRS6: Non-Orthogonal m4 shape found
1962 0 GRS6: Non-Orthogonal m5 shape found
1964 0 GRS6: Non-Orthogonal mt shape found
1966 0 GRS6: Non-Orthogonal ns shape found
1968 0 GRS6: Non-Orthogonal nw shape found
1970 0 GRS6: Non-Orthogonal nwasp shape found
1972 0 GRS6: Non-Orthogonal op shape found
1974 0 GRS6: Non-Orthogonal pcing shape found
1976 0 GRS6: Non-Orthogonal pd shape found
1978 0 GRS6: Non-Orthogonal pcfuse shape found
1980 0 GRS6: Non-Orthogonal qt shape found
1982 0 GRS6: Non-Orthogonal rn shape found
1984 0 GRS6: Non-Orthogonal rp shape found
1986 0 GRS6: Non-Orthogonal rr shape found
1988 0 GRS6: Non-Orthogonal rx shape found
1990 0 GRS6: Non-Orthogonal v1 shape found
1992 0 GRS6: Non-Orthogonal v1bar shape found
1994 0 GRS6: Non-Orthogonal v2 shape found
1996 0 GRS6: Non-Orthogonal v2bar shape found
1998 0 GRS6: Non-Orthogonal v3 shape found
2000 0 GRS6: Non-Orthogonal v3bar shape found
2002 0 GRS6: Non-Orthogonal v4 shape found
2004 0 GRS6: Non-Orthogonal v4bar shape found
2006 0 GRS6: Non-Orthogonal v5 shape found
2008 0 GRS6: Non-Orthogonal v5bar shape found
2010 0 GRS6: Non-Orthogonal am     shape found
2012 0 GRS6: Non-Orthogonal e2 shape found
2125 0 ERROR: FUSES FOUND! - LASER FUSES ARE NOT OFFERED WITH ANALOG METAL! (AM,MA,ML)
2127 0 ERROR: FUSES FOUND! - LASER FUSES ARE NOT OFFERED WITH ANALOG METAL! (AM,MA,ML)
2260 0 GR990a: RX(chipring) width >= 1.080 um.
2261 0 GR990a: RX(chipring) width >= 1.080 um.
2262 0 GR990b: BP(chipring) width >= 1.520 um.
2263 0 GR990b: BP(chipring) width >= 1.520 um.
2264 0 GR990f: M1(chipring) width >= 1.080 um.
2265 0 GR990f: M1(chipring) width >= 1.080 um.
2266 0 GR990f: M2(chipring) width >= 1.080 um.
2267 0 GR990f: M2(chipring) width >= 1.080 um.
2268 0 GR990f: M3(chipring) width >= 1.080 um.
2269 0 GR990f: M3(chipring) width >= 1.080 um.
2270 0 GR990f: M4(chipring) width >= 1.080 um.
2271 0 GR990f: M4(chipring) width >= 1.080 um.
2272 0 GR990f: M5(chipring) width >= 1.080 um.
2273 0 GR990f: M5(chipring) width >= 1.080 um.
2274 0 GR990g: MT(chipring) width >= 3.240 um.
2275 0 GR990g: MT(chipring) width >= 3.240 um.
2276 0 GR990k: AM(chipring) width >= 2.000 um.
2277 0 GR990k: AM(chipring) width >= 2.000 um.
2278 0 GR990c: BP(chipring) touching BB found!
2283 0 GR990d: CABAR(chipring) width == 0.20 um. (error >)
2284 0 GR990d: CABAR(chipring) width == 0.20 um. (error >)
2285 0 GR990d: CABAR(chipring) width == 0.20 um. (error <)
2286 0 GR990d: CABAR(chipring) width == 0.20 um. (error <)
2291 0 GR990e: V1B_RING width == 0.28 um. (error >)
2292 0 GR990e: V1B_RING width == 0.28 um. (error >)
2293 0 GR990e: V1B_RING width == 0.28 um. (error <)
2294 0 GR990e: V1B_RING width == 0.28 um. (error <)
2299 0 GR990e: V2B_RING width == 0.28 um. (error >)
2300 0 GR990e: V2B_RING width == 0.28 um. (error >)
2301 0 GR990e: V2B_RING width == 0.28 um. (error <)
2302 0 GR990e: V2B_RING width == 0.28 um. (error <)
2307 0 GR990e: V3B_RING width == 0.28 um. (error >)
2308 0 GR990e: V3B_RING width == 0.28 um. (error >)
2309 0 GR990e: V3B_RING width == 0.28 um. (error <)
2310 0 GR990e: V3B_RING width == 0.28 um. (error <)
2315 0 GR990e: V4B_RING width == 0.28 um. (error >)
2316 0 GR990e: V4B_RING width == 0.28 um. (error >)
2317 0 GR990e: V4B_RING width == 0.28 um. (error <)
2318 0 GR990e: V4B_RING width == 0.28 um. (error <)
2323 0 GR990e: V5B_RING width == 0.28 um. (error >)
2324 0 GR990e: V5B_RING width == 0.28 um. (error >)
2325 0 GR990e: V5B_RING width == 0.28 um. (error <)
2326 0 GR990e: V5B_RING width == 0.28 um. (error <)
2331 0 GR990j: FTBAR(chipring) width == 1.24 um. (error >)
2332 0 GR990j: FTBAR(chipring) width == 1.24 um. (error >)
2333 0 GR990j: FTBAR(chipring) width == 1.24 um. (error <)
2334 0 GR990j: FTBAR(chipring) width == 1.24 um. (error <)
2335 0 GR991: RX not within BP(chipring) found!
2337 0 GR991: RX must be within BP(chipring) >= 0.220 um.
2339 0 GR991: RX must be within BP(chipring) >= 0.220 um.
2340 0 GR992: CABAR not within RX(chipring) found!
2342 0 GR992: CABAR must be within RX(chipring) >= 0.440 um.
2344 0 GR992: CABAR must be within RX(chipring) >= 0.440 um.
2345 0 GR993: CABAR not within M1(chipring) found!
2347 0 GR993: CABAR must be within M1(chipring) >= 0.440 um.
2349 0 GR993: CABAR must be within M1(chipring) >= 0.440 um.
2358 0 GR994a: V1BAR must be within M1(chipring) >= 0.400 um.
2360 0 GR994a: V1BAR must be within M1(chipring) >= 0.400 um.
2362 0 GR994a: V1BAR must be within M1(chipring) >= 0.400 um.
2363 0 GR994a: V1BAR not within M1(chipring) found!
2372 0 GR994b: V2BAR must be within M2(chipring) >= 0.400 um.
2374 0 GR994b: V2BAR must be within M2(chipring) >= 0.400 um.
2376 0 GR994b: V2BAR must be within M2(chipring) >= 0.400 um.
2377 0 GR994b: V2BAR not within M2(chipring) found!
2386 0 GR994c: V3BAR must be within M3(chipring) >= 0.400 um.
2388 0 GR994c: V3BAR must be within M3(chipring) >= 0.400 um.
2390 0 GR994c: V3BAR must be within M3(chipring) >= 0.400 um.
2391 0 GR994c: V3BAR not within M3(chipring) found!
2400 0 GR994d: V4BAR must be within M4(chipring) >= 0.400 um.
2402 0 GR994d: V4BAR must be within M4(chipring) >= 0.400 um.
2404 0 GR994d: V4BAR must be within M4(chipring) >= 0.400 um.
2405 0 GR994d: V4BAR not within M4(chipring) found!
2414 0 GR994d1: V5BAR must be within M5(chipring) >= 0.400 um.
2416 0 GR994d1: V5BAR must be within M5(chipring) >= 0.400 um.
2418 0 GR994d1: V5BAR must be within M5(chipring) >= 0.400 um.
2419 0 GR994d1: V5BAR not within M5(chipring) found!
2428 0 GR994e: FTBAR must be within MT(chipring) >= 1.000 um.
2430 0 GR994e: FTBAR must be within MT(chipring) >= 1.000 um.
2432 0 GR994e: FTBAR must be within MT(chipring) >= 1.000 um.
2433 0 GR994e: FTBAR not within MT(chipring) found!
2442 0 GR994f: FTBAR must be within AM(chipring) >= 1.000 um.
2444 0 GR994f: FTBAR must be within AM(chipring) >= 1.000 um.
2446 0 GR994f: FTBAR must be within AM(chipring) >= 1.000 um.
2448 0 GR994f: FTBAR not within AM(chipring) found!
2457 0 GR994f: FTBAR must be within E1(chipring) >= 1.000 um.
2459 0 GR994f: FTBAR must be within E1(chipring) >= 1.000 um.
2461 0 GR994f: FTBAR must be within E1(chipring) >= 1.000 um.
2463 0 GR994f: FTBAR not within E1(chipring) found!
2472 0 GR995a: V1BAR must be within M2(chipring) >= 0.400 um.
2474 0 GR995a: V1BAR must be within M2(chipring) >= 0.400 um.
2476 0 GR995a: V1BAR must be within M2(chipring) >= 0.400 um.
2478 0 GR995a: V1BAR not within M2(chipring) found!
2488 0 GR995b: V1BAR must be within MT(chipring) >= 0.400 um.
2490 0 GR995b: V1BAR must be within MT(chipring) >= 0.400 um.
2492 0 GR995b: V1BAR must be within MT(chipring) >= 0.400 um.
2494 0 GR995b: V1BAR not within MT(chipring) found!
2503 0 GR996a: V2BAR must be within M3(chipring) >= 0.400 um.
2505 0 GR996a: V2BAR must be within M3(chipring) >= 0.400 um.
2507 0 GR996a: V2BAR must be within M3(chipring) >= 0.400 um.
2509 0 GR996a: V2BAR not within M3(chipring) found!
2519 0 GR996b: V2BAR must be within MT(chipring) >= 0.400 um.
2521 0 GR996b: V2BAR must be within MT(chipring) >= 0.400 um.
2523 0 GR996b: V2BAR must be within MT(chipring) >= 0.400 um.
2525 0 GR996b: V2BAR not within MT(chipring) found!
2527 0 GR996c: V3BAR not within M4(chipring) found!
2529 0 GR996c: V3BAR must be within M4(chipring) >= 0.400 um.
2539 0 GR996d: V3BAR must be within MT(chipring) >= 0.400 um.
2541 0 GR996d: V3BAR must be within MT(chipring) >= 0.400 um.
2543 0 GR996d: V3BAR must be within MT(chipring) >= 0.400 um.
2545 0 GR996d: V3BAR not within MT(chipring) found!
2555 0 GR996e: V4BAR must be within MT(chipring) >= 0.400 um.
2557 0 GR996e: V4BAR must be within MT(chipring) >= 0.400 um.
2559 0 GR996e: V4BAR must be within MT(chipring) >= 0.400 um.
2561 0 GR996e: V4BAR not within MT(chipring) found!
2570 0 GR996f: V4BAR must be within M5(chipring) >= 0.400 um.
2572 0 GR996f: V4BAR must be within M5(chipring) >= 0.400 um.
2574 0 GR996f: V4BAR must be within M5(chipring) >= 0.400 um.
2576 0 GR996f: V4BAR not within M5(chipring) found!
2585 0 GR996g: V5BAR must be within MT(chipring) >= 0.400 um.
2587 0 GR996g: V5BAR must be within MT(chipring) >= 0.400 um.
2589 0 GR996g: V5BAR must be within MT(chipring) >= 0.400 um.
2591 0 GR996g: V5BAR not within MT(chipring) found!
2598 0 GR999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2605 0 GR999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2613 0 GR999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2621 0 GR999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2629 0 GR999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2637 0 GR999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2645 0 GR999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2653 0 GR999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2661 0 GR999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2669 0 GR999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2676 0 GR999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2683 0 GR999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error >)
2685 0 GR999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2687 0 GR999: M1(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2689 0 GR999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2691 0 GR999: M2(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2693 0 GR999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2695 0 GR999: M3(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2697 0 GR999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2699 0 GR999: M4(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2701 0 GR999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2703 0 GR999: M5(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2705 0 GR999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2707 0 GR999: RX(chipring) must be within CHIPEDGE == 11.06 um. (error <)
2721 0 ERROR: CHIPEDGE is not bounded at X=0 on the left or not bounded at Y=0 on the bottom
2732 0 GR999a: OP must be within CHIPEDGE >= 11.06 um
2741 0 GR999a: PI must be within CHIPEDGE >= 11.06 um
2750 0 GR999a: NW must be within CHIPEDGE >= 11.06 um
2759 0 GR999a: PC must be within CHIPEDGE >= 11.06 um
2768 0 GR999a: NS must be within CHIPEDGE >= 11.06 um
2777 0 GR999a: RX must be within CHIPEDGE >= 11.06 um
2786 0 GR999a: RN must be within CHIPEDGE >= 11.06 um
2795 0 GR999a: PR must be within CHIPEDGE >= 11.06 um
2804 0 GR999a: NR must be within CHIPEDGE >= 11.06 um
2813 0 GR999a: RR must be within CHIPEDGE >= 11.06 um
2822 0 GR999a: RP must be within CHIPEDGE >= 11.06 um
2831 0 GR999a: DG must be within CHIPEDGE >= 11.06 um
2840 0 GR999a: BB must be within CHIPEDGE >= 11.06 um
2849 0 GR999a: K1 must be within CHIPEDGE >= 11.06 um
2858 0 GR999a: HT must be within CHIPEDGE >= 11.06 um
2867 0 GR999a: QT must be within CHIPEDGE >= 11.06 um
2876 0 GR999a: CA must be within CHIPEDGE >= 11.06 um
2885 0 GR999a: CABAR must be within CHIPEDGE >= 11.06 um
2894 0 GR999a: M1 must be within CHIPEDGE >= 11.06 um
2903 0 GR999a: V1 must be within CHIPEDGE >= 11.06 um
2912 0 GR999a: V1BAR must be within CHIPEDGE >= 11.06 um
2921 0 GR999a: M2 must be within CHIPEDGE >= 11.06 um
2930 0 GR999a: V2 must be within CHIPEDGE >= 11.06 um
2939 0 GR999a: V2BAR must be within CHIPEDGE >= 11.06 um
2948 0 GR999a: M3 must be within CHIPEDGE >= 11.06 um
2957 0 GR999a: V3 must be within CHIPEDGE >= 11.06 um
2966 0 GR999a: V3BAR must be within CHIPEDGE >= 11.06 um
2975 0 GR999a: M4 must be within CHIPEDGE >= 11.06 um
2984 0 GR999a: V4 must be within CHIPEDGE >= 11.06 um
2993 0 GR999a: V4BAR must be within CHIPEDGE >= 11.06 um
3002 0 GR999a: M5 must be within CHIPEDGE >= 11.06 um
3011 0 GR999a: V5 must be within CHIPEDGE >= 11.06 um
3020 0 GR999a: V5BAR must be within CHIPEDGE >= 11.06 um
3029 0 GR999a: MT must be within CHIPEDGE >= 11.06 um
3038 0 GR999a: FT must be within CHIPEDGE >= 11.06 um
3047 0 GR999a: FTBAR must be within CHIPEDGE >= 11.06 um
3056 0 GR999a: DV must be within CHIPEDGE >= 11.06 um
3065 0 GR999a: LV must be within CHIPEDGE >= 11.06 um
3074 0 GR999a: E1 must be within CHIPEDGE >= 11.06 um
3083 0 GR999a: BFGEN must be within CHIPEDGE >= 11.06 um
3092 0 GR999a: PHGEN must be within CHIPEDGE >= 11.06 um
3101 0 GR999a: BHGEN must be within CHIPEDGE >= 11.06 um
3110 0 GR999a: MA must be within CHIPEDGE >= 11.06 um
3119 0 GR999a: AM must be within CHIPEDGE >= 11.06 um
3128 0 GR999a: ML must be within CHIPEDGE >= 11.06 um
3137 0 GR999a: E2 must be within CHIPEDGE >= 11.06 um
3142 0 GR999a: Background enclosing a pad must contain CHIPEDGE!
3143 0 GR999b: BP(guardring) straddling CHIPEDGE found!
3163 0 GR999b: BP(guardring) within CHIPEDGE >= 9.280 um.
3165 0 GR999b: BP(guardring) within CHIPEDGE >= 9.280 um.
3181 0 GR999c: MT(ring) must be within CHIPEDGE == 11.06 um.(error <)
3183 0 GR999c: MT(ring) must be within CHIPEDGE == 11.06 um.(error <)
3184 0 GR999c: MT(ring) must be within CHIPEDGE == 11.06 um.(error >)
3202 0 GR999c: AM(ring) must be within CHIPEDGE == 11.06 um.(error <)
3204 0 GR999c: AM(ring) must be within CHIPEDGE == 11.06 um.(error <)
3205 0 GR999c: AM(ring) must be within CHIPEDGE == 11.06 um.(error >)
3206 0 GR999e: NW not allowed in chip Chip guardring area!
3207 0 GR999e: OP not allowed in chip Chip guardring area!
3208 0 GR999e: PC not allowed in chip Chip guardring area!
3209 0 GR999e: DI not allowed in chip Chip guardring area!
3212 0 GR999e: BP must be within chipring
3214 0 GR999e: CABAR must be within chipring
3216 0 GR999e: M1 must be within chipring
3218 0 GR999e: V1BAR must be within chipring
3220 0 GR999e: RX must be within chipring
3223 0 GR999e: M2 must be within chipring
3227 0 GR999e: V2BAR must be within chipring
3230 0 GR999e: M3 must be within chipring
3234 0 GR999e: V3BAR must be within chipring
3237 0 GR999e: M4 must be within chipring
3241 0 GR999e: V4BAR must be within chipring
3244 0 GR999e: M5 must be within chipring
3248 0 GR999e: V5BAR must be within chipring
3252 0 GR999e: MT must be within chipring
3259 0 GR999e: FT/FTBAR must be within chipring
3263 0 GR999e: E1 must be within chipring
3267 0 GR999e: E2 must be within chipring
3270 0 GR999e: MA must be within chipring
3273 0 GR999e: ML must be within chipring
3276 0 GR999e: AM must be within chipring
3279 0 GR1000: GUARDRING IS NOT CONNECTED TO A PAD! (AM)
3282 0 GR1000: GUARDRING IS NOT CONNECTED TO A PAD! (MA)
3285 0 GR1000: GUARDRING IS NOT CONNECTED TO A PAD! (ML)
3286 0 GR1: (PC over RX)(NFET) width >= 0.180 um.
3287 0 GR2: (PC over RX)(PFET) width >= 0.180 um.
3289 0 GR3: (PC over RX)(NFET) width for 45 deg >= 0.196 um.
3291 0 GR4: (PC over RX)(PFET) width for 45 deg >= 0.196 um.
3295 0 GR10: RX width under PC for NFET device >= 0.220 um.
3297 0 GR11: RX width under PC for PFET device >= 0.220 um.
3308 0 GR40b: RX space if both RX shapes are wider than 50.0um >= 2.00 um (space).
3310 0 GR40b: RX space if both RX shapes are wider than 50.0um >= 2.00 um (notch).
3311 0 GR50b: RX width (max) <= 200.000 um.
3312 0 GR50: RX width (min) >= 0.220 um.
3313 0 GR51: RX area >= 0.160 sq.um.
3315 0 GR52: RX space >= 0.260 um.
3317 0 GR52: RX notch >= 0.260 um.
3326 0 GRRX8b: (BF not touching (NW or RXHV)) to adjacent NW >= 1.140 um.
3327 0 GRRX8d: ((BF touch NW) touch NWASP) to adj (NW over NWASP) >= 0.700 um.
3340 0 GRRX23: ((RX over BB), not IND_FILT,not PC) not covered by {PD,RN,SBD} found!
3401 0 GR100: PC(not over {RX,((RXHV sized by +0.02) sized by -0.02)}) width >= 0.180 um.
3405 0 GR101a: PC area >= 0.203 sq. um.
3406 0 GR101b: PC enclosed area >= 0.291 sq. um.
3417 0 GR102a: (PC(NOT END) to PC(NOT END) space) (not over RX) >= 0.240 um.
3421 0 GR102a: (PC(NOT END) to PC(NOT END) notch) (not over RX) >= 0.240 um.
3427 0 GR102b: (PCEND to PC space) (not over RX)>= 0.180 um.
3434 0 GR102b: (PCEND to PCEND space) (not over RX) >= 0.180 um.
3437 0 GR104a: PC(over RX) space >= 0.240 um.
3440 0 GR104b: PC(over RX) space >= 0.240 um.
3447 0 GR110_HV: RX overlap past (PC not over RXHV) >= 0.280 um.
3450 0 GR110_HV: RX overlap past (PC not over RXHV) >= 0.280 um.(coincident)
3454 0 GR110_HV: RX overlap past (PC not over RXHV) >= 0.280 um.(45 deg. gate)
3462 0 GR111_HV: PC overlap past (RX not RXHV) >= 0.240 um.
3464 0 GR111_HV: PC overlap past (RX not RXHV) >= 0.240 um.(coincident)
3478 0 GR112_HV: (PC not over RXHV) overlap past RX (within 0.08 of RX corner) >= 0.300 um.
3481 0 GR114: PC to RX corner >= 0.060 um.
3482 0 GR114: PC abutting RX corner found!
3493 0 GR115: PC corner to RX >= 0.080 um.
3494 0 GR115: RX abutting PC corner found!
3551 0 GR119: PC Vertex within RX >= 0.280 um.
3580 0 GR120a: Non 45 degree PC vertices over RX found!(90 degree)
3587 0 GR120a: Non 45 degree PC vertices over RX found!(non 45)
3589 0 GR120b: Dist between inside corners of 45 degree gate >= 0.080 um.
3591 0 GR120c: (PC over RX) notch >= 0.460 um.
3603 0 GR121: PC intersecting RX at other than 90 degrees found!
3613 0 GR123b: Dist between inside corners of (RX under PC) >= 0.080 um.
3618 0 GR125: (PC over RX) dividing RX into less than 2 diffusions found!
3620 0 GR130b: (PC not intersecting RX) to RX >= 0.080 um.
3623 0 GRBB131: ((NW not over MOSVAR ) touching GRLOGIC) cannot touch a BB hole.
3625 0 GR200: CA width and length == 0.200 um.(error <)
3626 0 GR200: CA width and length == 0.200 um.(error >)
3630 0 GR201: Non-rectangular CA found!
3631 0 GR201: 45 degree CA or CABAR found
3633 0 GR203a: CA space >= 0.240 um.
3635 0 GR204: CA within RX >= 0.100 um.
3637 0 GR204a: CABAR within RX >= 0.200 um.
3638 0 GR207: CA(over RX) to adjacent PC >= 0.160 um.
3641 0 GR208: CA(over PC) to adjacent RX >= 0.160 um.
3642 0 GR208a: CABAR(over PC) to adjacent RX >= 0.200 um.
3644 0 GR209: CA within PC >= 0.060 um.
3646 0 GR209a: CABAR within PC >= 0.160 um.
3647 0 GR211: {CA,CABAR} over (PC over RX) found!
3649 0 GR212: {CA,CABAR} not over {RX or PC} found!
3651 0 GR220: CABAR width == 0.200 um.(error >)
3652 0 GR220: CABAR width == 0.200 um.(error <)
3654 0 GR221: Non-rectangular CABAR found!
3655 0 GR221: CABAR length (min) >= 0.600 um.
3656 0 GR222: CABAR length (max) <= 5.000 um.
3657 0 GR223c: CA touching CABAR found!
3659 0 GR223a: CABAR space >= 0.360 um.
3661 0 GR223b: CABAR space (run > 2.5) >= 0.520 um.
3662 0 GR223c: CABAR to adjacent CA >= 0.280 um.
3664 0 GR225: CABAR(over RX) to adjacent PC >= 0.240 um.
3668 0 GR250: NW(drawn or generated) width >= 0.700 um.
3672 0 GR252c: RX shape between (NW shapes < 1.28 um. apart) found!
3673 0 GRNWASP1: NW straddling NWASP found!
3675 0 GR252a: NW(not over NWASP) space >= 1.280 um.
3676 0 GR252a: NW(not over NWASP) to NW(over NWASP) space >= 1.280 um.
3678 0 GR252b: NW(over NWASP) space (run  < 0.70) >= 1.280 um.
3680 0 GR252b: NW(over NWASP) space (run >= 0.70) >= 0.840 um.
3682 0 GR252b: NW notch (run  < 0.70) >= 1.280 um.
3684 0 GR252b: NW notch (run >= 0.70) >= 0.840 um.
3696 0 GR260a: (RX within BP) within NW(>=40.0) >= 0.520 um.
3701 0 GRCP260: (RX(P+) not touching NW) must be within BB >= 1.280 um.
3703 0 GRCP260c: RX(N contact) within BB >= 1.280 um.
3706 0 GR261f: RX(NWcont) overlap of NW >= 0.280 um.
3709 0 GR262c: RX(NWcont)  within NW >= 0.000um.
3718 0 GR262: RX(NWcont) overlap area with NW >= 0.150 sq.um.
3719 0 GR262b: (RX within RN) intersect area with BB >= 0.150 sq.um.
3720 0 GR262f: RX(NWcont) overlap area with NW >= 0.240 sq.um.
3721 0 GR261: RX(NWcont) overlap of NW >= 0.460 um.
3724 0 GR265: RX(outside BP) to adjacent NW (diff net) >= 0.420 um.
3726 0 GR265a: RX(outside BP) to adjacent NW(>=40.0) >= 0.520 um.
3728 0 GRCP265b: (RX outside BP) to adj BB (diff net) >= 0.420 um.
3730 0 GRCP265c: (((RX outside BP) touching (TG RX5V)) over DN) to adj BB (diff net) >= 0.860 um.
3731 0 GR266: RX Sub contact to adjacent NW >= 0.080 um.
3732 0 GR266: RX IsoPwell contact to adjacent NW >= 0.080 um.
3733 0 GRCP266c: (RX(in BP) no NW) to BB space >= 0.400 um.
3797 0 GR268: RX(in BP) to RX(not BP) (in same NW) space <= 53.000 um.
11231 0 GR268b: RX(N+ Jct) to (Substrate Contact not over TG) space <= 53.000 um.
11239 0 GRBB268: (RX over PD) to RX(not PD) (same BB) space <= 53.000 um.
11251 0 GR268g_HV: ((NW, BB, BFMOAT, SN) donut  not over RXHV ) without a substrate or PWell contact found!
11257 0 GRNW4: NW overlapping BB found!
11258 0 GRNW4: NW to adjacent BB >= 1.760 um.
11260 0 GRVTSENS00: (PC over RX) straddling VTSENS found!
11262 0 GRVTSENS01: ((PC over RX) over VTSENS) to BB space >= 3.00 um.
11263 0 GRVTSENS01: ((PC over RX) over VTSENS) to BFMOAT space >= 3.00 um.
11264 0 GRVTSENS01: ((PC over RX) over VTSENS) to MOSVAR space >= 3.00 um.
11265 0 GRVTSENS01: ((PC over RX) over VTSENS) to NW space >= 3.00 um.
11266 0 GRVTSENS01: ((PC over RX) over VTSENS) to TG space >= 3.00 um.
11267 0 GRVTSENS01: ((PC over RX) over VTSENS) to SN space >= 3.00 um.
11268 0 GRVTSENS01: ((PC over RX) over VTSENS) to SP space >= 3.00 um.
11271 0 GRVTSENS02: (((PC over RX) over BP) over VTSENS) straddling TG found!
11273 0 GRVTSENS02: (((PC over RX) over BP) over VTSENS) within TG >= 2.30 um.
11275 0 GRVTSENS02: (((PC over RX) over BP) over VTSENS) within NW >= 2.30 um.
11280 0 GRVTSENS03: (((PC over RX) touching TG) over VTSENS) within DN >= 5.00 um.
11281 0 GR290: NR width >= 0.640 um.
11282 0 GR291: Non-orthogonal NR shape found!
11284 0 GR292: NR to NR  space >= 0.540 um.
11286 0 GR292: NR to NR  notch >= 0.540 um.
11290 0 GR294a: [(PC intersect RX) not within NW] to NR  space >= 0.260 um.
11291 0 GR294b: [(PC intersect RX) not within NW] straddling NR found!
11295 0 GR294b: [(PC intersect RX) not within NW] within NR >= 0.260 um.
11297 0 GR299b: NR overlap past NW >= 1.400 um.
11305 0 GRNR10 : NR touching (NE PE BB, MOSVAR, PD, DI) found!
11306 0 GRNR12 : NR to PCFUSE >= 1.400 um.
11307 0 GRNR12 : NR touching PCFUSE found!
11309 0 GRNR13: NR not touching (PC over RX) found!
11310 0 GRNR17: NR area >= 0.79 sq.um.
11314 0 GRNR18: NR enclosed area >= 0.79 sq.um.
11315 0 GRLW00: PR width >= 0.640 um.
11316 0 GRLW01: Non-orthogonal PR shape found!
11318 0 GRLW02: PR to PR  space >= 0.540 um.
11320 0 GRLW02: PR to PR  notch >= 0.540 um.
11324 0 GRLW04a: [(PC intersect RX) within NW] to PR  space >= 0.260 um.
11325 0 GRLW04b: [(PC intersect RX) within NW] straddling PR found!
11329 0 GRLW04b: [(PC intersect RX) within NW] within PR >= 0.260 um.
11330 0 GRLW09: PR overlap past NW >= 0.860 um.
11336 0 GRLW10 : PR touching (NE PE BB, MOSVAR, PD, DI) found!
11337 0 GRLW12 : PR to PCFUSE >= 1.400 um.
11338 0 GRLW12 : PR touching PCFUSE found!
11340 0 GRLW13: PR not touching (PC over RX) found!
11341 0 GRLW17: PR area >= 0.79 sq.um.
11345 0 GRLW18: PR enclosed area >= 0.79 sq.um.
11346 0 GRNE1: NE width >=0.44.
11348 0 GRNE2: NE space >=0.44.
11350 0 GRNE2: NE notch >=0.44.
11352 0 GRNE3: (PC interesct RX) to NE space >=1.00.
11354 0 GRNE4: (PC interesct RX) within NE  >=1.00.
11358 0 GRNE5: (PC touching OP) is found!
11359 0 GRNE5: ((PC or RX) touching OP) to NE space >=1.00.
11374 0 GRNE10: NE touching( DN PE NR PR BB MOSVAR PD DI ) found!
11375 0 GRNE12: NE to PCFUSE space >=2.50.
11376 0 GRNE12: NE touching PCFUSE found!
11377 0 GRNE13: NE must touch (PC over RX).
11378 0 GRNE15: NE to NW space >=0.44 .
11379 0 GRNE15: NE overlap NW found!
11380 0 GRNE16: NE to BB  space >=0.44 .
11381 0 GRNE16: NE to SN  space >=0.44 .
11382 0 GRNE16: NE to NG  space >=0.44 .
11383 0 GRNE16: NE to TG  space >=0.44 .
11384 0 GRNE16: NE to MOSVAR  space >=0.44 .
11386 0 GRNE16: NE to (BP touching PCFUSE) space >=0.44 .
11401 0 GRNE16: NE to ((intersection ((PC-RX) OP) expanded by 0.16) extended over PC by 0.42)  space >=0.44 .
11402 0 GRNE16: NE touching BB found!
11403 0 GRNE16: NE touching SN found!
11404 0 GRNE16: NE touching NG found!
11405 0 GRNE16: NE touching TG found!
11406 0 GRNE16: NE touching MOSVAR found!
11407 0 GRNE16: NE touching (BP touching PCFUSE) found!
11408 0 GRNE16: NE touching ((intersection ((PC-RX) OP) expanded by 0.16) extended over PC by 0.42) found!
11409 0 GRNE17: NE area >= 0.79 sq.um.
11413 0 GRNE18: NE enclosed area >= 0.79 sq.um.
11416 0 GRNE104: PC over NE space >=0.34 .
11418 0 GRNE104: (PC over NE) to unrelated PC  space >=0.34 .
11422 0 GRNE111: PC overlap past (RX touching NE)) >= 0.46 um.
11424 0 GRNE111: PC overlap past (RX touching NE)) >= 0.46 um.(coincident)
11425 0 GRPE1: PE width >=0.44.
11427 0 GRPE2: PE space >=0.44.
11429 0 GRPE2: PE notch >=0.44.
11431 0 GRPE3: (PC interesct RX) to PE space >=1.00.
11433 0 GRPE4: (PC interesct RX) within PE  >=1.00.
11437 0 GRPE5: (PC touching OP) is found!
11438 0 GRPE5: ((PC or RX) touching OP) to PE space >=1.00.
11453 0 GRPE10: PE touching( DN NE NR PR BB MOSVAR PD DI ) found!
11454 0 GRPE12: PE to PCFUSE space >=2.50.
11455 0 GRPE12: PE touching PCFUSE found!
11456 0 GRPE13: PE must touch (PC over RX).
11457 0 GRPE15: PE must be within NW >=0.0
11459 0 GRPE16: (NW overlap past PE) >= 0.44 .
11460 0 GRPE17: PE area >= 0.79 sq.um.
11464 0 GRPE18: PE enclosed area >= 0.79 sq.um.
11467 0 GRPE104: PC over PE space >=0.34 .
11469 0 GRPE104: (PC over PE) to unrelated PC  space >=0.34 .
11473 0 GRPE111: PC overlap past (RX touching PE)) >= 0.46 um.
11475 0 GRPE111: PC overlap past (RX touching PE)) >= 0.46 um.(coincident)
11480 0 GR350: BP width >= 0.340 um.
11485 0 GR351a: BP area >= 0.387 sq.um.
11486 0 GR351b: BP enclosed area >= 0.387 sq.um.
11488 0 GR352: BP space >= 0.340 um.
11490 0 GR352: BP notch >= 0.340 um.
11513 0 GR354b: (RX(Isopwell cont) over (NW +0.42)) within BP >= 0.140 um.
11516 0 GR354b pdbutt modified: (RX(sub cont) over (NW +0.42)) within BP >= 0.140 um.
11532 0 GR355: (RX(not over BP)not over NW) to BP space >= 0.140 um.
11538 0 GR356b: (RX(nw cont) not over (NW -0.42)) to adj BP >= 0.140 um.
11555 0 GR357: Layout will cause: BH to NW space >= 0.440 um.
11557 0 GR357: Layout will cause: BH to BB space >= 0.440 um.
11559 0 GR357: Layout will cause: BH to MOSVAR space >= 0.440 um.
11561 0 GR357a: Layout will cause: BH width >= 0.440 um.
11564 0 GR357b: Layout will cause: BH space >= 0.440 um.
11567 0 GR357b: Layout will cause: BH notch >= 0.440 um.
11592 0 GR358b: BP to PD space >= 0.340 um.
11593 0 GR358c: Layout will cause: BN to PD space >= 0.340 um.
11595 0 GR358d: Layout will cause: PH width >= 0.440 um.
11597 0 GR358e: Layout will cause: BN width >= 0.340 um.
11600 0 GR358f: Layout will cause: BN space >= 0.340 um.
11603 0 GR358f: Layout will cause: BN notch >= 0.340 um.
11604 0 GR358g_HV: (BF or (( RXHV sized by +0.7) sized by -0.7 ) sized by 0.2) width >= 0.980 um.
11622 0 GR358h_HV: Layout will cause: BF space (not over (GRLOGIC or ((RXHV sized by 0.6) sized by - 0.6))) >= 1.000 um.
11634 0 GR358h_HV: Layout will cause: BF space (not over (GRLOGIC or ((RXHV sized by 0.6) sized by - 0.6))) >= 1.000 um.
11637 0 GR358i: Layout will cause: PH space >= 0.440 um.
11640 0 GR358i: Layout will cause: PH notch >= 0.440 um.
11652 0 GR370: ((PC over RX) not over RXHV) to BP space >= 0.360 um.
11653 0 GR370: ((PC over RX) not over RXHV) to BP space (gate end)>= 0.360 um.
11654 0 GR370b: (PC over RX) touching PD found!
11655 0 GR370a: (PC over RX) to BB space >= 0.500 um.
11656 0 GR370b: (PC over RX) to PD >= 0.500 um.
11657 0 GR371_HV: ((PC over RX) not over RXHV) straddling BP found!
11659 0 GR371_HV: ((PC over RX) not over RXHV) within BP >= 0.360 um.
11662 0 GR378_HV: (BP inter RX) to adj (((PC intersect RX) not over RXHV) not in BP) >= 0.280 um.
11666 0 GR379_HV: (BP inter RX) overlap past (((PC intersect RX) in BP) not over RXHV) >= 0.280 um.
11667 0 GRBP3: BP touching BB found!
11671 0 GR372: (BP overlap of RX) not over NW >= 0.220 um.
11672 0 GR372a: Substrate contact area >= 0.147 sq.um.
11675 0 GR373: (RX overlap past BP) over NW  >= 0.220 um.
11676 0 GR373a: Well contact area >= 0.147 sq.um.
11677 0 GR374: RX straddling NW (butted n-well cont) found!
11679 0 GR374: RX within NW (butted n-well cont) >= 0.120 um.
11685 0 GR380: DI must be within BP == 0.040 um. (error >)
11686 0 GR380: DI outside of BP found.
11689 0 GR380c: NW(touching DI) touching BB found!
11691 0 GR380c: NW(touching DI) touching DN found!
11692 0 GR380d: NW(touching DI) touching RP found!
11693 0 GR380d: NW(touching DI) touching RR found!
11694 0 GR380e: NW(touching DI) touching TG found!
11695 0 GR380e: NW(touching DI) touching OP found!
11696 0 GR380e: NW(touching DI) touching PC found!
11698 0 GR380g: BP(touching DI) touching PD found!
11700 0 GR380: DI must be within BP == 0.040 um. (error <)
11701 0 GR380d: NW(touching DI) to RP space >= 2.500 um.
11702 0 GR380d: NW(touching DI) to RR space >= 2.500 um.
11704 0 GR381: RX straddling DI found!
11708 0 GR381b: RX within DI <= 0.340 um.
11710 0 GR381: RX within DI >= 0.100 um.
11717 0 GR382b: RX(NWcont) to DI space <= 0.540 um.
11718 0 GR382b: DI not within an RX(NWcont) hole found!
11720 0 GR383: DI not enclosing an RX shape found!
11722 0 GR385a: RX(not GRLOGIC) width (max) (when RX touches DI) <= 2.000 um.
11723 0 GR385: RX width (min) (when RX touches DI) >= 1.000 um.
11724 0 GR387: RX(touching DI) not within NW found!
11739 0 GR387b: ((NW(touching DI) expanded by 0.36um) edges) must be covered by ((((RX touching CA) not touching PC) over BP) not over (NW or BB))!
11741 0 GR388: (RX(NWcont) over NW(touching DI)) to BP space >= 0.140 um.
11750 0 GR389: (RX(sxcont) over (NW(touch DI) +1.0)) within BP >= 0.140 um.
11751 0 GRDIPI00: DIPI touching BP found!
11753 0 GRDIPI00: DIPI must be exact space to BP == 0.04 (error <)
11757 0 GRDIPI00: DIPI must be exact space to BP == 0.04 (error >)
11758 0 GRDIPI00c: DIPI must be covered by DN
11766 0 GRDIPI00d: DIPI touching (RR RP NE PE TG SN DP SP) found!
11767 0 GRDIPI00d: DIPI space to (RR RP NE PE TG SN DP SP) >= 2.50
11780 0 GRDIPI00e: DIPI touching (NW BP PC OP BB PD NR PR NG RN RXHV MOSVAR RXHV_IBM) found!
11782 0 GRDIPI01: RX minimum within DIPI >= 0.10
11787 0 GRDIPI01b: RX maximum within DIPI >= 0.34
11804 0 GRDIPI02b: RX isolated p-well contact maximum space to DIPI <= 0.54
11827 0 GRDIPI02c: RX isolated p-well contact touching (DIPI sized by 0.54) maximum space to RX isolated  n-well contact ring <= 1.00
11829 0 GRDIPI03: DIPI must enclose RX
11831 0 GRDIPI05: RX minimum width for RX within DIPI >=1.00
11834 0 GRDIPI5a: (RX not over GRLOGIC) maximum width for RX within DIPI >=2.00
11837 0 GRDIPI07: (RX within DIPI) must be within ((DN not over NW) not over BP)
11847 0 GRDIPI08: RX isolated p-well contact over (DIPI sized by 1.00) minimum within BP >=0.14
11856 0 GRDIPI09: (RX isolated p-well contact over (DIPI sized by 1.00) not over GRLOGIC) exact space to NW == 0.50 um (error <).
11863 0 GRDIPI09: (RX isolated p-well contact over (DIPI sized by 1.00) not over GRLOGIC) exact space to NW == 0.50 um (error>).
11871 0 GR710: (OP intersect RX) length >= 0.480 um.
11879 0 GR711: (OP intersect RX) width >= 0.280 um.
11890 0 GR711HV: ((((OP intersect RX) over BP) over NW) over DN)  width >= 1.000 um.
11894 0 GR712: (OP intersect PC) length >= 1.060 um.
11902 0 GR713: (OP intersect PC) width >= 0.280 um.
11905 0 GR715a: ((RX touching OP) outside BP) touching NW found!
11907 0 GR715f: RX(over OP) touching BB found!
11908 0 GR715a: ((RX touching OP) outside BP) to NW space >= 0.420 um.
11909 0 GR716a: (RX touching OP) straddling NW found!
11910 0 GR716a: (RX touching OP) straddling BB found!
11912 0 GR716b: ((OP intersect RX) touching NW ) not touching BP found!
11915 0 GR717b: (PC intersect OP) straddling NW found!
11916 0 GR717a: (PC intersect OP) to NW space >= 0.600 um.
11918 0 GR717b: (PC intersect OP) within NW >= 0.860 um.
11919 0 GR725: OP width >= 0.480 um.
11921 0 GR726: OP space >= 0.480 um.
11923 0 GR726: OP notch >= 0.480 um.
11925 0 GR727: OP overlap past RX >= 0.180 um.
11929 0 GR729a: OP area >= 0.720 sq.um.
11930 0 GR729b: OP enclosed area >= 0.720 sq.um.
11932 0 GR730: OP overlap past PC >= 0.200 um.
11937 0 GROP9a: (OP over RP) overlap of PD == 0.380 um.(error >)
11938 0 GROP9a: (OP over RR) overlap of PD == 0.380 um.(error >)
11939 0 GROP9: OP to adjacent PD >= 0.440 um.
11940 0 GROP9a: (OP over RP) overlap of PD == 0.380 um.(error <)
11941 0 GROP9a: (OP over RR) overlap of PD == 0.380 um.(error <)
11942 0 GR732: CA/CABAR over OP found!
11943 0 GR733: CA to OP space >= 0.180 um.
11944 0 GR733a: CABAR to OP space >= 0.360 um.
11950 0 GR734b: (RX touching OP) to BP space >= 0.220 um.
11957 0 GR736a: RX(touching OP) touching PC found!
11959 0 GR736a1: (RX(touching OP) not touching PC) touching SBLK found!
11962 0 GR736a2: ((PC touching OP) not over (ESDUMMY or ESD_CDM)) touching SBLK found!
11971 0 GR736a3: SBLK must touch OP
11973 0 GR739a: RX overlap past OP >= 0.620 um.
11975 0 GR739b: PC overlap past OP >= 0.580 um.
11976 0 GROP20: OP to adjacent RN >= 0.600 um.
11978 0 GROP24: OP touching RX(over RN) found!
11980 0 GROP30: ((PC over OP) over NW) to RX space >= 0.380 um.
11981 0 GROP31: (PC touching OP) to RN must be>= 0.3um !
11992 0 GROP31: (PC touching OP) cannot touch RN !
11998 0 GROP32: ((RX over OP) not over GRLOGIC) to (NR or PR or PE or NE) space >= 0.260 um.
11999 0 GROP32: ((RX over OP) not over GRLOGIC) touching (NR or PR or PE or NE) found!
12007 0 GRPBR35: PC(touching OP, not touching BB) to adjacent BB >= 2.000 um.
12013 0 GRSBLK3: (OP over RX) over PC) must be within (TG over (SBLK over (DN over (ESDUMMY or ESD_CDM)))) >= 0.000 um.
12016 0 GRSBLK2: (PC over RX) over OP) not within OP found.
12018 0 GRSBLK2: (PC over RX) over OP) must be within OP >= 0.180 um.
12020 0 GRSBLK4: SBLK must covered by (ESDUMMy or ESD_CDM).
12021 0 GRRR1: RR width >= 0.800 um.
12023 0 GRRR2: RR space >= 0.800 um.
12025 0 GRRR2: RR notch >= 0.800 um.
12026 0 GRRR3: RR touching RP found!
12027 0 GRRR3: RR to RP space >= 0.800 um.
12028 0 GRRR4: PC straddling RR found!
12030 0 GRRR4: PC within RR >= 0.260 um.
12031 0 GRRR5: RR to adjacent PC >= 0.280 um.
12032 0 GRRR6: RR to (PC over RX) space >= 0.500 um.
12033 0 GRRR7: RR touching RX found!
12034 0 GRRR7: RR to adjacent RX >= 0.280 um.
12036 0 GRRR8: BP within RR >= 0.000 um.
12038 0 GRRR9: BP(touching RR) touching BB found!
12040 0 GRRR9: BP(touching RR) touching PC(not touching RR) found!
12042 0 GRRR10: PC(not touching OP) touching RR found!
12044 0 GRRR11: (CA/CABAR over RR) not covered by PD found!
12045 0 GRRP1: RP width >= 0.800 um.
12047 0 GRRP2: RP space >= 0.800 um.
12049 0 GRRP2: RP notch >= 0.800 um.
12050 0 GRRP4: PC straddling RP found!
12052 0 GRRP4: PC within RP >= 0.260 um.
12053 0 GRRP5: RP to adjacent PC >= 0.280 um.
12054 0 GRRP6: RP to (PC over RX) space >= 0.500 um.
12055 0 GRRP7: RP touching RX found!
12056 0 GRRP7: RP to adjacent RX >= 0.280 um.
12058 0 GRRP8: BP within RP >= 0.000 um.
12060 0 GRRP9: BP(touching RP) touching BB found!
12062 0 GRRP9: BP(touching RP) touching PC(not touching RP) found!
12064 0 GRRP10: PC(not touching OP) touching RP found!
12066 0 GRRP11: (CA/CABAR over RP) not covered by PD found!
12067 0 GRKX1: K1 width (min) >= 5.000 um.
12068 0 GRKX2: V1 straddling K1 found!
12070 0 GRKX2: V1 within K1 >= 0.5000 um.
12072 0 GRKX3: K1 space >= 5.500 um.
12073 0 GRKX4: K1 touching M1 found!
12074 0 GRKX4: K1 to M1 space >= 1.000 um.
12085 0 GRKX5: More than ONE set of contacts found on a K1 resistor!
12111 0 GRKX6: K1 width (max) <= 30.000 um.
12113 0 GRKX8: Non-rectangular K1 found!
12114 0 GRKX8: 45 degree K1 found!
12125 0 GRKX9: V1(touching K1) space == 0.28 um. (error >)
12133 0 GRKX10: K1/M2 intersection only enclosing one V1 shape found!
12135 0 GRKX10: K1/MT intersection only enclosing one V1 shape found!
12136 0 GRKX11: K1 touching OP found!
12137 0 GRPD1: PD width >= 0.340 um.
12139 0 GRPD2a: PD space >= 0.340 um.
12141 0 GRPD2a: PD notch >= 0.340 um.
12143 0 GRPD3: PDHOLE width (for SBD anode) >= 0.700 um.
12145 0 GRPD3a: PDHOLE length (for SBD anode) >= 2.00 um.
12152 0 GRPD4: PD to adj RX >= 0.360 um.
12154 0 GRPD5: RX intersect PD (SBD guardring) >= 0.320 um.
12163 0 GRPD6: RX(not over ((SBD sized by 0.6) or BP2ND)) straddling PD found!
12166 0 GRPD6: RX(not over ((SBD sized by 0.6) or BP2ND)) within PD >= 0.200 um.
12168 0 GRPD6a: PD overlap past RX(SBD guardring) >= 0.360 um.
12170 0 GRPD7: PD overlap past PC >= 0.280 um.
12171 0 GRPD9b: Non-orthogonal PD shape found!
12172 0 GRPD10a: PD to adjacent PC >= 0.280 um.
12173 0 GRPD11: PD enclosed area >= 0.320 sq.um.
12179 0 GRPD14: CA(not over RN) not within PD(SBD) found!
12181 0 GRPD14: CA(not over RN) must be within PD(SBD) >= 0.280 um.
12183 0 GRPD15: (RX touching PD(touching SBD)) touching BP(drawn) found!
12186 0 GRPD16: PD(touching SBD) touching {PC or (RX not touching PD)} found!
12188 0 GRSBD1: SBD within DN >= 5.000 um.
12189 0 GRRN1: RN width >= 0.800 um.
12191 0 GRRN2: RN space >= 1.280 um.
12193 0 GRRN2: RN notch >= 1.280 um.
12194 0 GRRN3: RN to adjacent RX >= 0.420 um.
12195 0 GRRN4: RX straddling RN found!
12197 0 GRRN4: RX within RN >= 0.140 um.
12207 0 GRRN5a: (RX within RN) touching BP found!
12216 0 GRRN6: RN touching a P+ Junction found!
12217 0 GRRN7: RN touching a Substrate Contact found!
12218 0 GRRN10: (RN over RX) touching PD found!
12225 0 GRRN11: RN must be covered by (SBD sized by 2.14um)!
12226 0 GRRN12: RN to NW space >= 1.280 um.
12228 0 GRRN13: (RN union NW) width >= 0.700 um.
12237 0 GRNS15a: More than one union {RX, RN, (SBD sized by 1.26um)} shape in the same BB found!
12242 0 GRBB1: (BB not abutting NW)) width >= 2.760 um.
12251 0 GRBB1a: ((BB not over DN) abutting NW)) width == 1.000 um.(error >)
12252 0 GRBB1a: ((BB not over DN) abutting NW)) width == 1.000 um.(error <)
12272 0 GRBB1b: ((BB over DN) abutting NW)) must abut NW on all sides except those edges which abut BP2ND.
12275 0 GRBB1c: ((BB over DN) abbuting BP2ND width == 1.00 um.(error (<)
12276 0 GRBB1c: ((BB over DN) abbuting BP2ND width == 1.00 um.(error (>)
12278 0 GRBB2: BB space >= 2.00 um.
12280 0 GRBB2: BB notch >= 2.00 um.
12281 0 GRBB6: BB area >= 9.600 sq.um.
12285 0 GRBB7: BB enclosed area >= 4.000 sq.um.
12286 0 GRBB34: BB over NW found!
12291 0 GRBB34a: ( BB not over DN ) touching more than one (union(NW, RN)) shapes not allowed !
12292 0 GRBB35a: BB touching BP found!
12293 0 GRBB35: BB to adjacent BP >= 0.440 um.
12325 0 GRBB37: PD not within {[(BP or BB) over (PC(res)+ 0.40)] or (SBD sizd by 1.04) or (VNCAP_PC expanded by 1.00) or (BP2ND)} found!
12330 0 GRBB38: ((RX touching BB) not over IND_FILT) must be touching {RN, SBD, BP2ND}!
12331 0 GRBB41: PC straddling BB found!
12333 0 GRBB41: PC within BB >= 0.500 um.
12344 0 GRBB42: DN cannot touch (PD not over (BP2ND or (SBD sized 1.04) or RR or RP))
12349 0 GRPBN10: PC(touching PD) not within {BP or BB} found!
12350 0 GRPBN10: PC(touching RR) not within {BP or BB} found!
12351 0 GRPBN10: PC(touching RP) not within {BP or BB} found!
12353 0 GRPBN10: PC(touch PD) must be within {BP or BB} >= 0.400 um.
12355 0 GRPBN10: PC(touch RR) must be within {BP or BB} >= 0.400 um.
12357 0 GRPBN10: PC(touch RP) must be within {BP or BB} >= 0.400 um.
12362 0 GRPBN11: (PC(touching CA/CABAR) intersect BB) not within {PD/RR/RP} found!
12363 0 GRPBN12: PC to adjacent BB space >= 0.320 um.
12364 0 GR790: BFMOAT width >= 10.000 um.
12365 0 GR792: BB to adjacent BFMOAT space >= 10.000 um.
12367 0 GR792: BFMOAT space >= 10.000 um.
12369 0 GR792: BFMOAT notch >= 10.000 um.
12370 0 GR793: BFMOAT to adjacent NW space >= 2.000 um.
12371 0 GR795: BFMOAT to adjacent RX space >= 1.000 um.
12372 0 GR799: BB touching BFMOAT found!
12373 0 GR799: NW touching BFMOAT found!
12374 0 GR799: PC touching BFMOAT found!
12375 0 GR799: RX touching BFMOAT found!
12377 0 GR799: NR touching BFMOAT found!
12378 0 GR799: PR touching BFMOAT found!
12889 0 GR500b: M1 width (max) <= 35.000 um.
12890 0 GR500: M1 width (min) >= 0.240 um.
12894 0 GR501a: M1 area >= 0.172 sq.um.
12895 0 GR501b: M1 enclosed area >= 0.705 sq. um.
12897 0 GR502: M1 space >= 0.200 um.
12899 0 GR502: M1 notch >= 0.200 um.
13079 0 GR504:  M1(>1.48) to M1 (run >0) space >= 0.32 um.
13080 0 GR504b: M1(>4.00) to M1 (run >0) space >= 0.60 um.
13089 0 GR504a: M1(>1.60) to M1 (run >0) space >= 0.36 um.
13090 0 GR505a: CA not within M1 found!
13091 0 GR505b: CABAR not within M1 found!
13093 0 GR505a: CA must be within M1 >= 0.020 um.
13095 0 GR505b: CABAR must be within M1 >= 0.040 um.
13096 0 GR550: V1 width and length == 0.280 um. (error <)
13097 0 GR550: V2 width and length == 0.280 um. (error <)
13098 0 GR550: V3 width and length == 0.280 um. (error <)
13099 0 GR550: V4 width and length == 0.280 um. (error <)
13100 0 GR550: V5 width and length == 0.280 um. (error <)
13101 0 GR550: V1 width and length == 0.280 um. (error >)
13102 0 GR550: V2 width and length == 0.280 um. (error >)
13103 0 GR550: V3 width and length == 0.280 um. (error >)
13104 0 GR550: V4 width and length == 0.280 um. (error >)
13105 0 GR550: V5 width and length == 0.280 um. (error >)
13107 0 GR553a: V1 to V1 space >= 0.280 um.
13109 0 GR553a: V2 to V2 space >= 0.280 um.
13111 0 GR553a: V3 to V3 space >= 0.280 um.
13113 0 GR553a: V4 to V4 space >= 0.280 um.
13115 0 GR553a: V5 to V5 space >= 0.280 um.
13117 0 GR557: Non-rectangular V1 found!
13119 0 GR557: Non-rectangular V2 found!
13121 0 GR557: Non-rectangular V3 found!
13123 0 GR557: Non-rectangular V4 found!
13125 0 GR557: Non-rectangular V5 found!
13126 0 GR557: 45 degree V1 found!
13127 0 GR557: 45 degree V2 found!
13128 0 GR557: 45 degree V3 found!
13129 0 GR557: 45 degree V4 found!
13130 0 GR557: 45 degree V5 found!
13131 0 GR558: V1BAR outside of Chipring found!
13132 0 GR558: V2BAR outside of Chipring found!
13133 0 GR558: V3BAR outside of Chipring found!
13134 0 GR558: V4BAR outside of Chipring found!
13135 0 GR558: V5BAR outside of Chipring found!
13136 0 GR566: V1 overlapping V1BAR found!
13137 0 GR566: V2 overlapping V2BAR found!
13138 0 GR566: V3 overlapping V3BAR found!
13139 0 GR566: V4 overlapping V4BAR found!
13140 0 GR566: V5 overlapping V5BAR found!
13141 0 GR566: V1BAR to V1 space >= 0.560 um.
13142 0 GR566: V2BAR to V2 space >= 0.560 um.
13143 0 GR566: V3BAR to V3 space >= 0.560 um.
13144 0 GR566: V4BAR to V4 space >= 0.560 um.
13145 0 GR566: V5BAR to V5 space >= 0.560 um.
13153 0 GR570: V1(not over K1) must be within M1 >= -0.020 um.
13155 0 GR575a: V1 not within M2 found!
13157 0 GR575a1: V1 not within MT found!
13158 0 GR600: M2 width (min) >= 0.280 um.
13159 0 GR600: M3 width (min) >= 0.280 um.
13160 0 GR600: M4 width (min) >= 0.280 um.
13161 0 GR600: M5 width (min) >= 0.280 um.
13174 0 GR601a: M2 area > 0.3136 sq.um.
13175 0 GR601a: M3 area > 0.3136 sq.um.
13176 0 GR601a: M4 area > 0.3136 sq.um.
13177 0 GR601a: M5 area > 0.3136 sq.um.
13178 0 GR601b: M2 enclosed area >= 0.705 sq.um.
13179 0 GR601b: M3 enclosed area >= 0.705 sq.um.
13180 0 GR601b: M4 enclosed area >= 0.705 sq.um.
13181 0 GR601b: M5 enclosed area >= 0.705 sq.um.
13183 0 GR602: M2 space >= 0.280 um.
13185 0 GR602: M2 notch >= 0.280 um.
13187 0 GR602: M3 space >= 0.280 um.
13189 0 GR602: M3 notch >= 0.280 um.
13191 0 GR602: M4 space >= 0.280 um.
13193 0 GR602: M4 notch >= 0.280 um.
13195 0 GR602: M5 space >= 0.280 um.
13197 0 GR602: M5 notch >= 0.280 um.
13201 0 GR604:   M2(>1.60) to M2(>1.60) space >= 0.40 um.
13206 0 GR604a:  M2(>5.00) to M2 space  >= 0.60 um.
13210 0 GR604:   M3(>1.60) to M3(>1.60) space >= 0.40 um.
13215 0 GR604a:  M3(>5.00) to M3 space  >= 0.60 um.
13219 0 GR604:   M4(>1.60) to M4(>1.60) space >= 0.40 um.
13224 0 GR604a:  M4(>5.00) to M4 space  >= 0.60 um.
13228 0 GR604:   M5(>1.60) to M5(>1.60) space >= 0.40 um.
13233 0 GR604a:  M5(>5.00) to M5 space  >= 0.60 um.
13234 0 GR610: V2 not within M2 found!
13235 0 GR610: V3 not within M3 found!
13236 0 GR610: V4 not within M4 found!
13237 0 GR610: V5 not within M5 found!
13239 0 GR611: V2 not within M3 found!
13241 0 GR611: V2 not within MT found!
13243 0 GR611: V3 not within M4 found!
13245 0 GR611: V3 not within MT found!
13247 0 GR611: V4 not within M5 found!
13249 0 GR611: V4 not within MT found!
13251 0 GR611: V5 not within MT found!
13280 0 GR612: M1/M2 intersection only enclosing one V1 shape found!
13281 0 GR612: M1/MT intersection only enclosing one V1 shape found!
13282 0 GR640: MT width >= 0.280 um.
13286 0 GR641a: MT area > 0.548 sq.um.
13287 0 GR641b: MT enclosed area >= 0.705 sq.um.
13289 0 GR642: MT space >= 0.280 um.
13291 0 GR642: MT notch >= 0.280 um.
13292 0 GR644:  MT(>1.60) to MT space >= 0.40 um.
13293 0 GR644a: MT(>5.00) to MT space >= 0.60 um.
13294 0 GR644b: MT(>35.0) to MT space >= 2.00 um.
13301 0 GR650a: LV width >= 14.000 um.
13302 0 GR650b: DV width >= 14.000 um.
13303 0 GR651a: LV area >= 550.000 sq.um.
13304 0 GR651b: DV area >= 480.000 sq.um.
13306 0 GR653b: DV space >= 11.000 um.
13308 0 GR653b: DV notch >= 11.000 um.
13310 0 GR653c: LV space >= 29.000 um.
13312 0 GR653c: LV notch >= 29.000 um.
13314 0 GR658c: DV within CHIPEDGE >= 20.000 um.
13316 0 GR658d: LV within CHIPEDGE >= 29.000 um.
13317 0 ERROR: C4LV SHAPES FOUND! - PLEASE PICK A C4 SWITCH AND RERUN THE DRC CHECK
13322 0 GRBEOL1: C4LV touching DV found!
13323 0 GRBEOL1: LV touching DV found!
13325 0 GRA500b: M1(over M1CHEXCL) width (max) <= 14.000 um.
13330 0 GRA504a: M1(over M1CHEXCL) space (if one line > 2.40 wide) >= 0.700 um.
13331 0 GRA504b: M1(over M1CHEXCL) space (if one line > 5.30 wide) >= 1.600 um.
13332 0 GRA504c: M1(over M1CHEXCL) space (if one line > 8.40 wide) >= 2.500 um.
13333 0 GRA504d: M1(over M1CHEXCL) space (if one line >11.50 wide) >= 3.500 um.
13335 0 GRA504a: M1(over M1CHEXCL) notch (if one line > 2.40 wide) >= 0.700 um.
13337 0 GRA504b: M1(over M1CHEXCL) notch (if one line > 5.30 wide) >= 1.600 um.
13339 0 GRA504c: M1(over M1CHEXCL) notch (if one line > 8.40 wide) >= 2.500 um.
13341 0 GRA504d: M1(over M1CHEXCL) notch (if one line >11.50 wide) >= 3.500 um.
13342 0 GRMOSVAR1: MOSVAR width >= 0.440 um.
13344 0 GRMOSVAR2: MOSVAR space >= 0.440 um.
13346 0 GRMOSVAR2: MOSVAR notch >= 0.440 um.
13355 0 GRMOSVAR3: MOSVAR touching RP found!
13356 0 GRMOSVAR3: MOSVAR touching RR found!
13359 0 GRMOSVAR3a: (MOSVAR over NW) touching BP found!
13360 0 GRMOSVAR4: MOSVAR to BB space >= 0.440 um.
13361 0 GRMOSVAR4: MOSVAR to NW space >= 0.440 um.
13362 0 GRMOSVAR5: MOSVAR to RX space >= 0.340 um.
13363 0 GRMOSVAR5a: MOSVAR to (PC over RX) space >= 0.500 um.
13367 0 GRMOSVAR6: (RX touch MOSVAR) not within ((DN or NW )over MOSVAR) found!
13369 0 GRMOSVAR6: (RX touch MOSVAR) must be within (( DN or NW ) over MOSVAR) >= 0.420 um.
13373 0 GRPCAP1: ((PC over RX) touching MOSVAR) must be within BP >= 0.360 um.
13375 0 GRPCAP1: ((PC over RX) touching MOSVAR) within BP >= 0.360 um.
13376 0 GRFT1: FT width == 1.24 um.(error <)
13377 0 GRFT1: FT width == 1.24 um.(error >)
13379 0 GRFT2: FT space >= 2.000 um.
13390 0 GRFT3: FTBAR(outside IND_FLT) width == 1.24 um.(error >)
13399 0 GRFT3: FTBAR(over IND_FLT) width == 1.24 um.(error >)
13400 0 GRFT3: FTBAR(outside IND_FLT) width == 1.24 um.(error <)
13401 0 GRFT3: FTBAR(over IND_FLT) width == 1.24 um.(error <)
13402 0 GRFT4: FTBAR length (min) <= 1.260 um.
13403 0 GRFT5: FTBAR length (max) <= 20.000 um.
13404 0 GRFT6: FT touching FTBAR found!
13405 0 GRFT6: FT to FTBAR space >= 2.000 um.
13407 0 GRFT7: FTBAR space (run length <= 5.0) >= 2.000 um.
13409 0 GRFT8: FTBAR space (run length > 5.0) >= 4.000 um.
13410 0 GRFT9: FT not within MT found!
13412 0 GRFT9: FT must be within MT >= 1.000 um.
13413 0 GRFT10: FTBAR not within MT found!
13415 0 GRFT10: FTBAR must be within MT >= 1.000 um.
13420 0 GRFT11: Non-retangular FT/FTBAR found!
13421 0 GRFT12: 45 degree FT found!
13422 0 GRFT12: 45 degree FTBAR found!
13425 0 GRAM1: AM width >= 2.000 um.
13426 0 GRAM1a: AM area >= 10.000 sq.um.
13438 0 GRAM2: AM to AM space >= 2.800 um.
13440 0 GRAM2: AM to AM notch >= 2.800 um.
13474 0 GRAM2a: AM space for AM edges over the same (({FT,FTBAR} not over {LOWCRNT, IND_FILT}) sized by 8.0 um.) >= 5.000 um.
13498 0 GRAM2aa: AM space for AM edges over the same ((({FT,FTBAR} over IND_FILT) not over LOWCRNT) sized by 6.00 um.) >= 5.00 um.
13516 0 GRAM2b: (AM not over IND_FILT)(>10.00) to AM space >= 4.00 um.
13519 0 GRAM2ba: AM over (IND_FILT +25.0)(>10.00) to AM space >= 3.00 um.
13522 0 GRAM2b2: AM over (IND_FILT +50.0)(>25.00) to AM space >= 4.00 um.
13525 0 GRAM2c:  AM(>50.00) to AM space >= 5.00 um.
13529 0 GRAM3: FT not within AM found!
13531 0 GRAM3: FTBAR not within AM found!
13533 0 GRAM3: FT must be within AM >= 1.000 um.
13535 0 GRAM3: FTBAR must be within AM >= 1.000 um.
13538 0 GRAM4: DV(within CHIPEDGE) not within AM found!
13541 0 GRAM4: LV(within CHIPEDGE) not within AM found!
13550 0 GRQCAP1d: QT width (max) <= 1,000.0 um.
13559 0 GRQCAP1d: HT width (max) <= 1,000.0 um.
13560 0 GRQCAP1 : QT width >= 4.000 um.
13561 0 GRQCAP1a: HT width >= 4.000 um.
13562 0 GRQCAP1b: QT area (max per shape) <= 100,000.0 sq.um.
13563 0 GRQCAP1b: HT area (max per shape) <= 100,000.0 sq.um.
13565 0 GRQCAP2a: Non-rectangular QT shapes found!
13567 0 GRQCAP2a: Non-rectangular HT shapes found!
13570 0 GRQCAP2b: QT MIM aspect ratio > 3.0 found!
13573 0 GRQCAP2b: HT MIM aspect ratio > 3.0 found!
13575 0 GRQCAP2: QT space >= 2.200 um.
13577 0 GRQCAP2a1: HT space >= 3.600 um.
13578 0 GRQCAP3: QT not within MT found!
13579 0 GRQCAP3a: HT not within QT found!
13581 0 GRQCAP3: QT must be within MT >= 0.700 um.
13583 0 GRQCAP3a: HT must be within QT >= 0.700 um.
13593 0 GRQCAP4: QT(touching HT) not touching FT(outside of HT) found!
13594 0 GRQCAP4: FT straddling QT found!
13595 0 GRQCAP4b: FT straddling HT found!
13600 0 GRQCAP4a: (MT touching QT) touching V1 found!
13605 0 GRQCAP4a: (MT touching QT) touching V2 found!
13610 0 GRQCAP4a: (MT touching QT) touching V3 found!
13615 0 GRQCAP4a: (MT touching QT) touching V4 found!
13620 0 GRQCAP4a: (MT touching QT) touching V5 found!
13622 0 GRQCAP4: FT within QT >= 1.200 um.
13624 0 GRQCAP4b: FT within HT >= 1.200 um.
13625 0 GRQCAP4c: FT to HT space >= 1.000 um.
13626 0 GRQCAP5: FT to adjacent QT >= 1.000 um.
13627 0 GRQCAP5: FTBAR to adjacent QT >= 1.000 um.
13628 0 GRQCAP6: FTBAR touching QT found!
13632 0 GRQCAP8b: QT straddling BB(not touching (PC or DI)) found!
13633 0 GRQCAP8b: QT straddling NW(not touching (PC or DI)) found!
13635 0 GRQCAP8b: QT within BB(not touching (PC or DI )) >= 4.000 um.
13637 0 GRQCAP8b: QT within NW(not touching (PC or DI )) >= 4.000 um.
13645 0 GRQCAP10: (MT touching QT) to MT space >= 0.800!
13648 0 GRQCAP12b: QT(covered by NW) within NW >= 4.000 um.
13654 0 GRQCAP16b: NW to adjacent QT(not touching {NW,PC,RX}) >= 4.600 um.
13655 0 GRQCAP23a : (Ratio of (FT over (QT touching MIMHD)) area to QT area) > 10.0% found !
13656 0 GRQCAP23b : (Ratio of (FT over HT) area to HT area) > 10.0% found !
13667 0 GRQCAP30: QT shapes must be covered by MIM_HD (if at least one QT touch MIM_HD).
13676 0 GRQCAP30a: (MIM_HD not covering QT) found!
13678 0 GRQCAP30a: (MIM_HD partly covering QT) found!
13679 0 GRIND11: Invalid layer under IND_FLT found! (BN)
13680 0 GRIND11: Invalid layer under IND_FLT found! (BP)
13681 0 GRIND11: Invalid layer under IND_FLT found! (CABAR)
13682 0 GRIND11: Invalid layer under IND_FLT found! (LV)
13683 0 GRIND11: Invalid layer under IND_FLT found! (LVDUMMY)
13687 0 GRIND11: M1 straddling IND_FLT found!
13690 0 GRIND11: Invalid layer under IND_FLT found! (M2)
13693 0 GRIND11: Invalid layer under IND_FLT found! (M3)
13696 0 GRIND11: Invalid layer under IND_FLT found! (M4)
13699 0 GRIND11: Invalid layer under IND_FLT found! (M5)
13700 0 GRIND11: Invalid layer under IND_FLT found! (NS)
13701 0 GRIND11: Invalid layer under IND_FLT found! (NW)
13702 0 GRIND11: Invalid layer under IND_FLT found! (OP)
13703 0 GRIND11: Invalid layer under IND_FLT found! (QT)
13704 0 GRIND11: Invalid layer under IND_FLT found! (RN)
13707 0 GRIND11: Invalid layer under IND_FLT found! (RX)
13708 0 GRIND11: RX straddling IND_FLT found!
13716 0 GRIND11: Invalid layer under IND_FLT found! (MT)
13717 0 GRIND12: DN to IND_FILT space >= 25.00 um.
13719 0 GRIND12a: IND_FILT within DN >= 25.00 um.
13721 0 GRIND13: AM(over IND_FLT) not covered by BB found!
13722 0 GRIND16: (BB touch IND_FLT) touching BP found!
13724 0 GRIND16: (BB touch IND_FLT) touching (PC not touching IND_FLT) found!
13726 0 GRIND16: (BB touch IND_FLT) touching (RX not touching IND_FLT) found!
13728 0 GRIND23 :SHORTED INDUCTOR COILS FOUND!
13743 0 GRIND23b :M3 over IND_FILT must match exactly M3_COIL!
13746 0 GRIND23b :M4 over IND_FILT must match exactly M4_COIL!
13749 0 GRIND23b :M5 over IND_FILT must match exactly M5_COIL!
13752 0 GRIND23b :MT over IND_FILT must match exactly MT_COIL!
13767 0 GRTL1b: (AM over TLINE) width (max) <= 25.00 um.
13787 0 GRTL2a: TLINE overlap past AM >= 20.00 um.
13789 0 GRTL2b: AM overlap past TLINE >= 1.00 um
13798 0 GRTL3b: (AM over TLINE) length (min) >= 100.00 um.
13805 0 GRTL3a: (AM over TLINE) area (min) >= 400.00 sq.um.
13809 0 GRTL4b: (AM over TLINE) length (max) >= 1500.00 um.
13813 0 GRTL4b: (MA over TLINE) length (max) >= 1500.00 um.
13817 0 GRTL4b: (ML over TLINE) length (max) >= 1500.00 um.
13818 0 GRTL4a: (AM over TLINE) area (max) >= 37,500.00 sq.um.
13819 0 GRTL4a: (MA over TLINE) area (max) >= 37,500.00 sq.um.
13820 0 GRTL4a: (ML over TLINE) area (max) >= 37,500.00 sq.um.
13821 0 GRTL5: (AM over TLINE) not within BB found!
13825 0 GRTL5: (AM over TLINE) must be within BB >= 4.00 um.
13826 0 GRTL6a: Invalid layer under TLINE found! (M1)
13827 0 GRTL6a: Invalid layer under TLINE found! (M2)
13828 0 GRTL6a: Invalid layer under TLINE found! (M3)
13829 0 GRTL6a: Invalid layer under TLINE found! (M4)
13830 0 GRTL6a: Invalid layer under TLINE found! (M5)
13831 0 GRTL6a: Invalid layer under TLINE found! (MT)
13832 0 GRTL6a: Invalid layer under TLINE found! (NS)
13833 0 GRTL6a: Invalid layer under TLINE found! (NW)
13834 0 GRTL6a: Invalid layer under TLINE found! (DN)
13835 0 GRTL6a: Invalid layer under TLINE found! (PC)
13837 0 GRTL6a: Invalid layer under TLINE found! (RX)
13839 0 GRTL6b: (AM over TLINE) space >= 40.00 um.
13841 0 GRTL9: Non-rectangular (AM over TLINE) found!
13847 0 GRTL10: TLINE touching (LV,DV) found!
13853 0 GRTL10: TLINE to (LV,DV) space >= 4.00 um.
13855 0 GRTL11: TLINE within DN >= 25.00 um.
13856 0 GRTL12: TLINE to DN space >= 25.00 um.
13865 0 GR780: PCING width == 0.160 um.(error > )
13866 0 GR780: PCING width == 0.160 um.(error < )
13868 0 GR781b: The character sequence 'IPCI' is prohibited in all data cells in the design except those defined by Rules GR780, GR782 and GR783.
13870 0 GR782: PCING to PCING space >= 0.420 um.
13871 0 GR782: PCING to PC    space >= 0.420 um.
13872 0 GR782: PCING to RX    space >= 0.420 um.
13873 0 GR782: PCING to CA    space >= 0.420 um.
13874 0 GR782: PCING to CABAR space >= 0.420 um.
13875 0 GR782: PCING to BONDPAD space >= 0.420 um.
13879 0 GR782: PCING touching (PC, RX, or CA/CABAR) shapes found
13880 0 GR783: PCING arm length (from corner to end) >= 2.000 um.
13891 0 GR784: At least 40 PCIs are required to be uniformly distributed over the chip active area if the CHIPEDGE size is larger than 6mm on any side.
13900 0 GREF01: PCFUSE width == 0.18 um.(error >)
13901 0 GREF01: PCFUSE width == 0.18 um.(error <)
13902 0 GREF02: PCFUSE length == 1.20 um.(error <)
13903 0 GREF02: PCFUSE length == 1.20 um.(error >)
13906 0 GREF03: Non-rectangular PCFUSE found!
13908 0 GREF03a: Non-rectangular (PC touching PCFUSE) found!
13909 0 GREF03: 45 degree PCFUSE found
13910 0 GREF03a: 45 degree (PC touching PCFUSE) found
13912 0 GREF04: PCFUSE space >= 2.50 um.
13913 0 GREF05: PCFUSE over BB found!
13914 0 GREF05: PCFUSE over BFMOAT found!
13915 0 GREF05: PCFUSE over CA found!
13917 0 GREF05: PCFUSE over K1 found!
13918 0 GREF05: PCFUSE over M1 found!
13919 0 GREF05: PCFUSE over M2 found!
13921 0 GREF05: PCFUSE over MT found!
13929 0 GREF05: PCFUSE over (DN sized by 5.5um) found!
13930 0 GREF05: PCFUSE over NW found!
13931 0 GREF05: PCFUSE over OP found!
13932 0 GREF05: PCFUSE over PC found!
13934 0 GREF05: PCFUSE over QT found!
13935 0 GREF05: PCFUSE over RP found!
13936 0 GREF05: PCFUSE over RR found!
13937 0 GREF05: PCFUSE over RX found!
13938 0 GREF05: PCFUSE over VNCAP_M1 found!
13939 0 GREF05: PCFUSE over VNCAP_M2 found!
13940 0 GREF05: PCFUSE over VNCAP_M3 found!
13941 0 GREF05: PCFUSE over VNCAP_M4 found!
13942 0 GREF05: PCFUSE over VNCAP_M5 found!
13943 0 GREF05: PCFUSE over VNCAP_MT found!
13946 0 GREF06: PCFUSE to BB space >= 2.50 um.
13947 0 GREF06: PCFUSE to BFMOAT space >= 2.50 um.
13948 0 GREF06: PCFUSE to K1 space >= 2.50 um.
13949 0 GREF06: PCFUSE to M2 space >= 2.50 um.
13950 0 GREF06: PCFUSE to MT space >= 2.50 um.
13951 0 GREF06: PCFUSE to NW space >= 2.50 um.
13952 0 GREF06: PCFUSE to OP space >= 2.50 um.
13953 0 GREF06: PCFUSE to QT space >= 2.50 um.
13954 0 GREF06: PCFUSE to RP space >= 2.50 um.
13955 0 GREF06: PCFUSE to RR space >= 2.50 um.
13956 0 GREF06: PCFUSE to RX space >= 2.50 um.
13957 0 GREF06: PCFUSE to V1 space >= 2.50 um.
13958 0 GREF06: PCFUSE to VNCAP_M1 space >= 2.50 um.
13959 0 GREF06: PCFUSE to VNCAP_M2 space >= 2.50 um.
13960 0 GREF06: PCFUSE to VNCAP_M3 space >= 2.50 um.
13961 0 GREF06: PCFUSE to VNCAP_M4 space >= 2.50 um.
13962 0 GREF06: PCFUSE to VNCAP_M5 space >= 2.50 um.
13963 0 GREF06: PCFUSE to VNCAP_MT space >= 2.50 um.
13964 0 GREF07a: PCFUSE not within BP found!
13965 0 GREF07b: (PC touching PCFUSE) not within BP found!
13967 0 GREF07a: PCFUSE must be within BP >= 0.30 um.
13969 0 GREF07b: (PC touching PCFUSE) must be within BP >= 0.30 um.
13976 0 GREF08a: PCFUSE abutting more than 1 anode found!
13977 0 GREF08a: PCFUSE abutting more than 1 cathode found!
13979 0 GREF08: PCFUSE (small end) not abutting a PC shape found!
13981 0 GREF08b: PCFUSE to (PC not touching PCFUSE) space >= 2.50 um.
13983 0 GREF09: PCFUSE to (M1 not touching (PC touch PCFUSE)) space >= 2.50 um.
13984 0 GREF10: (PC touching PCFUSE) not touching any CA's found!
13985 0 GREF10: (PC touching PCFUSE) touching less than 4 CA's found!
13986 0 GREF10: (PC touching PCFUSE) touching more than 4 CA's found!
13995 0 GREF11a: (PC touching PCFUSE) (anode) width == 1.18 um.(error >)
13996 0 GREF11a: (PC touching PCFUSE) (anode) width == 1.18 um.(error <)
13997 0 GREF11b: (PC touching PCFUSE) (anode) length == 1.74 um.(error <)
13998 0 GREF11b: (PC touching PCFUSE) (anode) length == 1.74 um.(error >)
14007 0 GREF12b: (PC touching PCFUSE) (cathode) length == 1.38 um.(error >)
14008 0 GREF12a: (PC touching PCFUSE) (cathode) width == 2.46 um.(error <)
14009 0 GREF12a: (PC touching PCFUSE) (cathode) width == 2.46 um.(error >)
14010 0 GREF12b: (PC touching PCFUSE) (cathode) length == 1.38 um.(error <)
14018 0 GREF13: (M1 touching (PC touching PCFUSE)) (anode) width <= 1.20 um.
14020 0 GREF14: (M1 touching (PC touching PCFUSE)) (cathode) width <= 2.50 um.
14021 0 GREF15: PCFUSE to (M1 touching (PC touching PCFUSE)) space >= 1.00 um.
14041 0 GREF16: PCFUSE not centered on PC anode found!
14043 0 GREF16: PCFUSE not centered on PC cathode found!
14044 0 GREF18: (BP touching PCFUSE) width >= 0.720 um.
14046 0 GREF19: (BP touching PCFUSE) touching BB found!
14047 0 GREF19: (BP touching PCFUSE) touching TG found!
14048 0 GREF19: (BP touching PCFUSE) touching SN found!
14049 0 GREF19: (BP touching PCFUSE) touching NG found!
14050 0 GREF19: (BP touching PCFUSE) touching MOSVAR found!
14051 0 GREF19: (BP touching PCFUSE) touching NW found!
14052 0 GREF19: (BP touching PCFUSE) touching (PC -RX) over OP)... found!
14054 0 GREF19: (BP touching PCFUSE) to BB space >= 0.44 um.
14055 0 GREF19: (BP touching PCFUSE) to SN space >= 0.44 um.
14056 0 GREF19: (BP touching PCFUSE) to NG space >= 0.44 um.
14057 0 GREF19: (BP touching PCFUSE) to TG space >= 0.44 um.
14058 0 GREF19: (BP touching PCFUSE) to MOSVAR space >= 0.44 um.
14059 0 GREF19: (BP touching PCFUSE) to NW space >= 0.44 um.
14060 0 GREF19: (BP touching PCFUSE) to (PC -RX) over OP)... space >= 0.44 um.
14062 0 GREF20: (BP touching PCFUSE) touching (BP touching OP) found!
14065 0 GREF20: (BP touch PCFUSE) touch (BP touch (PC no touch PCFUSE)) found!
14067 0 GREF20: (BP touching PCFUSE) touching (BP touching RX) found!
14068 0 GRVNCAP1: VNCAPM1 minimum width >= 1.00 um !
14069 0 GRVNCAP1: VNCAPM2 minimum width >= 1.00 um !
14070 0 GRVNCAP1: VNCAPM3 minimum width >= 1.00 um !
14071 0 GRVNCAP1: VNCAPM4 minimum width >= 1.00 um !
14072 0 GRVNCAP1: VNCAPM5 minimum width >= 1.00 um !
14073 0 GRVNCAP1: VNCAPMT minimum width >= 1.00 um !
14134 0 GRVNCAP3_HV: ((M1 over VNCAP_M1) not over VNCAPHV) width == 0.36 um.(error <)
14135 0 GRVNCAP3_HV: ((M2 over VNCAP_M2) not over VNCAPHV) width == 0.36 um.(error <)
14136 0 GRVNCAP3_HV: ((M3 over VNCAP_M3) not over VNCAPHV) width == 0.36 um.(error <)
14137 0 GRVNCAP3_HV: ((M4 over VNCAP_M4) not over VNCAPHV) width == 0.36 um.(error <)
14138 0 GRVNCAP3_HV: ((M5 over VNCAP_M5) not over VNCAPHV) width == 0.36 um.(error <)
14139 0 GRVNCAP3_HV: ((MT over VNCAP_MT) not over VNCAPHV) width == 0.36 um.(error <)
14140 0 GRVNCAP3_HV: ((M1 over VNCAP_M1) not over VNCAPHV) width == 0.36 um.(error >)
14141 0 GRVNCAP3_HV: ((M2 over VNCAP_M2) not over VNCAPHV) width == 0.36 um.(error >)
14142 0 GRVNCAP3_HV: ((M3 over VNCAP_M3) not over VNCAPHV) width == 0.36 um.(error >)
14143 0 GRVNCAP3_HV: ((M4 over VNCAP_M4) not over VNCAPHV) width == 0.36 um.(error >)
14144 0 GRVNCAP3_HV: ((M5 over VNCAP_M5) not over VNCAPHV) width == 0.36 um.(error >)
14145 0 GRVNCAP3_HV: ((MT over VNCAP_MT) not over VNCAPHV) width == 0.36 um.(error >)
14214 0 GRVNCAP3a: (M1 over VNCAPM1) width == 1.0 um.(error >)
14223 0 GRVNCAP3a: (M2 over VNCAPM2) width == 1.0 um.(error >)
14232 0 GRVNCAP3a: (M3 over VNCAPM3) width == 1.0 um.(error >)
14241 0 GRVNCAP3a: (M4 over VNCAPM4) width == 1.0 um.(error >)
14250 0 GRVNCAP3a: (M5 over VNCAPM5) width == 1.0 um.(error >)
14259 0 GRVNCAP3a: (MT over VNCAPMT) width == 1.0 um.(error >)
14266 0 GRVNCAP3a: (M1 over VNCAP_M1) width == 1.0 um.(error <)
14267 0 GRVNCAP3a: (M2 over VNCAP_M2) width == 1.0 um.(error <)
14268 0 GRVNCAP3a: (M3 over VNCAP_M3) width == 1.0 um.(error <)
14269 0 GRVNCAP3a: (M4 over VNCAP_M4) width == 1.0 um.(error <)
14270 0 GRVNCAP3a: (M5 over VNCAP_M5) width == 1.0 um.(error <)
14271 0 GRVNCAP3a: (MT over VNCAP_MT) width == 1.0 um.(error <)
14278 0 GRVNCAP4a_HV: ((M1 over VNCAPM1) not over VNCAPHV)  space (for common run length <= 0.36) == 0.40um (error <)
14279 0 GRVNCAP4a_HV: ((M2 over VNCAPM2) not over VNCAPHV)  space (for common run length <= 0.36) == 0.40um (error <)
14280 0 GRVNCAP4a_HV: ((M3 over VNCAPM3) not over VNCAPHV)  space (for common run length <= 0.36) == 0.40um (error <)
14281 0 GRVNCAP4a_HV: ((M4 over VNCAPM4) not over VNCAPHV)  space (for common run length <= 0.36) == 0.40um (error <)
14282 0 GRVNCAP4a_HV: ((M5 over VNCAPM5) not over VNCAPHV)  space (for common run length <= 0.36) == 0.40um (error <)
14283 0 GRVNCAP4a_HV: ((MT over VNCAPMT) not over VNCAPHV)  space (for common run length <= 0.36) == 0.40um (error <)
14285 0 GRVNCAP4b_HV: ((M1 over VNCAPM1) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error <)
14287 0 GRVNCAP4b_HV: ((M2 over VNCAPM2) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error <)
14289 0 GRVNCAP4b_HV: ((M3 over VNCAPM3) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error <)
14291 0 GRVNCAP4b_HV: ((M4 over VNCAPM4) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error <)
14293 0 GRVNCAP4b_HV: ((M5 over VNCAPM5) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error <)
14295 0 GRVNCAP4b_HV: ((MT over VNCAPMT) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error <)
14304 0 GRVNCAP4a_HV: ((M1 over VNCAPM1) not over VNCAPHV) space (for common run length <= 0.36) == 0.40um (error >)
14313 0 GRVNCAP4a_HV: ((M2 over VNCAPM2) not over VNCAPHV) space (for common run length <= 0.36) == 0.40um (error >)
14322 0 GRVNCAP4a_HV: ((M3 over VNCAPM3) not over VNCAPHV) space (for common run length <= 0.36) == 0.40um (error >)
14331 0 GRVNCAP4a_HV: ((M4 over VNCAPM4) not over VNCAPHV) space (for common run length <= 0.36) == 0.40um (error >)
14340 0 GRVNCAP4a_HV: ((M5 over VNCAPM5) not over VNCAPHV) space (for common run length <= 0.36) == 0.40um (error >)
14349 0 GRVNCAP4a_HV: ((MT over VNCAPMT) not over VNCAPHV) space (for common run length <= 0.36) == 0.40um (error >)
14354 0 GRVNCAP4b_HV: ((M1 over VNCAPM1) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error >)
14359 0 GRVNCAP4b_HV: ((M2 over VNCAPM2) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error >)
14364 0 GRVNCAP4b_HV: ((M3 over VNCAPM3) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error >)
14369 0 GRVNCAP4b_HV: ((M4 over VNCAPM4) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error >)
14374 0 GRVNCAP4b_HV: ((M5 over VNCAPM5) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error >)
14379 0 GRVNCAP4b_HV: ((MT over VNCAPMT) not over VNCAPHV) space (for common run length > 0.36) == 0.32um (error >)
14381 0 GRVNCAP6a: (V1 intersect VNCAPM1) space (different-net, edge to edge) > 0.46 um.
14383 0 GRVNCAP6a: (V2 intersect VNCAPM2) space (different-net, edge to edge) > 0.46 um.
14385 0 GRVNCAP6a: (V3 intersect VNCAPM3) space (different-net, edge to edge) > 0.46 um.
14387 0 GRVNCAP6a: (V4 intersect VNCAPM4) space (different-net, edge to edge) > 0.46 um.
14389 0 GRVNCAP6a: (V5 intersect VNCAPM5) space (different-net, edge to edge) > 0.46 um.
14391 0 GRVNCAP6a: (FT intersect VNCAPMT) space (different-net, edge to edge) > 0.46 um.
14392 0 GRVNCAP8a_HV: (M1 intersect VNCAPM1) touching CA/CABAR found !
14395 0 GRVNCAP8b: ((M2 intersect VNCAPM2) not over VNCAPM1) touching V1 found !
14398 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM1) touching V1 found !
14401 0 GRVNCAP8b: ((M3 intersect VNCAPM3) not over VNCAPM2) touching V2 found !
14404 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM2) touching V2 found !
14407 0 GRVNCAP8b: ((M4 intersect VNCAPM4) not over VNCAPM3) touching V3 found !
14410 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM3) touching V3 found !
14413 0 GRVNCAP8b: ((M5 intersect VNCAPM5) not over VNCAPM4) touching V4 found !
14416 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM4) touching V4 found !
14419 0 GRVNCAP8b: ((MT intersect VNCAPMT) not over VNCAPM5) touching V5 found !
14422 0 GRVNCAP9a: ((M1 intersect VNCAPM1) not over VNCAPM2) touching V1 found !
14425 0 GRVNCAP9a: ((M1 intersect VNCAPM1) not over VNCAPMT) touching V1 found !
14428 0 GRVNCAP9a: ((M2 intersect VNCAPM2) not over VNCAPM3) touching V2 found !
14431 0 GRVNCAP9a: ((M2 intersect VNCAPM2) not over VNCAPMT) touching V2 found !
14434 0 GRVNCAP9a: ((M3 intersect VNCAPM3) not over VNCAPM4) touching V3 found !
14437 0 GRVNCAP9a: ((M3 intersect VNCAPM3) not over VNCAPMT) touching V3 found !
14440 0 GRVNCAP9a: ((M4 intersect VNCAPM4) not over VNCAPM5) touching V4 found !
14443 0 GRVNCAP9a: ((M4 intersect VNCAPM4) not over VNCAPMT) touching V4 found !
14446 0 GRVNCAP9a: ((M5 intersect VNCAPM5) not over VNCAPMT) touching V5 found !
14447 0 GRVNCAP9a: VNCAPMT touching FT not allowed !
14448 0 GRVNCAP9a: VNCAPMT touching FTBAR not allowed !
14450 0 GRVNCAP9b: ((M2 intersect VNCAPM2) touching {FT, FTBAR}) found !
14451 0 GRVNCAP9b: ((M3 intersect VNCAPM3) touching {FT, FTBAR}) found !
14452 0 GRVNCAP9b: ((M4 intersect VNCAPM4) touching {FT, FTBAR}) found !
14453 0 GRVNCAP9b: ((M5 intersect VNCAPM5) touching {FT, FTBAR}) found !
14454 0 GRVNCAP9b: ((MT intersect VNCAPMT) touching {FT, FTBAR}) found !
14455 0 GRVNCAP10: VNCAPM1 touching PCFUSE found !
14456 0 GRVNCAP10: VNCAPM2 touching PCFUSE found !
14457 0 GRVNCAP10: VNCAPM3 touching PCFUSE found !
14458 0 GRVNCAP10: VNCAPM4 touching PCFUSE found !
14459 0 GRVNCAP10: VNCAPM5 touching PCFUSE found !
14460 0 GRVNCAP10: VNCAPMT touching PCFUSE found !
14461 0 GRVNCAP10: VNCAPM1 touching K1 found !
14462 0 GRVNCAP10: VNCAPM2 touching K1 found !
14463 0 GRVNCAP10: VNCAPM3 touching K1 found !
14464 0 GRVNCAP10: VNCAPM4 touching K1 found !
14465 0 GRVNCAP10: VNCAPM5 touching K1 found !
14466 0 GRVNCAP10: VNCAPMT touching K1 found !
14467 0 GRVNCAP10: VNCAPM1 touching BONDPAD found !
14468 0 GRVNCAP10: VNCAPM2 touching BONDPAD found !
14469 0 GRVNCAP10: VNCAPM3 touching BONDPAD found !
14470 0 GRVNCAP10: VNCAPM4 touching BONDPAD found !
14471 0 GRVNCAP10: VNCAPM5 touching BONDPAD found !
14472 0 GRVNCAP10: VNCAPMT touching BONDPAD found !
14473 0 GRVNCAP10: VNCAPM1 touching LOGOBND found !
14474 0 GRVNCAP10: VNCAPM2 touching LOGOBND found !
14475 0 GRVNCAP10: VNCAPM3 touching LOGOBND found !
14476 0 GRVNCAP10: VNCAPM4 touching LOGOBND found !
14477 0 GRVNCAP10: VNCAPM5 touching LOGOBND found !
14478 0 GRVNCAP10: VNCAPMT touching LOGOBND found !
14485 0 GRVNCAP10: VNCAPM1 to adj. PCFUSE space >= 5.00 um.
14486 0 GRVNCAP10: VNCAPM2 to adj. PCFUSE space >= 5.00 um.
14487 0 GRVNCAP10: VNCAPM3 to adj. PCFUSE space >= 5.00 um.
14488 0 GRVNCAP10: VNCAPM4 to adj. PCFUSE space >= 5.00 um.
14489 0 GRVNCAP10: VNCAPM5 to adj. PCFUSE space >= 5.00 um.
14490 0 GRVNCAP10: VNCAPMT to adj. PCFUSE space >= 5.00 um.
14491 0 GRVNCAP10: VNCAPM1 to adj. K1 space >= 5.00 um.
14492 0 GRVNCAP10: VNCAPM2 to adj. K1 space >= 5.00 um.
14493 0 GRVNCAP10: VNCAPM3 to adj. K1 space >= 5.00 um.
14494 0 GRVNCAP10: VNCAPM4 to adj. K1 space >= 5.00 um.
14495 0 GRVNCAP10: VNCAPM5 to adj. K1 space >= 5.00 um.
14496 0 GRVNCAP10: VNCAPMT to adj. K1 space >= 5.00 um.
14497 0 GRVNCAP10: VNCAPM1 to adj. BONDPAD space >= 5.00 um.
14498 0 GRVNCAP10: VNCAPM2 to adj. BONDPAD space >= 5.00 um.
14499 0 GRVNCAP10: VNCAPM3 to adj. BONDPAD space >= 5.00 um.
14500 0 GRVNCAP10: VNCAPM4 to adj. BONDPAD space >= 5.00 um.
14501 0 GRVNCAP10: VNCAPM5 to adj. BONDPAD space >= 5.00 um.
14502 0 GRVNCAP10: VNCAPMT to adj. BONDPAD space >= 5.00 um.
14503 0 GRVNCAP10: VNCAPM1 to adj. LOGOBND space >= 5.00 um.
14504 0 GRVNCAP10: VNCAPM2 to adj. LOGOBND space >= 5.00 um.
14505 0 GRVNCAP10: VNCAPM3 to adj. LOGOBND space >= 5.00 um.
14506 0 GRVNCAP10: VNCAPM4 to adj. LOGOBND space >= 5.00 um.
14507 0 GRVNCAP10: VNCAPM5 to adj. LOGOBND space >= 5.00 um.
14508 0 GRVNCAP10: VNCAPMT to adj. LOGOBND space >= 5.00 um.
14510 0 GRVNCAP11b: (V2 over VNCAPM2) must be coincident with (V1 over VNCAPM1)
14512 0 GRVNCAP11b: (V3 over VNCAPM3) must be coincident with (V2 over VNCAPM2)
14514 0 GRVNCAP11b: (V4 over VNCAPM4) must be coincident with (V3 over VNCAPM3)
14516 0 GRVNCAP11b: (V5 over VNCAPM5) must be coincident with (V4 over VNCAPM4)
14564 0 GRVNCAP12: (M2 over VNCAPM2) must be coincident with (M1 over VNCAPM1)
14566 0 GRVNCAP12: (M3 over VNCAPM3) must be coincident with (M2 over VNCAPM2)
14568 0 GRVNCAP12: (M4 over VNCAPM4) must be coincident with (M3 over VNCAPM3)
14570 0 GRVNCAP12: (M5 over VNCAPM5) must be coincident with (M4 over VNCAPM4)
14572 0 GRVNCAP12: (MT over VNCAPMT) must be coincident with (M1 over VNCAPM1)
14574 0 GRVNCAP12: (MT over VNCAPMT) must be coincident with (M2 over VNCAPM2)
14576 0 GRVNCAP12: (MT over VNCAPMT) must be coincident with (M3 over VNCAPM3)
14578 0 GRVNCAP12: (MT over VNCAPMT) must be coincident with (M4 over VNCAPM4)
14580 0 GRVNCAP12: (MT over VNCAPMT) must be coincident with (M5 over VNCAPM5)
14589 0 GRVNCAP13_HV: (((NW not touching VNCAPHV) or (BB  not touching VNCAP_HV)) not touching (PC  or RX)) overlap past (M1 over VNCAPM1) >= 5.0um.
14591 0 GRVNCAP13_HV: (((NW not touching VNCAPHV) or (BB  not touching VNCAP_HV)) not touching (PC  or RX)) overlap past (M2 over VNCAPM2) >= 5.0um.
14593 0 GRVNCAP13_HV: (((NW not touching VNCAPHV) or (BB  not touching VNCAP_HV)) not touching (PC  or RX)) overlap past (M3 over VNCAPM3) >= 5.0um.
14595 0 GRVNCAP13_HV: (((NW not touching VNCAPHV) or (BB  not touching VNCAP_HV)) not touching (PC  or RX)) overlap past (M4 over VNCAPM4) >= 5.0um.
14597 0 GRVNCAP13_HV: (((NW not touching VNCAPHV) or (BB  not touching VNCAP_HV)) not touching (PC  or RX)) overlap past (M5 over VNCAPM5) >= 5.0um.
14599 0 GRVNCAP13_HV: (((NW not touching VNCAPHV) or (BB  not touching VNCAP_HV)) not touching (PC  or RX)) overlap past (MT over VNCAPMT) >= 5.0um.
14600 0 GRVNCAP15: (M1 intersect VNCAPM1) must be rectangular
14601 0 GRVNCAP15: (M2 intersect VNCAPM2) must be rectangular
14602 0 GRVNCAP15: (M3 intersect VNCAPM3) must be rectangular
14603 0 GRVNCAP15: (M4 intersect VNCAPM4) must be rectangular
14604 0 GRVNCAP15: (M5 intersect VNCAPM5) must be rectangular
14605 0 GRVNCAP15: (MT intersect VNCAPMT) must be rectangular
14613 0 GRVNCPM1: Union (VNCAP_Mx (x=1,2,3,4,5,T)) must enclose at least one VNCAP_PARM shape!
14616 0 GRVNCPM2: VNCAP_M1 must enclose one VNCAP_COUNT shape!
14618 0 GRVNCPM2: VNCAP_M1 must enclose one VNCAP_COUNT shape!
14620 0 GRVNCPM2: VNCAP_M1 must enclose one VNCAP_COUNT shape!
14622 0 GRVNCPM2: VNCAP_M1 must enclose one VNCAP_COUNT shape!
14624 0 GRVNCPM2: VNCAP_M1 must enclose one VNCAP_COUNT shape!
14626 0 GRVNCPM2: VNCAP_M1 must enclose one VNCAP_COUNT shape!
14771 0 GRVNCAPHV3: ((M2 over VNCAP_M2) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error <)
14773 0 GRVNCAPHV3: ((M3 over VNCAP_M3) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error <)
14775 0 GRVNCAPHV3: ((M4 over VNCAP_M4) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error <)
14777 0 GRVNCAPHV3: ((M5 over VNCAP_M5) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error <)
14779 0 GRVNCAPHV3: ((MT over VNCAP_MT) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error <)
14781 0 GRVNCAPHV3: ((M2 over VNCAP_M2) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error >)
14783 0 GRVNCAPHV3: ((M3 over VNCAP_M3) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error >)
14785 0 GRVNCAPHV3: ((M4 over VNCAP_M4) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error >)
14787 0 GRVNCAPHV3: ((M5 over VNCAP_M5) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error >)
14789 0 GRVNCAPHV3: ((MT over VNCAP_MT) touching VNCAPHV touching text == +50 on level VNCAPHV ) width == 0.28 um.(error >)
14791 0 GRVNCAPHV3c: ((M1 over VNCAP_M1) touching VNCAPHV touching text == +50 on level VNCAPHV) width == 0.42 um.(error <)
14793 0 GRVNCAPHV3c: ((M1 over VNCAP_M1) touching VNCAPHV touching text == +50 on level VNCAPHV) width == 0.42 um.(error >)
14807 0 GRVNCAPHV3a: ((M2 over VNCAP_M2) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error <)
14809 0 GRVNCAPHV3a: ((M3 over VNCAP_M3) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error <)
14811 0 GRVNCAPHV3a: ((M4 over VNCAP_M4) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error <)
14813 0 GRVNCAPHV3a: ((M5 over VNCAP_M5) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error <)
14815 0 GRVNCAPHV3a: ((MT over VNCAP_MT) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error <)
14817 0 GRVNCAPHV3a: ((M2 over VNCAP_M2) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error >)
14819 0 GRVNCAPHV3a: ((M3 over VNCAP_M3) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error >)
14821 0 GRVNCAPHV3a: ((M4 over VNCAP_M4) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error >)
14823 0 GRVNCAPHV3a: ((M5 over VNCAP_M5) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error >)
14825 0 GRVNCAPHV3a: ((MT over VNCAP_MT) touching VNCAPHV touching text == +120 on level VNCAPHV ) width == 0.32 um.(error >)
14827 0 GRVNCAPHV3d: ((M1 over VNCAP_M1) touching VNCAPHV touching text == +120 on level VNCAPHV) width == 0.56 um.(error <)
14829 0 GRVNCAPHV3d: ((M1 over VNCAP_M1) touching VNCAPHV touching text == +120 on level VNCAPHV) width == 0.56 um.(error >)
14956 0 GRVNCAPHV4b: ((M2 over VNCAPM2) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length > 0.28) == 0.50um (error >)
14964 0 GRVNCAPHV4b: ((M3 over VNCAPM3) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length > 0.28) == 0.50um (error >)
14972 0 GRVNCAPHV4b: ((M4 over VNCAPM4) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length > 0.28) == 0.50um (error >)
14980 0 GRVNCAPHV4b: ((M5 over VNCAPM5) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length > 0.28) == 0.50um (error >)
14988 0 GRVNCAPHV4b: ((MT over VNCAPMT) not over (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length > 0.28) == 0.50um (error >)
14998 0 GRVNCAPHV4aa: ((M1 over VNCAPM1) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.42) == 0.80um (error >)
15008 0 GRVNCAPHV4a: ((M2 over VNCAPM2) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error >)
15018 0 GRVNCAPHV4a: ((M3 over VNCAPM3) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error >)
15028 0 GRVNCAPHV4a: ((M4 over VNCAPM4) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error >)
15038 0 GRVNCAPHV4a: ((M5 over VNCAPM5) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error >)
15048 0 GRVNCAPHV4a: ((MT over VNCAPMT) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error >)
15049 0 GRVNCAPHV4a: ((M2 over VNCAPM2) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error <)
15050 0 GRVNCAPHV4a: ((M3 over VNCAPM3) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error <)
15051 0 GRVNCAPHV4a: ((M4 over VNCAPM4) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error <)
15052 0 GRVNCAPHV4a: ((M5 over VNCAPM5) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error <)
15053 0 GRVNCAPHV4a: ((MT over VNCAPMT) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.80um (error <)
15054 0 GRVNCAPHV4aa: ((M1 over VNCAPM1) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.42) == 0.80um (error <)
15064 0 GRVNCAPHV4ab: ((M1 over VNCAPM1) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.42) == 1.60um (error >)
15074 0 GRVNCAPHV4a1: ((M2 over VNCAPM2) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error >)
15084 0 GRVNCAPHV4a1: ((M3 over VNCAPM3) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error >)
15094 0 GRVNCAPHV4a1: ((M4 over VNCAPM4) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error >)
15104 0 GRVNCAPHV4a1: ((M5 over VNCAPM5) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error >)
15114 0 GRVNCAPHV4a1: ((MT over VNCAPMT) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error >)
15193 0 GRVNCAPHV4a1: ((M2 over VNCAPM2) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error <)
15194 0 GRVNCAPHV4a1: ((M3 over VNCAPM3) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error <)
15195 0 GRVNCAPHV4a1: ((M4 over VNCAPM4) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error <)
15196 0 GRVNCAPHV4a1: ((M5 over VNCAPM5) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error <)
15197 0 GRVNCAPHV4a1: ((MT over VNCAPMT) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 1.60um (error <)
15198 0 GRVNCAPHV4ab: ((M1 over VNCAPM1) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.42) == 1.60um (error <)
15200 0 GRVNCAPHV4b: ((M2 over VNCAPM2) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.50um (error <)
15202 0 GRVNCAPHV4b: ((M3 over VNCAPM3) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.50um (error <)
15204 0 GRVNCAPHV4b: ((M4 over VNCAPM4) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.50um (error <)
15206 0 GRVNCAPHV4b: ((M5 over VNCAPM5) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.50um (error <)
15208 0 GRVNCAPHV4b: ((MT over VNCAPMT) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length <= 0.28) == 0.50um (error <)
15210 0 GRVNCAPHV4b1: ((M2 over VNCAPM2) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 0.84um (error <)
15212 0 GRVNCAPHV4b1: ((M3 over VNCAPM3) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 0.84um (error <)
15214 0 GRVNCAPHV4b1: ((M4 over VNCAPM4) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 0.84um (error <)
15216 0 GRVNCAPHV4b1: ((M5 over VNCAPM5) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 0.84um (error <)
15218 0 GRVNCAPHV4b1: ((MT over VNCAPMT) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length <= 0.28) == 0.84um (error <)
15226 0 GRVNCAPHV4b1: ((M2 over VNCAPM2) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length > 0.28) == 0.84um (error >)
15234 0 GRVNCAPHV4b1: ((M3 over VNCAPM3) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length > 0.28) == 0.84um (error >)
15242 0 GRVNCAPHV4b1: ((M4 over VNCAPM4) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length > 0.28) == 0.84um (error >)
15250 0 GRVNCAPHV4b1: ((M5 over VNCAPM5) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length > 0.28) == 0.84um (error >)
15258 0 GRVNCAPHV4b1: ((MT over VNCAPMT) not over (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length > 0.28) == 0.84um (error >)
15260 0 GRVNCAPHV4c: ((M1 over VNCAPM1) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length > 0.42) == 0.36um (error <)
15261 0 GRVNCAPHV4c: ((M1 over VNCAPM1) touching (VNCAPHV touching text ==+50 on level VNCAPHV)) space (for common run length > 0.42) == 0.36um (error >)
15264 0 GRVNCAPHV4c1: ((M1 over VNCAPM1) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length > 0.42) == 0.60um (error <)
15272 0 GRVNCAPHV4c1: ((M1 over VNCAPM1) touching (VNCAPHV touching text ==+120 on level VNCAPHV)) space (for common run length > 0.42) == 0.60um (error >)
15276 0 GRVNCAPHV6: ((V1 intersect VNCAP_M1) touching VNCAPHV) within (M1 intersect VNCAP_M1) > 0.36 um.
15280 0 GRVNCAPHV6: ((V2 intersect VNCAP_M2) touching VNCAPHV) within (M2 intersect VNCAP_M2) > 0.36 um.
15284 0 GRVNCAPHV6: ((V3 intersect VNCAP_M3) touching VNCAPHV) within (M3 intersect VNCAP_M3) > 0.36 um.
15288 0 GRVNCAPHV6: ((V4 intersect VNCAP_M4) touching VNCAPHV) within (M4 intersect VNCAP_M4) > 0.36 um.
15292 0 GRVNCAPHV6: ((V5 intersect VNCAP_M5) touching VNCAPHV) within (M5 intersect VNCAP_M5) > 0.36 um.
15296 0 GRVNCAPHV6: ((FT intersect VNCAP_MT) touching VNCAPHV) within (MT intersect VNCAP_MT) > 0.36 um.
15297 0 GRVNCAPHV8b: (M1 intersect VNCAPM1)  touching CA/CABAR found !
15362 0 GRVNCAPHV12b: ((M3 over VNCAPM3) touching VNCAPHV) must be coincident with (M2 over VNCAPM2)
15363 0 GRVNCAPHV12b: ((M4 over VNCAPM4) touching VNCAPHV) must be coincident with (M3 over VNCAPM3)
15364 0 GRVNCAPHV12b: ((M5 over VNCAPM5) touching VNCAPHV) must be coincident with (M4 over VNCAPM4)
15365 0 GRVNCAPHV12b: ((MT over VNCAPMT) touching VNCAPHV) must be coincident with (M5 over VNCAPM5)
15366 0 GRVNCAPHV12b: ((MT over VNCAPMT) touching VNCAPHV) must be coincident with (M4 over VNCAPM4)
15367 0 GRVNCAPHV12b: ((MT over VNCAPMT) touching VNCAPHV) must be coincident with (M3 over VNCAPM3)
15368 0 GRVNCAPHV12b: ((MT over VNCAPMT) touching VNCAPHV) must be coincident with (M2 over VNCAPM2)
15369 0 GRVNCAPHV12b: ((MT over VNCAPMT) touching VNCAPHV) must be coincident with (M1 over VNCAPM1)
15372 0 GRVNCAPHV12d: ((M2 intersect VNCAP_M2) touching VNCAPHV) within (M1 intersect VNCAP_M1) >= 0.00.
15374 0 GRVNCAPHV18: (M1 intersect VNCAP_M1) within VNCAPHV >= 0.00.
15375 0 GRVNCAPHV19: ((M1 intersect VNCAP_M1) touching VNCAPHV) to RX space >= 1.50 um.
15376 0 GRVNCAPHV19: ((M2 intersect VNCAP_M2) touching VNCAPHV) to RX space >= 1.50 um.
15377 0 GRVNCAPHV19: ((M3 intersect VNCAP_M3) touching VNCAPHV) to RX space >= 1.50 um.
15378 0 GRVNCAPHV19: ((M4 intersect VNCAP_M4) touching VNCAPHV) to RX space >= 1.50 um.
15379 0 GRVNCAPHV19: ((M5 intersect VNCAP_M5) touching VNCAPHV) to RX space >= 1.50 um.
15380 0 GRVNCAPHV19: ((MT intersect VNCAP_MT) touching VNCAPHV) to RX space >= 1.50 um.
15388 0 GR942b: DV(pad) to any other shape (AM) >= 3.00 um.
15389 0 GR942b: DV(pad) to any other shape (K1) >= 3.00 um.
15390 0 GR942b: DV(pad) to any other shape (DIPI) >= 3.00 um.
15391 0 GR942b: DV(pad) to any other shape (PCFUSE) >= 3.00 um.
15392 0 GR942b: DV(pad) to any other shape (QT) >= 3.00 um.
15393 0 GR942b: DV(pad) to any other shape (RXHV) >= 3.00 um.
15394 0 GR942b: DV(pad) to any other shape (RXHV_IBM) >= 3.00 um.
15395 0 GR942b: DV(pad) to any other shape (NG) >= 3.00 um.
15396 0 GR942b: DV(pad) to any other shape (DI) >= 3.00 um.
15398 0 GR942b: DV(pad) to any other shape (WVR) >= 3.00 um.
15399 0 GR942b: DV(pad) to any other shape (LOGOBND) >= 3.00 um.
15400 0 GR942b: DV(pad) to any other shape (VNCAP_M1) >= 3.00 um.
15401 0 GR942b: DV(pad) to any other shape (VNCAP_M2) >= 3.00 um.
15402 0 GR942b: DV(pad) to any other shape (VNCAP_M3) >= 3.00 um.
15403 0 GR942b: DV(pad) to any other shape (VNCAP_M4) >= 3.00 um.
15404 0 GR942b: DV(pad) to any other shape (VNCAP_M5) >= 3.00 um.
15405 0 GR942b: DV(pad) to any other shape (VNCAP_MT) >= 3.00 um.
15408 0 GR942b: DV(pad) to any other shape (FTBAR) >= 3.00 um.
15412 0 GR945b: DV must be within CHIPEDGE (Max) <= 190.00 um.
15414 0 GR941b: DV PAD space >= 11.00 um.
15416 0 GR946b: Non-rectangular DV pad found!
15419 0 GR946b: DV pad width (must be rectangular) >= 62.00 um.
15430 0 GR946g: DV pad length (perp to CHIPEDGE) >= 95.000 um.
15442 0 GR946g: DV pad length (perp to CHIPEDGE) >= 95.000 um.
15446 0 GR946g: DV pad width >= 62.0 um and length >= 95.0 um !
15457 0 GR946g: DV pad length (perp to CHIPEDGE) >= 95.000 um.
15460 0 GR948b1: DV not within last metal found!
15462 0 GR948b1: DV must be within AM >= 3.00 um.
15466 0 GR951: no shapes allowed below a pad via (K1)
15469 0 GR951: no shapes allowed below a pad via (PCFUSE)
15471 0 GR951: no shapes allowed below a pad via (QT)
15474 0 GR951: no shapes allowed below a pad via (DIPI)
15475 0 GR951: no shapes allowed below a pad via (DI)
15484 0 GR951: no shapes allowed below a pad via (VNCAP_M1)
15485 0 GR951: no shapes allowed below a pad via (VNCAP_M2)
15486 0 GR951: no shapes allowed below a pad via (VNCAP_M3)
15487 0 GR951: no shapes allowed below a pad via (VNCAP_M4)
15488 0 GR951: no shapes allowed below a pad via (VNCAP_M5)
15489 0 GR951: no shapes allowed below a pad via (VNCAP_MT)
15491 0 GR951: no shapes allowed below a pad via (MT)
15493 0 GR951: no shapes allowed below a pad via (FTBAR)
15494 0 GR951: no shapes allowed below a pad via (rxhv)
15495 0 GR951: no shapes allowed below a pad via (rxhv_ibm)
15496 0 GR951: no shapes allowed below a pad via (WVR)
15497 0 GR951: no shapes allowed below a pad via (LOGOBND)
15499 0 GR951: no shapes allowed below a pad via (NG)
15735 0 GRBONDPAD1: BONDPAD overlap past LASTMETAL >= 0.100 um.
15748 0 GRBONDPAD3: LASTMETAL(over BONDPAD) not within (BB or PC or ((M1 sized by 0.2) sized by -0.2)) found!
15750 0 GRBONDPAD3: LASTMETAL(over BONDPAD) must be within BB >= 4.900 um.
15752 0 GRBONDPAD3: LASTMETAL(over BONDPAD) must be within PC >= 4.900 um.
15754 0 GRBONDPAD3: LASTMETAL(over BONDPAD) must be within ((M1 sized by 0.2) sized by -0.2) >= 4.900 um.
15764 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching BP found!
15774 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching E1 found!
15784 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching K1 found!
15804 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M2 found!
15814 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M3 found!
15824 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M4 found!
15834 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching M5 found!
15844 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching MT found!
15854 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching NW found!
15864 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching RX found!
15874 0 GRBONDPAD4: LASTMETAL(over BONDPAD) touching NS found!
15875 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to BP space >= 4.900 um.
15876 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to E1 space >= 4.900 um.
15877 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to K1 space >= 4.900 um.
15878 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M1 space >= 4.900 um.
15879 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M2 space >= 4.900 um.
15880 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M3 space >= 4.900 um.
15881 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M4 space >= 4.900 um.
15882 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to M5 space >= 4.900 um.
15883 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to MT space >= 4.900 um.
15884 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to NW space >= 4.900 um.
15885 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to PC space >= 4.900 um.
15886 0 GRBONDPAD4: LASTMETAL(over BONDPAD) to RX space >= 4.900 um.
15891 0 WARNING: YOU HAVE BOTH C4 AND WIREBOND PADS IN THIS DESIGN
15916 0 GRF20: FILL shape on M2 area <= 144.00 sq. um.
15917 0 GRF20: FILL shape on M3 area <= 144.00 sq. um.
15918 0 GRF20: FILL shape on M4 area <= 144.00 sq. um.
15919 0 GRF20: FILL shape on M5 area <= 144.00 sq. um.
15920 0 GRF20: FILL shape on MT area <= 144.00 sq. um.
15924 0 GRF20: FILL shape on E1 area <= 144.00 sq. um.
15946 0 PFETM_L PFETM channel length for W < 1 U     >= 0.53 U
15953 0 PFETIM_L PFETIM channel length for W < 1 U     >= 0.53 U
15960 0 PFETM_W PFETM channel width for L < 0.53     >= 1.0 U
15967 0 PFETIM_W PFETIM channel width for L < 0.53     >= 1.0 U
15972 0 GRTGSC0a: SCGATE must be touched ((((PC over RX) over TG) over BP) over NW) 
15985 0 GRTGSC2b: SCGATE cannot touch (BB,OP,PD)
15988 0 GRTGSC2c: SCGATE must covered by all of following levels (NW,BP,TG)
15993 0 GRTG1: ((PC over RX) over TG) width for NFET >= 0.70  um.
15997 0 GRTG2: ((PC over RX) over TG) width for PFET >= 0.50  um.
16000 0 GRTG3: Non-rectangular ((PC_over RX) touching TG) found!
16001 0 GRTG3: 45 degree ((PC_over RX) touching TG) found
16010 0 GRTG4: Non-orthogonal (RX ( not over ((ESD_DUMMY,ESD_CDM )RXHV) ) or (touching (PC not over RXHV))) touching (TG or RX5V)) shape found!
16016 0 GRTG5: (PC touching (TG or RX5V)) to RX (abutting not allowed) >= 0.160 um.
16022 0 GRTG6: (RX touching (TG or RX5V)) to PC (abutting not allowed) >= 0.160 um.
16030 0 GRTG7_HV: (((PC over (RX not over RXHV)) touching TG) touching BP) must be within ((TG over NW) not over MOSVAR) >= 1.260 um.
16040 0 GRTG8_HV: ((((PC over (RX not over (RXHV or RXHV_IBM))) touching TG) not touching BP) not touching NW) must be within (TG not over ( NW or MOSVAR)) >= 1.80 um.
16044 0 GRTG8a: (((PC over RX) touching TG) not touching BP) must be within TG >= 0.50 um.
16047 0 GRTG8b: ((PC over RX) over RXHV) within TG >= 0.50 um.
16048 0 GRTG9: (PC over RX) to TG space >= 1.00 um.
16050 0 GRTG10: TG overlap past NW >= 0.94 um.
16053 0 GRTG10a: (NW over TG) space >= 1.08 um.
16054 0 GRTG10a1: TG abuting NW is prohibited!
16055 0 GRTG12: TG  to BB  >= 0.80 um.
16056 0 GRTG12: TG  cannot touch BB .
16057 0 GRTG12: TG  to NW  >= 0.80 um.
16058 0 GRTG12: TG  to MOSVAR  >= 0.80 um.
16059 0 GRTG13: TG overlap of NW >= 0.80 um.
16061 0 GRTG13a: NW width under TG >= 0.80 um.
16063 0 GRTG15: NW overlap past TG >= 0.80 um.
16067 0 GRTG16: RX touching (TG or RX5V) cannot touch (PC not over TG) 
16072 0 GRTG19: TG cannot touch PCFUSE .
16073 0 GRTG19: TG to PCFUSE  >= 2.50 um.
16074 0 GRTG20: Non-orthogonal TG shape found!
16075 0 GRTG21: TG width >= 0.80  um.
16077 0 GRTG24a: (TG not over RXHV) to DN space >= 6.50  um.
16081 0 GRTG24b: (TG not over RXHV) within (DN not touching (RXHV_IBM touching text == NFETI120M_REV_1.0 PFET12MH_REV_1.0)) >= 1.20 um.
16082 0 GRTG24b: (TG not over RXHV) straddling (DN not touching (RXHV_IBM touching text == NFETI120M_REV_1.0 PFET12MH_REV_1.0)) not allowed!
16084 0 GRTG24c: TG to (DN touching(text on level RXHV2 == + 120)) >= 9.50 um.
16087 0 GRTG24d: (TG not over RXHV_IBM) within (DN touching(text on level RXHV2 == + 120) )) >= 3.00 um.
16088 0 GRTG24d: (TG not over RXHV_IBM) straddling (DN touching(text on level RXHV2 == + 120) ) found.
16091 0 GRTG50: ((RX over PC) over TG) width >= 0.50  um.
16096 0 GRTG110: (RX touching TG) overlap past PC >= 0.380 um.
16104 0 GRTG252: ((PC over RX) touching TG ) to (NW or MOSVAR) >= 1.80um.
16105 0 GRTG252: ((PC over RX) touching TG ) to (NW or MOSVAR) >= 1.80um.
16115 0 GRTG252a: (((PC over RX) not over MOSVAR) touching TG ) within NW  >= 1.60um.
16126 0 GRTG260a1: (RX(P+) touching (TG or RX5V)) within NW >= 0.80 um.
16151 0 GRTG260a2: (RX P+ junction touching {TG,RX5V}) within NW for (NW width >=40um) and ((not NW) width >=40um) >= 0.90um
16161 0 GRTG260c1: RX P+ junction within (NW touching {TG, RX5V}) >=0.80um
16177 0 GRTG260c2: RX P+ junction within (NW touching {RX5V, TG} for (NW width >=40um) and ((not NW) width >=40um) >=0.90um
16189 0 GRTG265a1: (RX N+ junction touching {RX5V, TG}) to NW >= 1.00um
16199 0 GRTG265a2: (RX N+ junction touching {RX5V, TG}) to NW for (NW width >=40um) and ((not NW) width >=40um) >= 1.10um
16209 0 GRTG265c1: RX N+ junction to (NW touching ({RX5V, TG} over RX) not over BP) >=1.00um
16221 0 GRTG265c2: RX N+ junction to (NW touching (RX5V, TG) for (NW width >=40um) and ((not NW) width >=40um) >=1.10um
16230 0 GRTG265e1: (RX N+ junction touching {RX5V, TG} ) to BB >= 1.00um.
16260 0 GRTG268a: (RX(in BP)touching TG) in ((NW or SN) not over (RXHV or RXHV_IBM))to (RX(not BP) (NW or SN) contact not over TG) in the same ((NW or SN)not over (RXHV, RXHV_IBM)) space <= 20.000 um.
16343 0 GRTG268b: (RX(no BP) not over (RXHV sized by 1.00) touching TG, not touching NW, not touching BB ) to Substrate Contact space <= 15.000 um.
16353 0 GRTG353: (RX touching (RX5V or TG))  within BP  >= 0.14um.
16370 0 GRTG354b: (RX substrate contact OVER ((NW touching {RX5V, TG})sized by 1.00 per edge)) within BP >= 0.14um
16379 0 GRTG354b: (RX IsoPwell contact OVER ((NW touching {RX5V, TG})sized by 1.00 per edge)) within BP >= 0.14um
16393 0 GRTG356b: (RX N-well ( NW touching {RX5V, TG}) contact) not over (( NW touching {RX5V, SPACE5V} sized by -0.80 per edge )) to BP >= 0.14um
16408 0 GRTG358a: TE  width >= 0.44  um.
16409 0 GRTG358a: TF  width >= 0.44  um.
16411 0 GRTG358b: TE  space >= 0.44  um.
16413 0 GRTG358b: TF  space >= 0.44  um.
16415 0 GRTG358b: TE  notch >= 0.44  um.
16417 0 GRTG358b: TF  notch >= 0.44  um.
16418 0 GRTG358c: TE  area  >= 0.387 sq.um.
16419 0 GRTG358c: TF  area  >= 0.387 sq.um.
16420 0 GRTG358c: TG  area  >= 0.387 sq.um.
16430 0 GRTG358d: TE enclosed area >= 0.387 sq. um.
16431 0 GRTG358d: TF enclosed area >= 0.387 sq. um.
16432 0 GRTG358d: TG enclosed area >= 0.387 sq. um.
16433 0 GRTG358e: WX  width >= 0.70  um.
16434 0 GRTG358e: WY  width >= 0.70  um.
16436 0 GRTG358f: WX  notch >= 0.70  um.
16438 0 GRTG358f: WY  notch >= 0.70  um.
16440 0 GRTG358f: WX  space >= 0.70  um.
16442 0 GRTG358f: WY  space >= 0.70  um.
16443 0 GRTG358g: WX  area  >= 2.100 sq.um.
16444 0 GRTG358g: WY  area  >= 2.100 sq.um.
16451 0 GRTG358h: WY enclosed area >= 2.100 sq. um.
16452 0 GRTG358h: WX enclosed area >= 2.100 sq. um.
16464 0 GRTG17_HV: TG cannot touch ( BB RN RR RP NE PE PD NR PR PCFUSE DI GRLOGIC) 
16466 0 GRTG17c_HV: TG not touching (PC over RX) found!
16468 0 GRTG207_HV: (CA touching TG ) to PC >= 0.16um.
16477 0 GRTG14_HV: (((RX or PC) not over ((RXHV sized by 0.28) or ESDUMMY)) touching OP) to TG  >= 1.00 um.
16483 0 GRTG14_HV: ((((RX or PC) not over ((RXHV sized by 0.28) or (RXHV_IBM touching text = NFETI120M_REV_1.0) or ESDUMMY)) touching OP) cannot touch TG)
16497 0 GRTG18_HV: (TG not over (RXHV or RXHV_IBM)) cannot touch ((RX not over (RXHV or RXHV_IBM)) over (BP or PD) not over (NW or MOSVAR)).
16500 0 GRTG18_HV: (TG not over (RXHV or RXHV_IBM) ) to ((RX not over (RXHV or RXHV_IBM))over (BP or PD) not over NW) >= 0.50 um.
16507 0 GRTG18a: (TG over NW) touching ((RX not over BP) over NW) found !
16509 0 GRTG18a: (TG over NW) to ((RX not over BP) over NW)  >= 0.50 um.
16512 0 GRTG22a_HV: (TG not over RXHV) space >= 0.80  um.
16515 0 GRTG22a_HV: (TG not over RXHV) notch >= 0.80  um.
16518 0 GRTG22b_HV: (TG over RXHV) space >= 0.44  um.
16521 0 GRTG22b_HV: (TG over RXHV) notch >= 0.44  um.
16530 0 GRTG52_HV: ((RX not over( RXHV RXHV_IBM ESDDUMMY ESD_CDM) touching (TG or RX5V)) to (RX not over (RXHV RXHV_IBM)) >= 0.70 um.
16544 0 GRTG52a_HV: (((RX over( RXHV ESDDUMMY ESD_CDM) sized by 0.7) over BP) touching (TG or RX5V)) to ((RX over BP) not over RXHV) >= 0.70  um.
16558 0 GRTG52b_HV: (((RX over( RXHV ESDDUMMY ESD_CDM) sized by 0.7) not over BP) touching (TG or RX5V)) to (RX  not over (BP RXHV)) >= 0.70  um.
16559 0 GRTG52c_HV: (((RX over( RXHV ESDDUMMY ESD_CDM) sized by 0.7) over BP) touching (TG or RX5V)) to (RX  not over (BP RXHV))>= 0.36  um.
16562 0 GRTG52d_HV: (((RX over( RXHV ESDDUMMY ESD_CDM) sized by 0.7) not over BP) touching (TG or RX5V)) to ((RX  not over RXHV) over BP) >= 0.36  um.
16567 0 GRTG52e_HV: (((RX over( RXHV ESDDUMMY ESD_CDM) sized by 0.7) not over BP) touching (TG or RX5V)) to (((RX  not over RXHV) over BP)not over (ESDUMMY ESD_CDM)) >= 0.70  um.
16572 0 GRTG52f_HV: (((RX over( RXHV ESDDUMMY ESD_CDM) sized by 0.7) not over BP) touching (TG or RX5V)) to (((RX  not over (RXHV BP)) not over (ESDUMMY ESD_CDM)) >= 0.70  um.
16574 0 GRTG52g_HV: (((RX over( RXHV ESDDUMMY ESD_CDM) sized by 0.7) over BP) touching (TG or RX5V)) within BP >= 0.14  um.
16575 0 GRTG52h_HV: (((RX over( RXHV ESDDUMMY ESD_CDM) sized by 0.7) not over BP) touching (TG or RX5V)) to BP >= 0.14  um.
16587 0 GRTG52i_HV: (TG touching (( RX to RX space <0.7) not over (RXHV RXHV_IBM)) found.
16588 0 GRTG52i_HV: (TG to (( RX to RX space <0.7) not over (RXHV RXHV_IBM)) >= 0.50  um.
16592 0 GRTG104a_HV: ((PC over NW) over TG ) to (PC over TG) >= 0.34um.
16597 0 GRTG104b_HV: (((PC not over NW) over TG ) to (PC over TG)) over RX >= 0.50um.
16608 0 GRTG111_HV: (PC not over (RXHV or RXHV_IBM)) overlap past (RX touching TG) >= 0.60 um.
16610 0 GRTG111_HV: (PC not over (RXHV or RXHV_IBM)) overlap past RX (RX touching TG) coincident
16622 0 GRDN1: DN width >= 10.80  um.
16624 0 GRDN2: DN space >= 13.50  um.
16626 0 GRDN2: DN notch >= 13.50  um.
16629 0 GRDN2a: (DN touching (RXHV2=+120) to DN space >= 18.0  um.
16632 0 GRDN2b: (DN touching (PFET120M_REV_1.0) to DN space >= 19.7 um.
16670 0 GRDN3: All DN edges must be covered by [(((RX not over BP) sized by 1.0) over ({NW,SN} sized by 0.5)) or (({NW,SN} over {(RXHV sized by 1.4) or RXHV_IBM}) sized by 2.3)
16692 0 GRDN3a: ((( DN sized by -2.3) over (RXHV sized by 7.15)) not over ((RXHV sized by 0.7) sized by -0.5)) must be covered by (NW ,SN)!
16717 0 GRDN3b: All [(DN not touching (text on level RXHV2 == +120) ] must be covered by [(((RX (not over BP) sized by 1.0) over (NW sized by 0.5)) or (RXHV_IBM sized by 3.3)]
16738 0 GRDN3c: All [((DN touching RXHV2 == +120) ) not over (DN sized by -3.5)] must be covered by ((NW sized by 0.5) or (RXHV_IBM sized by 3.3))
16749 0 GRDN4: ((union( NW over DN , (NW over DN) holes)) not over (union( NW over DN, (NW over DN) holes) sized by -1.3) must be covered by (NW not over (TG not over RXHV))
16750 0 GRDN5: NW straddling DN found!
16752 0 GRDN5: NW within DN >= 0.50  um.
16753 0 GRDN5a: RX straddling DN found!
16755 0 GRDN5a: RX within DN >= 0.75  um.
16756 0 GRDN5b: BP straddling DN found!
16757 0 GRDN5b: PD straddling DN found!
16759 0 GRDN5b: BP within DN >= 1.35  um.
16761 0 GRDN5b: PD within DN >= 1.35  um.
16763 0 GRDN5d: SN within DN >= 0.50  um.
16766 0 GRDN5c: PD straddling (DN touching (text on level RXHV2== '+120') not touching text on level RXHV_IBM = PFET120M_REV_1.0) found!
16768 0 GRDN5c: PD within (DN touching (text on level RXHV2== '+120') not touching text on level RXHV_IBM = PFET120M_REV_1.0) >= 3.50  um.
16769 0 GRDN5c: BP straddling (DN touching (text on level RXHV2== '+120') not touching text on level RXHV_IBM = PFET120M_REV_1.0) found!
16771 0 GRDN5c: BP within (DN touching (text on level RXHV2== '+120') not touching text on level RXHV_IBM = PFET120M_REV_1.0) >= 3.50  um.
16774 0 GRDN6:  Each DN shape must be fully enclosed with P+Rx ring
16779 0 GRDN6a: Multiple DN shape within single P+Rx ring are not allowed!
16781 0 GRDN7: DN to P+ junction space >= 5.50  um.
16792 0 GRDN7a: (DNtouching[((RX or PC) touching (RXHV_IBM touching ( text on level RXHV_IBM == {NFETI120M_REV_1.0, PFET120M_REV_1.0,ESD120_REV_1.0} ))) or (text on level RXHV2 == +120)]) to p+RX space >= 9.50 um.
16800 0 GRDN8: (RX,BB,NW,TG) are not allowed between DN and its enclosing p+RX
16812 0 GRDN8a: RXEXCLUD must cover the region between DN and its enclosing P+RX
16818 0 GRDN8b: PCEXCLUD is required to cover the region between (DN touching text on level RXHV2==+120) and its enclosing p+RX ring.PCEXCLUD may touch RX.
16819 0 GRDN9: DN to NW space >= 12.00  um.
16821 0 GRDN9a: (DN touching RXHV2 text= +120) to NW space >= 15.00  um.
16822 0 GRDN9a: (DN touching RXHV2 text= +120) to NW space >= 15.00  um.
16852 0 GRDN10: PC is not allowed between (N+RX ring in DN) and its enclosing P+RX ring
16869 0 GRDN11: M1 is required to cover the region (((DN sized by +0.2) not touching [((RX or PC) touching (RXHV_IBM touching ( text on level RXHV_IBM == {NFETI120M_REV_1.0,PFET120M_REV_1.0} ))) ]- (DN sized by -0.75))
16889 0 GRDN11a: M1 from rule DN11 must be connected to N+RX ring
16904 0 GRDN11b: M1 is required to cover the region ((( DN touching(text on level RXHV2 == +120)] not touching [((RX or PC) touching (RXHV_IBM touching ( text on level RXHV_IBM =={NFETI120M_REV_1.0, PFET120M_REV_1.0, ESD120_REV_1.0} )))]) sized by +5.5) - (DN sized by -0.75))
16908 0 GRDN11c: M1 from rule DN11b must be connected to N+ RX ring
16941 0 GRDN12: M1 is required to cover the region ((( DN not touching[((RX or PC) touching(RXHV_IBM touching (text on level RXHV_IBM {NFETM120_REV_1.0,PFETM120_REV_1.0, ESD120_REV_1.0} ))) or (text on level RXHV2 = +120)]) sizedby 5.5 ) - (DN sized by 1.0))
16948 0 GRDN12a: M1 from rule DN12 must be connected to P+RX ring
16965 0 GRDN12b: M1 is required to cover the region ((( [ DN touching (text on level RXHV2 == +120)] not touching [((RX or PC) touching (RXHV_IBM touching ( text on level RXHV_IBM == {NFETI120M_REV_1.0, PFET120M_REV_1.0, ESD120_REV_1.0} )))]) sized by 9.5) - (DN sized by 6.5))
16971 0 GRDN12c: M1 from rule DN12b must be connected to P+RX ring
16978 0 GRDN13: No M1 metal is allowed between the M1 metal ring defined in DN11 and DN12.
16985 0 GRDN13: No M1 metal is allowed between the M1 metal ring defined in DN11b and DN12b.
16993 0 GRDN13a: M2EXCLUD/MTEXCLUD(3LM) must cover the area between the M1 metal ringsdefined in rules DN11b and DN12b
17003 0 GRDN13b: M1EXCLUD/M2EXCLUD/MTEXCLUD(3LM) must cover the area between DN touching ((Rx or PC) touching (RXHV_IBM touching (text on level {NFETI120M_REV_1.0, PFET120M_REV_1.0, ESD120_REV_1.0})) and its enclosing P+ring
17006 0 GRDN14: (DN touching (text on level RXHV2 == +120)) must be rectangular. (No polygon DN shapes allowed for 120v DN wells)
17023 0 GRDN15: ((DN touching[((RX or PC)touching(RXHV_IBMtouching(text on level RXHV_IBM, {NFETI120M_REV_1.0, PFET120M_REV_1.0, ESD120_REV_1.0} ))) or (text on levelRXHV2 +120)]) sized by 8.5) - (DN sized by -0.5) must be covered by BFCUS
17031 0 GRDN16: (RXHV_IBM touching (text on level RXHV_IBM, NFETI20MH_REV_1.0) sized by 0.6) to (RX) > 1.5
17032 0 GRDN16: (RXHV_IBM touching (text on level RXHV_IBM, NFETI20MH_REV_1.0) sized by 0.6) to (PC) > 1.5
17033 0 GRDP1: DP width >= 0.70  um.
17035 0 GRDP2: DP space >= 0.70  um.
17037 0 GRDP2: DP notch >= 0.70  um.
17039 0 GRSN1: SN width >= 0.70  um.
17042 0 GRSN1a: (SN to SN minimum space) starddling RXHV >= 2.10  um.
17045 0 GRSN2: SN space >= 0.70  um.
17048 0 GRSN2: SN notch >= 0.70  um.
17049 0 GRSN3: SN over NW is not allowed
17071 0 GRSN4: ((RX within SN) not over ((( RXHV sized by 0.2) sized by -0.2) or RXHV_IBM) ) >= 0.25 um.
17072 0 GRSN5: SN to DN space >= 12.0  um.
17074 0 GRSP1: SP width >= 0.70  um.
17077 0 GRSP2: SP space >= 0.70  um.
17080 0 GRSP2: SP notch >= 0.70  um.
17082 0 GRENCL1: (SN SP DP NW BF ) area >= 2.100 sq.um.
17084 0 GRENCL1: (SN SP DP NW BF ) area >= 2.100 sq.um.
17086 0 GRENCL1: (SN SP DP NW BF ) area >= 2.100 sq.um.
17087 0 GRENCL1: (SN SP DP NW BF ) area >= 2.100 sq.um.
17088 0 GRENCL1: (SN SP DP NW BF ) area >= 2.100 sq.um.
17112 0 GRENCL2: (SN SP DP NW BF ) enclosed area >= 2.100 sq.um.
17113 0 GRENCL2: (SN SP DP NW BF ) enclosed area >= 2.100 sq.um.
17114 0 GRENCL2: (SN SP DP NW BF ) enclosed area >= 2.100 sq.um.
17115 0 GRENCL2: (SN SP DP NW BF ) enclosed area >= 2.100 sq.um.
17116 0 GRENCL2: (SN SP DP NW BF ) enclosed area >= 2.100 sq.um.
17119 0 GR5VONLY01: If 5VONLY shape exists in the layout then all TG shapes must be covered by 5VONLY
17132 0 GR5VONLY02: 5VONLY cannot exist in the same layout with any of the following levels {NE PE NG NR PR ((PC over RX) not over (TG or OUT_FILL))DI DIPI BP2ND
17138 0 GR5VONLY03: 5VONLY  touching CHIPEDGE  must match CHIPEDGE
17145 0 GR5VONLY04: OUT_FILL touching (CA CABAR) found!
17149 0 GRBP2ND1: All BP2ND edges must abut (BB overDN) == 0.00 um.
17153 0 GRBP2ND1: All BP2ND edges must abut (BB overDN) == 0.00 um.
17154 0 GRBP2ND2: BP2ND to RN space >= 1.00 um.
17155 0 GRBP2ND2: BP2ND to NW space >= 1.00 um.
17156 0 GRBP2ND2: BP2ND to PR space >= 1.00 um.
17157 0 GRBP2ND2: BP2ND to NR space >= 1.00 um.
17158 0 GRBP2ND2: BP2ND to NE space >= 1.00 um.
17159 0 GRBP2ND2: BP2ND to PE space >= 1.00 um.
17160 0 GRBP2ND2: BP2ND to TG space >= 1.00 um.
17161 0 GRBP2ND2: BP2ND to NG space >= 1.00 um.
17162 0 GRBP2ND2: BP2ND to PC space >= 1.00 um.
17163 0 GRBP2ND2: BP2ND to RR space >= 1.00 um.
17164 0 GRBP2ND2: BP2ND to RP space >= 1.00 um.
17165 0 GRBP2ND2: BP2ND to OP space >= 1.00 um.
17166 0 GRBP2ND2: BP2ND to ZEROVT space >= 1.00 um.
17167 0 GRBP2ND2: BP2ND to GRLOGIC space >= 1.00 um.
17168 0 GRBP2ND2: BP2ND to RXHV space >= 1.00 um.
17169 0 GRBP2ND2: BP2ND to RXHV_IBM space >= 1.00 um.
17170 0 GRBP2ND2: BP2ND to SN space >= 1.00 um.
17171 0 GRBP2ND2: BP2ND to SP space >= 1.00 um.
17172 0 GRBP2ND2: BP2ND to DI space >= 1.00 um.
17173 0 GRBP2ND2: BP2ND to DP space >= 1.00 um.
17174 0 GRBP2ND2: BP2ND to DIPI space >= 1.00 um.
17175 0 GRBP2ND2: BP2ND touching RN prohibited
17176 0 GRBP2ND2: BP2ND touching NW prohibited
17177 0 GRBP2ND2: BP2ND touching PR prohibited
17178 0 GRBP2ND2: BP2ND touching NR prohibited
17179 0 GRBP2ND2: BP2ND touching NE prohibited
17180 0 GRBP2ND2: BP2ND touching PE prohibited
17181 0 GRBP2ND2: BP2ND touching TG prohibited
17182 0 GRBP2ND2: BP2ND touching NG prohibited
17183 0 GRBP2ND2: BP2ND touching PC prohibited
17184 0 GRBP2ND2: BP2ND touching RR prohibited
17185 0 GRBP2ND2: BP2ND touching RP prohibited
17186 0 GRBP2ND2: BP2ND touching OP prohibited
17187 0 GRBP2ND2: BP2ND touching ZEROVT prohibited
17188 0 GRBP2ND2: BP2ND touching GRLOGIC prohibited
17189 0 GRBP2ND2: BP2ND touching RXHV prohibited
17190 0 GRBP2ND2: BP2ND touching SN prohibited
17191 0 GRBP2ND2: BP2ND touching SP prohibited
17192 0 GRBP2ND2: BP2ND touching DI prohibited
17193 0 GRBP2ND2: BP2ND touching DIPI prohibited
17194 0 GRBP2ND2: BP2ND touching DP prohibited
17195 0 GRBP2ND2: BP2ND touching RXHV_IBM prohibited
17198 0 GRBP2ND3: (RX not over PD) touching BP2ND minimum width >= 1.00 um.
17201 0 GRBP2ND4: (RX over BP2ND) within PD >= 0.14 um.
17202 0 GRBP2ND5: BP2ND must be covered by MOSVAR
17203 0 GRBP2ND6: BP2ND must be covered by DN
17204 0 GRBP2ND350: BP2ND width >= 0.34 um.
17205 0 GRBP2ND351a: BP2ND area >= 0.387 sq.um.
17209 0 GRBP2ND351b: BP2ND enclosed area >= 0.387 sq. um.
17211 0 GRBP2ND352a: BP2ND to BP2ND >= 0.34 um.
17212 0 GRBP2ND352b: BP2ND to BP >= 0.34 um.
17213 0 GRBP2ND352b: BP2ND touching BP is prohibited!
17218 0 GRBP2ND999: BP2ND must be within CHIPEDGE
17219 0 GRNG1: NG width >= 0.44  um.
17221 0 GRNG2: NG space >= 0.44  um.
17223 0 GRNG2: NG notch >= 0.44  um.
17233 0 GRNG3: ((PC not over (RXHV or RXHV_IBM)) touching NG) to RX >= 0.40 um.
17238 0 GRNG4_HV: ((PC over RX) not over (RXHV, RXHV_IBM)) straddling NG found!
17240 0 GRNG4_HV: ((PC over RX) not over (RXHV, RXHV_IBM)) within NG >= 0.40 um.
17244 0 GRNG5_HV: ((PC over RX) not over (RXHV or RXHV_IBM)) to NG >= 0.70 um.
17253 0 GRNG6: TG to (((PC intersect rx) intersect NG) sized by 0.5) >= 0.44 um.
17263 0 GRNG207: (CA touching NG) to PC  >= 0.20 um.
17264 0 GRNG358c: NG area >= 0.387 sq.um.
17268 0 GRNG358d: NG enclosed area >= 0.387 sq. um.
17285 0 GRCUST1: (NW,TG,NG,BB,MOSVAR,((BP touching PCFUSE )sized -0.14) within NONIAGBH) >= 0.00 um.
17295 0 GRCUST1a: (NW,BB,BFMOAT) within NONIAGBF >= 0.00  um.
17297 0 GRCUST2: NW within NONIAGPH >= 0.00  um.
17312 0 GRCUST5: (NW,TG,NG,BB,MOSVAR,(BP touching PCFUSE )sized -0.14) BFMOAT within NOGEN >= 0.00  um.
17313 0 GRCUST6: BFCUS width >= 0.98  um.
17315 0 GRCUST7: BFCUS space >= 0.80  um.
17317 0 GRCUST7: BFCUS notch >= 0.80  um.
17321 0 GRCUST8: (BHCUS,PHCUS,TECUS,TFCUS) width >= 0.44  um.
17323 0 GRCUST9: (BHCUS,PHCUS,TECUS,TFCUS) space >= 0.44  um.
17325 0 GRCUST9: (BHCUS,PHCUS,TECUS,TFCUS) notch >= 0.44  um.
17334 0 GRCUST10: (BHCUS,PHCUS,TECUS,TFCUS,BPCUS) area >= 0.387 sq.um.
17338 0 GRCUST11: (BHCUS,PHCUS,TECUS,TFCUS,BPCUS) enclosed area >= 0.387 sq. um.
17339 0 GRCUST12: BPCUS width >= 0.34  um.
17341 0 GRCUST13: BPCUS space >= 0.34  um.
17343 0 GRCUST13: BPCUS notch >= 0.34  um.
17344 0 GR797_HV: BFMOAT touching DN is not allowed!
17348 0 GRBB1_HV: (BB(not abutting NW) over DN) width >= 4.280 um.
17354 0 GRBB2_HV: BB ring is not allowed over DN except when (NW or BP2ND) covers the inside of BB ring
17357 0 GRRL01: (KERFEXCL,OUTKERN,FILLKERN) touching CHIPEDGE is prohibited
17366 0 GRRL02: (NS NOGEN PHCUS WX WY BF BH PH BN) touching CHIPEDGE is prohibited
17367 0 GRRL02: (NS NOGEN PHCUS WX WY BF BH PH BN) used in layout is prohibited
17378 0 GR999a: KERFEXCL  must be within CHIPEDGE >= 11.06 um
17387 0 GR999a: FILLKERN  must be within CHIPEDGE >= 11.06 um
17396 0 GR999a: OUTKERN  must be within CHIPEDGE >= 11.06 um
17405 0 GR999a: NONIAGBH  must be within CHIPEDGE >= 11.06 um
17414 0 GR999a: NONIAGBF  must be within CHIPEDGE >= 11.06 um
17423 0 GR999a: NONIAGPH  must be within CHIPEDGE >= 11.06 um
17432 0 GR999a: NONIAGTE  must be within CHIPEDGE >= 11.06 um
17441 0 GR999a: NONIAGTE  must be within CHIPEDGE >= 11.06 um
17450 0 GR999a: NONIAGTF  must be within CHIPEDGE >= 11.06 um
17459 0 GR999a: NONIAGSN  must be within CHIPEDGE >= 11.06 um
17468 0 GR999a: NONIAGSP  must be within CHIPEDGE >= 11.06 um
17477 0 GR999a: NONIAGPV  must be within CHIPEDGE >= 11.06 um
17487 0 GR999a: NONIAGNV  must be within CHIPEDGE >= 11.06 um
17496 0 GR999a: NOGEN  must be within CHIPEDGE >= 11.06 um
17505 0 GR999a: TECUS  must be within CHIPEDGE >= 11.06 um
17514 0 GR999a: TFCUS  must be within CHIPEDGE >= 11.06 um
17523 0 GR999a: PVCUS  must be within CHIPEDGE >= 11.06 um
17532 0 GR999a: NVCUS  must be within CHIPEDGE >= 11.06 um
17541 0 GR999a: BHCUS  must be within CHIPEDGE >= 11.06 um
17550 0 GR999a: BFCUS  must be within CHIPEDGE >= 11.06 um
17559 0 GR999a: BPCUS  must be within CHIPEDGE >= 11.06 um
17568 0 GR999a: PHCUS  must be within CHIPEDGE >= 11.06 um
25040 0 GR268b_HV: RX(N+ Jct) to (Pwell Contact not over TG) space <= 53.000 um.
25042 0 GR268b_HV: RX(N+ Jct) to (PI    Contact not over TG) space <= 53.000 um.
25053 0 GR268b_HV: DN not over(NW,SN,BB,RXHV,TG) must contain ((RX over BP) not over (NW,SN,BB,RXHV,TG)).
27026 0 GRNW1_HV: Maximum (((NW or SN) over DN) to ((NW or SN)over DN) space) in the same DN shape <= 65.
27035 0 GRNW1_HV: Maximum (((NW or SN) over DN) to ((NW or SN)over DN) notch) in the same DN shape <= 65.
27086 0 GRNW2_HV: ((DN sized by -0.5) not over ( NW or BB) space) (different net) >= 1.30 um.
27152 0 GR123a_HV: 45 degree outside RX vertice under (PC not under (GRLOGIC, RXHV, RHV_IBM)) found!
27154 0 GR123a_HV: 90 degree inside RX vertice under (PC not under (GRLOGIC, RXHV, RHV_IBM)) found!
27162 0 GR123a_HV: 90 degree outside RX vertice under (PC not under (GRLOGIC, RXHV, RHV_IBM)) found!
27167 0 GR250a_HV: Non-orthogonal (NW not over RXHV) shapes found!
27170 0 GR260_HV: ((RX within BP) not over RXHV) straddling NW found!
27172 0 GR260_HV: ((RX within BP) not over RXHV) within NW >= 0.420 um.
27196 0 GR268_HV: {(RX(in BP) not over TG) in ((NW or SN) over DN (not over RXHV))} to {RX(not BP) over DN not over TG} (same NW or SN) space <= 53.000 um.
27200 0 GR269_HV: (PC over ( RX not over RXHV) (where (RX not over RXHV) Straddles NW)) straddling NW found!
27202 0 GR269_HV: (PC over ( RX not over RXHV) (where (RX not over RXHV) Straddles NW)) to NW space >= 0.700 um.
27204 0 GR269a_HV: ( RX(NWcont) not over RXHV) overlap past (NW not over GRLOGIC ) >= 0.700 um.
27209 0 GR269b_HV: ( RX not over RXHV ) overlap past (NW over DN) >= 0.700 um.
27220 0 GR353_HV: (((RX not over RXHV) over BP) over NW) within BP >= 0.140 um.
27224 0 GR353_HV: (((RX not over RXHV) over BP) over NW) within BP (coincident) >= 0.140 um.
27228 0 GR353_HV: (((RX not over RXHV) over BP) over NW) within BB >= 0.140 um.
27232 0 GR353_HV: (((RX not over RXHV) over BP) over NW) within BB (coincident) >= 0.140 um.
27244 0 GR354a_HV: (((RX(sub or Isopwell cont) not over RXHV) not GRLOGIC) not (NW +0.42)) within BP >= 0.000 um.
27249 0 GR715b_HV: (((RX not over (RXHV sized by 0.28)) touching OP) inside BP) not within NW found!
27251 0 GR715b_HV: (((RX not over (RXHV sized by 0.28)) touching OP) inside BP) within NW >= 0.420 um.
27253 0 GR728_HV: OP to (RX not over ( RXHV sized by 0.28 )) space >= 0.160 um.
27255 0 GR731_HV: OP to (PC not over ( RXHV sized by 0.28 )) space>= 0.260 um.
27260 0 GR734a_HV: ((RX not over ( RXHV sized by 0.28 )) touching OP) straddling BP found!
27262 0 GR734a_HV: ((RX not over ( RXHV sized by 0.28 )) touching OP) within BP >= 0.220 um.
27270 0 GR735a2_HV: ((PC not over ( RXHV sized by 0.28 )) touching OP) within BB >= 0.300 um.
27272 0 GR735a2_HV: ((PC not over ( RXHV sized by 0.28 )) touching OP) within BP >= 0.300 um.
27274 0 GR735a2_HV: (PC touching OP) straddling (BP,BB) found!
27275 0 GR735b_HV: ((PC not over ( RXHV sized by 0.28 )) touching OP) to BP space >= 0.300 um.
27279 0 GR736_HV: (OP not over ((ESDUMMY or ESD_CDM) over TG)) over (PC intersect RX) found!
27292 0 GR738_HV: Non-rectangular (OP intersect (RX not over ( RXHV sized by 0.28 ))) found!
27294 0 GR738_HV: Non-rectangular (OP intersect ((PC not over VNCAP_PC) not over (( RXHV sized by 0.28) or (RXHV_IBM touching text = NFETI120M_REV_1.0))) found!
27299 0 GROP29_HV: ((PC not over (( RXHV sized by 0.28 ) or ESDUMMY or ESD_CDM)) touching OP) touching RX found!
27311 0 GRPBR19_HV: More than ONE set of contacts found on a PC resistor!
27315 0 GRPBR19_HV: More than ONE set of contacts found on a RX resistor!
27330 0 GRPBR19_HV: More than ONE set of contacts found on a HVPWRES resistor!
27344 0 GRPBR19_HV: More than ONE set of contacts found on a HVNWRES resistor!
27349 0 GRPBR29_HV: PC(touching OP, not GRLOGIC) within NW >= 2.000 um.
27353 0 GRPBR31: (PC(touching OP, touching BB) not over vncap_pc) within BB >= 2.000 um.
27357 0 GRPHHOLE8_HV: (((PC over RX) not over RXHV ) over NW) touching PHHOLE1 found!
27358 0 GRPHHOLE8_HV: (((PC over RX) not over RXHV ) over NW) to PHHOLE1 space >= 0.360 um.
27362 0 GR132_HV: ((PC that intersects RX) not over (RXHV RXHV_IBM)) area <= 320.000 sq.um.
27366 0 GR132a_HV: ((PC that intersects RX) touching (RXHV RXHV_IBM)) area <= 4800.00 sq.um.
27370 0 GR716c_HV: (((OP not over ( RXHV sized by 0.28 ) ) intersect RX) not touching NW ) touching BP found!
27373 0 GRPBR33_HV: (PC not over ( RXHV sized by 0.28 ) )(touching OP, no touching NW, not over GRLOGIC) to adjacent NW >= 2.000 um.
27382 0 GRHV1: RXHV with 0 or more than 1 RXHV label
27391 0 GRHV1a: RXHV_IBM with 0 or more than 1 RXHV_IBM label
27393 0 GRHV2: RXHV space >= 0.02 um.
27395 0 GRHV2: RXHV notch >= 0.02 um.
27397 0 GRHV2a: RXHV_IBM space >= 0.02 um.
27399 0 GRHV2a: RXHV_IBM notch >= 0.02 um.
27400 0 # WARNING: GRHV3 is not a DRC checking rule but an ERC/LVS checking one !
27420 0 GRHV4: BHCUS are allowed only inside RXHV shape sized by 0.01 !
27428 0 GRHV4: BPCUS are allowed only inside RXHV shape sized by 0.01 !
27436 0 GRHV4: TECUS are allowed only inside RXHV shape sized by 0.01 !
27440 0 GRHV4: TFCUS are allowed only inside RXHV shape sized by 0.01 !
27444 0 GRHV4: NONIAGBF are allowed only inside RXHV shape sized by 0.01 !
27448 0 GRHV4: NONIAGBH are allowed only inside RXHV shape sized by 0.01 !
27452 0 GRHV4: NONIAGPH are allowed only inside RXHV shape sized by 0.01 !
27464 0 GRHV4: NONIAGTE are allowed only inside RXHV shape sized by 0.01 !
27468 0 GRHV4: NONIAGTF are allowed only inside RXHV shape sized by 0.01 !
27472 0 GRHV4: NONIAGSN are allowed only inside RXHV shape sized by 0.01 !
27476 0 GRHV4: NONIAGSP are allowed only inside RXHV shape sized by 0.01 !
27480 0 GRHV4: NONIAGTG are allowed only inside RXHV shape sized by 0.01 !
27484 0 GRHV4: NONIAGWX are allowed only inside RXHV shape sized by 0.01 !
27530 0 GRHV4: (BHCUS not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27536 0 GRHV4: (BPCUS not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27539 0 GRHV4: (TECUS not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27542 0 GRHV4: (TFCUS not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27545 0 GRHV4: (NONIAGBF not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or  [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27548 0 GRHV4: (NONIAGBH not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27551 0 GRHV4: (NONIAGPH not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27554 0 GRHV4: (NONIAGTE not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27557 0 GRHV4: (NONIAGTF not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27560 0 GRHV4: (NONIAGWX not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27563 0 GRHV4: (NONIAGWY not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27566 0 GRHV4: (NONIAGSN not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27569 0 GRHV4: (NONIAGSP not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27572 0 GRHV4: (NONIAGTG not over RXHV) must be covered by ( [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27612 0 GRHV4: (BFCUS not over RXHV) must be covered by ( [(DN touching(text on levelRXHV2 = +120)) sized by 8.5) - (DN sized by -0.5)] or [(RXHV_IBM touching(text on level RXHVIBM = NFETI120M_REV_1.0 PFET120M_REV_1.0 ESD120_REV_1.0) sized by 13.0] or [RXHV_IBM touching (text on level RXHV_IBM {PFET12MH_REV_1.0 sized by 7.5 )] or [RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0 sized by 0.3 )])
27647 0 GRHV4a: SN is only allowed inside {((RXHV sized by +0.2) sized by -0.2), (N+RX hole in RXHV) sized by 1.4um,(RXHV_IBM, RXHV_IBM touching (text on level RXHV_IBM {NFETI120M_REV_1.0 PFET120M_REV_1.0 PFET12MH_REV_1.0}))
27669 0 GRHV4b: (SP, DP) only allowed inside ((RXHV RXHV_IBM) sized by +0.2) sized by -0.2)or in RXHV_IBM touching (text on level RXHV_IBM {NFET12MH_REV_1.0})
27675 0 GRHV5: (N+ RX hole overlapping RXHV) to ((RX not touching RXHV) over DN) space >= 7.6 um.
27676 0 GRHV5: (N+ RX hole overlapping RXHV) to ((RX not touching RXHV) over DN) space >= 7.6 um.
27695 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27696 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27697 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27698 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27699 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27700 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27701 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27702 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27703 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27704 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27705 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27706 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27707 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27708 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27709 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27710 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27711 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27712 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27713 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27714 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
27715 0 GRHV6: Space between n+Rx Holes belonging to elements with different RxHV Texts >= 10.2
28197 0 GRNFET20HS_REV: NFET20HS Revision must be == 4.0 !
28207 0 GRNFET20HS_L: NFET20HS Channel Length (SN) >= 0.7
28208 0 GRNFET20HS_L: NFET20HS Channel Length (SN) >= 0.7
28217 0 GRNFET20HS_W: NFET20HS Channel Width >= 5.0
28218 0 GRNFET20HS_W: NFET20HS Channel Width >= 5.0
28223 0 GRNFET20HS_X1: SD-RX enclosure of CA == 0.16
28236 0 GRNFET20HS_X2: PC to SD-RX spacing == 0.26
28244 0 GRNFET20HS_X3: SD-RX to CHANNEL-RX spacing == 0.26
28250 0 GRNFET20HS_X4: SN enclosure of SD-RX == 1.53
28259 0 GRNFET20HS_X5: SD-RX to DP spacing  == 1.03
28268 0 GRNFET20HS_X6: DP extension of SP  == 0.45
28278 0 GRNFET20HS_X7: PC overlap of DP  == 0.45
28285 0 GRNFET20HS_X8: PC Width (outside) == 1.47
28293 0 GRNFET20HS_X9: SD-RX to BULK spacing == 2.42
28306 0 GRNFET20HS_X10: DP width == 0.70
28319 0 GRNFET20HS_X11: SP width == 0.70
28326 0 GRNFET20HS_X12: PC to BULK CA spacing  == 0.20
28330 0 GRNFET20HS_X13: BP enclosure of BULK CA == 0.34
28335 0 GRNFET20HS_Y1: SN enclosure of SD-RX == 1.46
28349 0 GRNFET20HS_Y2: SD-RX to BULK spacing == 2.41
28366 0 GRNFET20HS_Y3: PC extension of CHANNEL-RX == 1.86
28375 0 GRNFET20HS_Y4: PC extension of CHANNEL-RX == 0.40
28381 0 GRNFET20HS_Y5: SP to CHANNEL-RX spacing == 0.0
28411 0 GRNFET20HS_Y6: PC 45-Deg Corner == 0.42
28445 0 GRNFET20HS_Y7: SN 45-Deg Corner == 0.60
28451 0 GRNFET20HS_Y8: SN Minimum channel-RX enclosure of BULK-CA >= 1.15
28455 0 GRNFET20HS_Y9: BULK-CA spacing == 4.80
28458 0 GRNFET20MH_REV: NFET20MH Revision must be == 1.0 !
28478 0 GRNFET20MH_L: NFET20MH Channel Length (SP) >= 0.4
28479 0 GRNFET20MH_L: NFET20MH Channel Length (SP) >= 0.4
28484 0 GRNFET20MH_W2: NFET20MH Channel Width >= 2.5
28485 0 GRNFET20MH_W2: NFET20MH Channel Width >= 2.5
28496 0 GRNFET20MH_X1: NG to DRAIN-CA spacing == 0.2.
28504 0 GRNFET20MH_X2: PC to DRAIN-CA spacing == 0.6.
28514 0 GRNFET20MH_X3: NG width == 1.14.
28529 0 GRNFET20MH_X4: SN enclosure of DRAIN-CA == 1.84.
28540 0 GRNFET20MH_X5: SP to SN spacing == 0.30.
28558 0 GRNFET20MH_X6: SP width == 0.70.
28568 0 GRNFET20MH_X7: SP to BULK-RX spacing == 0.10.
28584 0 GRNFET20MH_Y1: PC to DRAIN-RX spacing == 0.50.
28595 0 GRNFET20MH_Y2: NG extension of DRAIN-RX  == 0.76.
28607 0 GRNFET20MH_Y3: PC to DRAIN-RX spacing == 1.84.
28622 0 GRNFET20MH_Y4: PC width of gate connection == 1.94.
28639 0 GRNFET20MH_Y5: BULK-RX to DRAIN-RX spacing == 2.94.
28651 0 GRNFET20MH_Y6: SP width == 0.70.
28686 0 GRNFET20MH_Y7: PC 45-Deg Corner == 0.58
28717 0 GRNFET20MH_Y8: SN 45-Deg Corner == 0.80
28744 0 GRNFET20MH_Y9: PC 45-Deg Corner == 0.13
28761 0 GRNFET20MH_Y10: SP extension of SOURCE-RX == 0.98
28799 0 GRNFET20MH_Y11: SP 45-Deg Corner == 0.44
28813 0 GRNFET20MH_Y12: TG enclosure of RX == 0.50
28816 0 GRNFET50HS_REV: NFET50HS Revision must be == 4.0 !
28826 0 GRNFET50HS_L: NFET50HS Channel Length (SN space) >= 1.3
28827 0 GRNFET50HS_L: NFET50HS Channel Length (SN space) >= 1.3
28836 0 GRNFET50HS_W: NFET50HS Channel Width >= 5.0
28837 0 GRNFET50HS_W: NFET50HS Channel Width >= 5.0
28842 0 GRNFET50HS_X1: SD-RX enclosure of CA == 1.10
28854 0 GRNFET50HS_X2: PC to SD-RX spacing == 1.38
28865 0 GRNFET50HS_X3: SD-RX to CHANNEL-RX spacing == 2.75
28871 0 GRNFET50HS_X4: SN enclosure of SD-RX == 3.95
28880 0 GRNFET50HS_X5: SD-RX to DP spacing  == 3.35
28889 0 GRNFET50HS_X6: DP extension of SP  == 0.85
28909 0 GRNFET50HS_X7: PC overlap of DP  == 0.75
28916 0 GRNFET50HS_X8: PC Width (outside) == 3.95
28924 0 GRNFET50HS_X9: SD-RX to BULK spacing == 7.15
28937 0 GRNFET50HS_X10: DP width == 0.70
28950 0 GRNFET50HS_X11: SP width == 0.70
28957 0 GRNFET50HS_X12: PC to BULK CA spacing  == 0.20
28961 0 GRNFET50HS_X13: BP enclosure of BULK CA == 0.34
28973 0 GRNFET50HS_Y1: SN enclosure of SD-RX == 5.15
28987 0 GRNFET50HS_Y2: SD-RX to BULK spacing == 8.35
29006 0 GRNFET50HS_Y3: PC extension of CHANNEL-RX == 5.06
29016 0 GRNFET50HS_Y4: PC extension of CHANNEL-RX == 0.40
29021 0 GRNFET50HS_Y5: SP to CHANNEL-RX spacing == 0.0
29058 0 GRNFET50HS_Y6: PC 45-Deg Corner == 0.74
29098 0 GRNFET50HS_Y7: SN 45-Deg Corner == 1.54
29104 0 GRNFET50HS_Y8: SN Minimum channel-RX enclosure of BULK-CA >= 1.15
29108 0 GRNFET50HS_Y9: BULK-CA spacing == 4.80
29111 0 GRNFETI20H_REV: NFET20IH Revision must be == 4.0 !
29131 0 GRNFETI20H_L: NFETI20H Channel Length (DP) >= 0.5
29132 0 GRNFETI20H_L: NFETI20H Channel Length (DP) >= 0.5
29137 0 GRNFETI20H_W2: NFETI20H Channel Width >= 2.5
29138 0 GRNFETI20H_W2: NFETI20H Channel Width >= 2.5
29148 0 GRNFETI20H_R1: NFETI20H bulk and source must be connected with M1
29161 0 GRNFETI20H_X1: SOURCE-RX to BULK-RX spacing == 0.28
29167 0 GRNFETI20H_X2: SOURCE-RX extension of PC  == 0.60
29183 0 GRNFETI20H_X3: SOURCE-RX extension of DP  == 1.80
29199 0 GRNFETI20H_X4: PC extension of SOURCE-RX == 0.3
29207 0 GRNFETI20H_X6: SOURCE-RX to BULK-RX spacing == 0.5
29217 0 GRNFETI20H_X7: SP extension to BULK-RX spacing == 0.48
29228 0 GRNFETI20H_X8: SN enclosure of CA == 0.25
29246 0 GRNFETI20H_X9: DRAIN-RX enclosure of CA == 0.24
29254 0 GRNFETI20H_X10: DRAIN-RX enclosure of CA == 0.24
29273 0 GRNFETI20H_X11: minimun DN enclosure of RX == 2.68
29278 0 GRNFETI20H_X12: minimun SN extension of RX == 0.54
29297 0 GRNFETI20H_X13: DP enclosure of SP == 0.20
29311 0 GRNFETI20H_Y1: PC to BULK-RX spacing == 0.44
29324 0 GRNFETI20H_Y2: DP enclosure of BULK-RX == 2.5
29334 0 GRNFETI20H_Y3: DRAIN-RX to BULK-RX spacing == 4.7
29339 0 GRNFETI20H_Y4: PC width of gate connection == 3.98
29374 0 GRNFETI20H_Y5: PC Corner == 1.3
29403 0 GRNFETI20H_Y6: DP Corner 0.6
29434 0 GRNFETI20H_Y7: PC Corner == 0.2
29439 0 GRNFETI20H_Y8: minimum DN enclosure of DP  >= 3.40
29454 0 GRNFETI20H_Y9: SP enclosure of BULK-RX == 1.0
29472 0 GRNFETI20H_Y10: SP overlap of SOURCE-RX  == 0.1
29480 0 INFO NFETI20H_modeled: RXHV oversize  == 3.36
29483 0 GRNFETI20T_REV: NFET20IT Revision must be == 4.0 !
29501 0 GRNFETI20T_L: NFETI20T Channel Length (not BFCUS) >= 0.2
29502 0 GRNFETI20T_L: NFETI20T Channel Length (not BFCUS) >= 0.2
29509 0 GRNFETI20T_W2: NFETI20T Channel Width >= 2.5
29510 0 GRNFETI20T_W2: NFETI20T Channel Width >= 2.5
29523 0 GRNFETI20T_R1: NFETI20T bulk and source must be connected with M1
29536 0 GRNFETI20T_X1: SOURCE-RX to BULK-RX spacing == 0.28
29550 0 GRNFETI20T_X2: SOURCE-RX extension of PC  == 0.56
29569 0 GRNFETI20T_X3: SOURCE-RX overlap of BFCUS == 1.6 
29574 0 GRNFETI20T_X4: PC extension of SOURCE-RX == 0.5
29589 0 GRNFETI20T_X6: DRAIN-RX to SOURCE-RX  spacing == 0.7
29599 0 GRNFETI20T_X8: SN enclosure of CA == 0.25
29607 0 GRNFETI20T_X9: DRAIN-RX enclosure of CA == 0.24
29615 0 GRNFETI20T_X10: DRAIN-RX enclosure of CA == 0.24
29633 0 GRNFETI20T_X11: minimun DN enclosure of RX == 2.68
29637 0 GRNFETI20T_X12: minimun SN extension of RX == 0.54
29650 0 GRNFETI20T_X13: DP extension of stretched BFCUS edge == 0.3
29666 0 GRNFETI20T_X14:  BFCUS to DRAIN-RX spacing == 0.10.
29680 0 GRNFETI20T_Y1: PC to BULK-RX spacing == 0.44
29694 0 GRNFETI20T_Y2: BFCUS to BULK-RX == 1
29704 0 GRNFETI20T_Y3: DP to BULK-RX == 1
29715 0 GRNFETI20T_Y4: DRAIN-RX to BULK-RX spacing == 4.9
29720 0 GRNFETI20T_Y5: PC width of gate connection == 4.18
29746 0 GRNFETI20T_Y6: DP width == 2.0
29787 0 GRNFETI20T_Y7: PC Corner == 1.3
29811 0 GRNFETI20T_Y8: DP Corner == 0.6
29832 0 GRNFETI20T_Y9: BFCUS Corner == 0.6
29853 0 GRNFETI20T_Y10: PC Corner == 0.24
29858 0 GRNFETI20T_Y11: minimum DN enclosure of DP  >= 3.40
29866 0 INFO NFETI20T_modeled: RXHV oversize  == 3.36
29869 0 GRNFETI25M_REV: NFETI25M Revision must be == 4.0 !
29887 0 GRNFETI25M_L: NFETI25M Channel Length (SP) >= 0.4
29888 0 GRNFETI25M_L: NFETI25M Channel Length (SP) >= 0.4
29895 0 GRNFETI25M_W2: NFETI25M Channel Width >= 2.5
29896 0 GRNFETI25M_W2: NFETI25M Channel Width >= 2.5
29910 0 GRNFETI25M_X1: SOURCE-RX to BULK-RX spacing == 0.28
29923 0 GRNFETI25M_X2: SOURCE-RX extension of BULK-RX  == 0.56
29940 0 GRNFETI25M_X3: SOURCE-RX overlap of SP == 1.6 
29951 0 GRNFETI25M_X4: PC extension of SOURCE-RX == 0.8
29964 0 GRNFETI25M_X6: DRAIN-RX to SOURCE-RX  spacing == 1.0
29974 0 GRNFETI25M_X8: SN enclosure of CA == 0.25
29982 0 GRNFETI25M_X9: DRAIN-RX enclosure of CA == 0.24
29990 0 GRNFETI25M_X10: DRAIN-RX enclosure of CA == 0.24
30004 0 GRNFETI25M_X11: minimun DN enclosure of RX == 2.68
30009 0 GRNFETI25M_X12: minimun SN extension of RX == 0.50
30023 0 GRNFETI25M_X13: DP extension of stretched SP edge == 0.3
30030 0 GRNFETI25M_Y1: PC to BULK-RX spacing == 0.44
30041 0 GRNFETI25M_Y2: SP enclodure of BULK-RX == 1
30053 0 GRNFETI25M_Y3: DP to BULK-RX == 1
30060 0 GRNFETI25M_Y4: DRAIN-RX to BULK-RX spacing == 5.2
30071 0 GRNFETI25M_Y5: PC width of gate connection == 4.48
30097 0 GRNFETI25M_Y6: DP width == 2.0
30138 0 GRNFETI25M_Y7: PC Corner == 1.3
30162 0 GRNFETI25M_Y8: DP Corner == 0.8
30187 0 GRNFETI25M_Y9: SP Corner == 0.6
30213 0 GRNFETI25M_Y10: PC Corner == 0.24
30218 0 GRNFETI25M_Y11: minimum DN enclosure of DP  >= 3.63
30226 0 INFO NFETI25M_modeled: RXHV oversize  == 3.36
30229 0 GRNFETI50H_REV: NFETI50H Revision must be == 6.0 !
30247 0 GRNFETI50H_L: NFETI50H Channel Length (DP) >= 0.5
30248 0 GRNFETI50H_L: NFETI50H Channel Length (DP) >= 0.5
30255 0 GRNFETI50H_W2: NFETI50H Channel Width >= 2.5
30256 0 GRNFETI50H_W2: NFETI50H Channel Width >= 2.5
30266 0 GRNFETI50H_R1: NFETI50H bulk and source must be connected with M1
30280 0 GRNFETI50H_X1: SOURCE-RX to BULK-RX spacing == 0.28
30292 0 GRNFETI50H_X2: SOURCE-RX extension of PC  == 0.60
30308 0 GRNFETI50H_X3: SOURCE-RX extension of DP  == 2.00
30318 0 GRNFETI50H_X4: PC extension of SOURCE-RX == 2.46
30326 0 GRNFETI50H_X6: SOURCE-RX to BULK-RX spacing == 4.1
30336 0 GRNFETI50H_X7: SP extension to BULK-RX spacing == 0.58
30356 0 GRNFETI50H_X8: SN enclosure of CA == 0.35
30374 0 GRNFETI50H_X9: DRAIN-RX enclosure of CA == 0.55
30382 0 GRNFETI50H_X10: DRAIN-RX enclosure of CA == 0.24
30396 0 GRNFETI50H_X11: minimun DN enclosure of RX == 1.16
30401 0 GRNFETI50H_X12: minimun SN extension of RX == 0.25
30419 0 GRNFETI50H_X13: DP enclosure of SP == 0.20
30433 0 GRNFETI50H_Y1: PC to BULK-RX spacing == 0.44
30446 0 GRNFETI50H_Y2: DP enclosure of BULK-RX == 2.5
30454 0 GRNFETI50H_Y3: DRAIN-RX to BULK-RX spacing == 11.85
30459 0 GRNFETI50H_Y4: PC width of gate connection == 9.17
30494 0 GRNFETI50H_Y5: PC Corner == 1.3
30523 0 GRNFETI50H_Y6: DP Corner 0.5
30554 0 GRNFETI50H_Y7: PC Corner == 0.2
30558 0 GRNFETI50H_Y8: minimum DN enclosure of DP  >= 3.400
30573 0 GRNFETI50H_Y9: SP enclosure of BULK-RX == 1.0
30591 0 GRNFETI50H_Y10: SP overlap of SOURCE-RX  == 0.1
30599 0 INFO NFETI50H_modeled: RXHV oversize  == 6.54
30602 0 GRNFETI50M_REV: NFETI50M Revision must be == 5.0 !
30620 0 GRNFETI50M_L: NFETI50M Channel Length (SP) >= 0.4
30621 0 GRNFETI50M_L: NFETI50M Channel Length (SP) >= 0.4
30628 0 GRNFETI50M_W2: NFETI50M Channel Width >= 2.5
30629 0 GRNFETI50M_W2: NFETI50M Channel Width >= 2.5
30642 0 GRNFETI50M_R1: NFETI50M bulk and source must be connected with M1
30654 0 GRNFETI50M_X1: SOURCE-RX to BULK-RX spacing == 0.28
30666 0 GRNFETI50M_X2: SOURCE-RX extension of BULK-RX  == 0.56
30681 0 GRNFETI50M_X3: SOURCE-RX overlap of SP == 1.9 
30686 0 GRNFETI50M_X4: PC extension of SOURCE-RX == 2.85
30699 0 GRNFETI50M_X6: DRAIN-RX to SOURCE-RX  spacing == 3.8
30715 0 GRNFETI50M_X8: SN enclosure of CA == 0.35
30723 0 GRNFETI50M_X9: DRAIN-RX enclosure of CA == 0.55
30731 0 GRNFETI50M_X10: DRAIN-RX enclosure of CA == 0.24
30745 0 GRNFETI50M_X11: minimun DN enclosure of RX >= 0.91
30761 0 GRNFETI50M_X12: PC enclosure of DP == 4.75
30775 0 GRNFETI50M_Y1: PC to BULK-RX spacing == 0.44
30789 0 GRNFETI50M_Y2: SP enclodure of BULK-RX == 1.5
30798 0 GRNFETI50M_Y3: DRAIN-RX to BULK-RX spacing == 11.72
30803 0 GRNFETI50M_Y4: PC width of gate connection == 10.25
30838 0 GRNFETI50M_Y5: PC Corner == 1.3
30863 0 GRNFETI50M_Y6: SP Corner == 0.6
30894 0 GRNFETI50M_Y7: PC Corner == 0.2
30906 0 GRNFETI50M_Y8: DP to BULK-RX == 1.5
30925 0 GRNFETI50M_Y9: DP width == 1.5
30933 0 INFO NFETI50M_modeled: RXHV oversize  == 6.00
30936 0 GRNFETI50T_REV: NFETI50T Revision must be == 5.0 !
30954 0 GRNFETI50T_L: NFETI50T Channel Length (not BFCUS) >= 0.2
30955 0 GRNFETI50T_L: NFETI50T Channel Length (not BFCUS) >= 0.2
30962 0 GRNFETI50T_W2: NFETI50T Channel Width >= 2.5
30963 0 GRNFETI50T_W2: NFETI50T Channel Width >= 2.5
30976 0 GRNFETI50T_R1: NFETI50T bulk and source must be connected with M1
30987 0 GRNFETI50T_X1: SOURCE-RX to BULK-RX spacing == 0.28
30999 0 GRNFETI50T_X2: SOURCE-RX extension of PC  == 0.56
31016 0 GRNFETI50T_X3: SOURCE-RX overlap of BFCUS == 1.7 
31021 0 GRNFETI50T_X4: PC extension of SOURCE-RX == 2.63
31036 0 GRNFETI50T_X6: DRAIN-RX to SOURCE-RX  spacing == 4.05
31052 0 GRNFETI50T_X8: SN enclosure of CA == 0.35
31060 0 GRNFETI50T_X9: DRAIN-RX enclosure of CA == 0.55
31076 0 GRNFETI50T_X10:  BFCUS to DRAIN-RX spacing == 0.30.
31084 0 GRNFETI50T_X11: DRAIN-RX enclosure of CA == 0.24
31098 0 GRNFETI50T_Y1: PC to BULK-RX spacing == 0.44
31112 0 GRNFETI50T_Y2: BFCUS to BULK-RX == 1.5
31122 0 GRNFETI50T_Y3: DRAIN-RX to BULK-RX spacing == 11.85
31127 0 GRNFETI50T_Y4: PC width of gate connection == 9.91
31162 0 GRNFETI50T_Y5: PC Corner == 1.3
31183 0 GRNFETI50T_Y6: BFCUS Corner == 0.6
31214 0 GRNFETI50T_Y7: PC Corner == 0.2
31226 0 GRNFETI50T_Y8: DP to BULK-RX == 1.5
31252 0 GRNFETI50T_Y9: DP width == 2.3
31280 0 GRNFETI50T_Y10: DP Corner == 0.6
31287 0 INFO NFETI50T_modeled: RXHV oversize  == 6.05
31290 0 GRPFET20H_REV: PFET20H Revision must be == 4.0 !
31308 0 GRPFET20H_L: PFET20H Channel Length (SN) >= 0.6
31309 0 GRPFET20H_L: PFET20H Channel Length (SN) >= 0.6
31316 0 GRPFET20H_W2: PFET20H Channel Width >= 2.5
31317 0 GRPFET20H_W2: PFET20H Channel Width >= 2.5
31323 0 GRPFET20H_X1: PC to DRAIN-RX spacing == 0.2
31335 0 GRPFET20H_X2: DP enclosure of DRAIN-RX == 0.90
31346 0 GRPFET20H_X3: DRAIN-RX to SOURCE-RX spacing (field plate) == 0.50
31358 0 GRPFET20H_X4: SOURCE-RX extention of SN == 0.8
31369 0 GRPFET20H_X8: minimum SN extention of RX >= 0.24
31385 0 GRPFET20H_X5: minimun SN extension of RX == 0.8
31395 0 GRPFET20H_X6: minimun DN enclosure of SN == 1.21
31402 0 GRPFET20H_X9: DRAIN-RX enclosure of CA == 0.2
31409 0 GRPFET20H_Y1: PC to DRAIN-RX spacing == 0.5
31422 0 GRPFET20H_Y2: DP enclosure of DRAIN-RX == 2
31436 0 GRPFET20H_Y3: PC Width of gate connection == 2
31447 0 GRPFET20H_Y4: DRAIN-RX to BULK-RX spacing == 3.26
31472 0 GRPFET20H_Y5: PC Corner == 1
31493 0 GRPFET20H_Y6: DP Corner == 0.5
31515 0 GRPFET20H_Y7: SN extention of SOURCE-RX == 1.2
31542 0 GRPFET20H_Y8: SN Corner == 0.5
31556 0 GRPFET20H_Y10: SN extention of RX== 0.24
31568 0 GRPFET20H_Y11: BP enclosure of PC == 0.14
31576 0 INFO PFET20H_modeled: RXHV oversize  == 2.61
31579 0 GRPFET20HS_REV: PFET20HS Revision must be == 4.0 !
31598 0 GRPFET20HS_L: PFET20HS Channel Length (DN NOT UNDER DP) >= 2.0
31599 0 GRPFET20HS_L: PFET20HS Channel Length (DN NOT UNDER DP) >= 2.0
31605 0 GRPFET20HS_W: PFET20HS Channel Width >= 5.0
31606 0 GRPFET20HS_W: PFET20HS Channel Width >= 5.0
31613 0 GRPFET20HS_X1: SD-RX enclosure of CA == 0.2
31619 0 GRPFET20HS_X2: PC to SD-RX spacing == 0.25
31632 0 GRPFET20HS_X3: SD-RX to SOURCE-RX spacing (field plate) == 0.5
31645 0 GRPFET20HS_X4: DP to enclosure of SD-RX == 0.8
31659 0 GRPFET20HS_X5: DP to SN spacing == 0.25
31673 0 GRPFET20HS_X6: DP enclosure of SD-RX == 0.70
31682 0 GRPFET20HS_X7: PC width (outside) == 0.75
31691 0 GRPFET20HS_X8: SD-RX to BULK-RX spacing == 4.1
31701 0 GRPFET20HS_X9: minimum SN extension of RX >= 0.9
31715 0 GRPFET20HS_X10: SP enclosure of SD-RX == 0.05
31722 0 GRPFET20HS_Y1: PC to SD-RX spacing == 0.5
31728 0 GRPFET20HS_Y2: DP enclosure of SD-RX == 2
31736 0 GRPFET20HS_Y4: BULK-RX to SD-RX spacing == 5.4
31762 0 GRPFET20HS_Y3: PC width of gate connection == 2
31780 0 GRPFET20HS_Y5: PC extension of CHANNEL-RX == 1.5
31795 0 GRPFET20HS_Y6: SN to CHANNEL-RX spacing == 0.4
31824 0 GRPFET20HS_Y7: PC Corner == 1
31857 0 GRPFET20HS_Y8: DP Corner 0.5
31865 0 INFO PFET20HS_modeled: RXHV oversize  == 1.35
31868 0 GRPFET20T_REV: PFET20T Revision must be == 3.0 !
31886 0 GRPFET20T_L: PFET20T Channel Length (NW) >= 0.2
31887 0 GRPFET20T_L: PFET20T Channel Length (NW) >= 0.2
31894 0 GRPFET20T_W2: PFET20T Channel Width >= 2.5
31895 0 GRPFET20T_W2: PFET20T Channel Width >= 2.5
31901 0 GRPFET20T_X1: PC to DRAIN-RX spacing == 0.2
31910 0 GRPFET20T_X2: DP enclosure of DRAIN-RX == 1.15
31921 0 GRPFET20T_X3: DRAIN-RX to SOURCE-RX spacing (field plate) == 0.45
31934 0 GRPFET20T_X4: SOURCE-RX extention of nw == 0.7
31945 0 GRPFET20T_X8: minimum NW extention of RX >= 0.24
31961 0 GRPFET20T_X5: minimun SN extension of RX == 0.8
31971 0 GRPFET20T_X6: minimun DN enclosure of SN == 1.51
31978 0 GRPFET20T_X9: DRAIN-RX enclosure of CA == 0.2
31985 0 GRPFET20T_Y1: PC to DRAIN-RX spacing == 0.5
31998 0 GRPFET20T_Y2: DP enclosure of DRAIN-RX == 2
32012 0 GRPFET20T_Y3: PC width gate connection == 2
32023 0 GRPFET20T_Y4: DRAIN-RX to BULK-RX spacing == 3.26
32050 0 GRPFET20T_Y5: PC Corner == 1
32076 0 GRPFET20T_Y6: DP Corner == 0.5
32092 0 GRPFET20T_Y7: NW extention of SOURCE-RX == 1.2
32121 0 GRPFET20T_Y8: NW Corner == 0.5
32135 0 GRPFET20T_Y10: NW extention of RX== 0.45
32147 0 GRPFET20T_Y11: BP enclosure of PC == 0.14
32155 0 INFO PFET20T_modeled: RXHV oversize  == 2.91
32158 0 GRPFET25M_REV: PFET25M Revision must be == 4.0 !
32176 0 GRPFET25M_L: PFET25M Channel Length (SN) >= 0.6
32177 0 GRPFET25M_L: PFET25M Channel Length (SN) >= 0.6
32184 0 GRPFET25M_W2: PFET25M Channel Width >= 2.5
32185 0 GRPFET25M_W2: PFET25M Channel Width >= 2.5
32191 0 GRPFET25M_X1: PC to DRAIN-RX spacing == 0.2
32203 0 GRPFET25M_X2: DP enclosure of DRAIN-RX == 0.80
32214 0 GRPFET25M_X3: DRAIN-RX to SOURCE-RX spacing (field plate) == 0.50
32226 0 GRPFET25M_X4: SOURCE-RX extention of SN == 0.7
32237 0 GRPFET25M_X8: minimum SN extention of RX >= 0.24
32248 0 GRPFET25M_X5: minimun SN extension of RX>== 0.8
32258 0 GRPFET25M_X6: minimun DN enclosure of SN >= 1.21
32265 0 GRPFET25M_X9: DRAIN-RX enclosure of CA == 0.2
32272 0 GRPFET25M_Y1: PC to DRAIN-RX spacing == 0.5
32285 0 GRPFET25M_Y2: DP enclosure of DRAIN-RX == 2
32299 0 GRPFET25M_Y3: DRAIN-RX to BULK-RX spacing == 2
32312 0 GRPFET25M_Y4: DRAIN-RX to BULK-RX spacing == 3.26
32339 0 GRPFET25M_Y5: PC Corner == 1
32365 0 GRPFET25M_Y6: DP Corner == 0.5
32381 0 GRPFET25M_Y7: SN extention of SOURCE-RX == 1.2
32408 0 GRPFET25M_Y8: SN Corner == 0.5
32422 0 GRPFET25M_Y10: SN extention of RX== 0.24
32431 0 GRPFET25M_Y11: BP enclosure of PC == 0.14
32439 0 INFO PFET25M_modeled: RXHV oversize  == 2.61
32442 0 GRPFET50H_REV: PFET50H Revision must be == 4.0 !
32460 0 GRPFET50H_L: PFET50H Channel Length (SN) >= 0.6
32461 0 GRPFET50H_L: PFET50H Channel Length (SN) >= 0.6
32468 0 GRPFET50H_W2: PFET50H Channel Width >= 2.5
32469 0 GRPFET50H_W2: PFET50H Channel Width >= 2.5
32475 0 GRPFET50H_X1: PC to DRAIN-RX spacing == 0.75
32487 0 GRPFET50H_X2: DP enclosure of DRAIN-RX == 3.30
32498 0 GRPFET50H_X3: DRAIN-RX to SOURCE-RX spacing (field plate) == 3.00
32510 0 GRPFET50H_X4: SOURCE-RX extention of SN == 0.7
32521 0 GRPFET50H_X8: minimum SN extention of RX >= 0.24
32532 0 GRPFET50H_X5: minimun SN extension of RX>== 0.8
32542 0 GRPFET50H_X6: minimun DN enclosure of SN >= 1.21
32549 0 GRPFET50H_X9: DRAIN-RX enclosure of CA == 0.2
32556 0 GRPFET50H_Y1: PC to DRAIN-RX spacing == 1.2
32569 0 GRPFET50H_Y2: DP enclosure of DRAIN-RX == 5
32583 0 GRPFET50H_Y3: DRAIN-RX to BULK-RX spacing == 5
32596 0 GRPFET50H_Y4: DRAIN-RX to BULK-RX spacing == 6.96
32623 0 GRPFET50H_Y5: PC Corner == 2
32649 0 GRPFET50H_Y6: DP Corner == 1.3
32665 0 GRPFET50H_Y7: SN extention of SOURCE-RX == 1.2
32692 0 GRPFET50H_Y8: SN Corner == 0.5
32706 0 GRPFET50H_Y10: SN extention of RX== 0.24
32715 0 GRPFET50H_Y11: BP enclosure of PC == 0.14
32723 0 INFO PFET50H_modeled: RXHV oversize  == 2.61
32726 0 GRPFET50HS_REV: PFET50HS Revision must be == 4.0 !
32745 0 GRPFET50HS_L: PFET50HS Channel Length (DN NOT UNDER DP) >= 3.0
32746 0 GRPFET50HS_L: PFET50HS Channel Length (DN NOT UNDER DP) >= 3.0
32752 0 GRPFET50HS_W: PFET50HS Channel Width >= 5.0
32753 0 GRPFET50HS_W: PFET50HS Channel Width >= 5.0
32760 0 GRPFET50HS_X1: SD-RX enclosure of CA == 0.2
32766 0 GRPFET50HS_X2: PC to SD-RX spacing == 0.75
32778 0 GRPFET50HS_X3: SD-RX to SOURCE-RX spacing (field plate) == 2.75
32790 0 GRPFET50HS_X4: DP to enclosure of SD-RX == 3.05
32804 0 GRPFET50HS_X5: DP to SN spacing == 0.75
32818 0 GRPFET50HS_X6: DP enclosure of SD-RX == 2.95
32827 0 GRPFET50HS_X7: PC width (outside) == 2.50
32836 0 GRPFET50HS_X8: SD-RX to BULK-RX spacing == 6.35
32846 0 GRPFET50HS_X9: Minimum SN extension of RX >= 0.9
32853 0 GRPFET50HS_Y1: PC to SD-RX spacing == 1.2
32859 0 GRPFET50HS_Y2: DP enclosure of SD-RX == 5
32867 0 GRPFET50HS_Y4: BULK-RX to SD-RX spacing == 8.4
32893 0 GRPFET50HS_Y3: PC width of gate connection == 5
32911 0 GRPFET50HS_Y5: PC extension of CHANNEL-RX == 4.2
32926 0 GRPFET50HS_Y6: SN to CHANNEL-RX spacing == 0.4
32955 0 GRPFET50HS_Y7: PC Corner == 2
32988 0 GRPFET50HS_Y8: DP Corner 1.3
32996 0 INFO PFET50HS_modeled: RXHV oversize  == 1.35
32999 0 GRPFET50M_REV: PFET50M Revision must be == 4.0 !
33017 0 GRPFET50M_L: PFET50M Channel Length (SN) >= 0.6
33018 0 GRPFET50M_L: PFET50M Channel Length (SN) >= 0.6
33032 0 GRPFET50M_W2: PFET50M Channel Width >= 2.5
33033 0 GRPFET50M_W2: PFET50M Channel Width >= 2.5
33039 0 GRPFET50M_X1: PC to DRAIN-RX spacing == 0.75
33051 0 GRPFET50M_X2: DP enclosure of DRAIN-RX == 3.30
33062 0 GRPFET50M_X3: DRAIN-RX to SOURCE-RX spacing (field plate) == 3.00
33074 0 GRPFET50M_X4: SOURCE-RX extention of SN == 0.7
33085 0 GRPFET50M_X8: minimum SN extention of RX >= 0.24
33096 0 GRPFET50M_X5: minimun SN extension of RX>== 0.8
33106 0 GRPFET50M_X6: minimun DN enclosure of SN >= 1.21
33113 0 GRPFET50M_X9: DRAIN-RX enclosure of CA == 0.2
33120 0 GRPFET50M_Y1: PC to DRAIN-RX spacing == 1.2
33133 0 GRPFET50M_Y2: DP enclosure of DRAIN-RX == 5
33147 0 GRPFET50M_Y3: DRAIN-RX to BULK-RX spacing == 5
33160 0 GRPFET50M_Y4: DRAIN-RX to BULK-RX spacing == 6.96
33187 0 GRPFET50M_Y5: PC Corner == 2
33213 0 GRPFET50M_Y6: DP Corner == 1.3
33229 0 GRPFET50M_Y7: SN extention of SOURCE-RX == 1.2
33256 0 GRPFET50M_Y8: SN Corner == 0.5
33270 0 GRPFET50M_Y10: SN extention of RX== 0.24
33279 0 GRPFET50M_Y11: BP enclosure of PC == 0.14
33287 0 INFO PFET50M_modeled: RXHV oversize  == 2.61
33290 0 GRPFET50T_REV: PFET50T Revision must be == 4.0 !
33308 0 GRPFET50T_L: PFET50T Channel Length (NW) >= 0.2
33309 0 GRPFET50T_L: PFET50T Channel Length (NW) >= 0.2
33323 0 GRPFET50T_W2: PFET50T Channel Width >= 2.5
33324 0 GRPFET50T_W2: PFET50T Channel Width >= 2.5
33330 0 GRPFET50T_X1: PC to DRAIN-RX spacing == 0.75
33342 0 GRPFET50T_X2: DP enclosure of DRAIN-RX == 3.70
33353 0 GRPFET50T_X3: DRAIN-RX to SOURCE-RX spacing (field plate) == 3.00
33365 0 GRPFET50T_X4: SOURCE-RX extention of nw == 0.7
33376 0 GRPFET50T_X8: minimum NW extention of RX >= 0.45
33392 0 GRPFET50T_X5: minimun SN extension of RX == 0.8
33402 0 GRPFET50T_X6: minimun DN enclosure of SN == 1.21
33409 0 GRPFET50T_X9: DRAIN-RX enclosure of CA == 0.2
33416 0 GRPFET50T_Y1: PC to DRAIN-RX spacing == 1.2
33429 0 GRPFET50T_Y2: DP enclosure of DRAIN-RX == 5
33443 0 GRPFET50T_Y3: DRAIN-RX to BULK-RX spacing == 5
33456 0 GRPFET50T_Y4: DRAIN-RX to BULK-RX spacing == 6.96
33483 0 GRPFET50T_Y5: PC Corner == 2
33509 0 GRPFET50T_Y6: DP Corner == 1.3
33525 0 GRPFET50T_Y7: NW extention of SOURCE-RX == 1.2
33553 0 GRPFET50T_Y8: NW Corner == 0.5
33567 0 GRPFET50T_Y10: NW extention of RX== 0.45
33579 0 GRPFET50T_Y11: BP enclosure of PC == 0.14
33587 0 INFO PFET50T_modeled: RXHV oversize  == 2.61
33590 0 GRHVNWRES_REV: HVNWRES Revision must be == 4.0 !
33592 0 GRHVNWRES_W: Minimum width >= 4.0um
33593 0 GRHVNWRES_L: Minimum HVNWRES length >= 20.0um
33594 0 GRHVNWRES_X1: Minimum CABAR to BPCUS spacing >=0.36um
33596 0 GRHVNWRES_Y1: Minimum SN enclosure of CABAR >= 0.7um.
33603 0 GRHVNWRES_Y2: RX ovlp CABAR ==0.2um.
33605 0 GRHVNWRES_Y3: Min OP enclosure SN >= 1.18um.
33607 0 GRHVNWRES_Y4: Minimum BPCUS enclosure of SN >= 1.18um.
33610 0 GRHVNWRES_Y5: Minimum RX to SN spacing >= 4.2um.
33616 0 GRHVNWRES_Y6: M1 spacing == 0.6um
33624 0 GRHVNWRES_R1: (M1 over (OP over HVNWRES))between OP holes is not allowed!
33627 0 GRHVNWRES_R2: (M2 over (OP over HVNWRES)) is not allowed!
33630 0 GRHVPWRES_REV: HVPWRES Revision must be == 4.0 !
33631 0 GRHVPWRES_W: Minimum width >= 4.0um.
33632 0 GRHVPWRES_L: Minimum length >= 4.0um.
33633 0 GRHVPWRES_X1: Minimum CABAR to BPCUS spacing >= 0.36um.
33635 0 GRHVPWRES_X2: Minimum BP enclosure of CABAR >= 0.36um.
33637 0 GRHVPWRES_Y1: SP enclosure of CABAR >=0.2um.
33644 0 GRHVPWRES_Y2: RX enclosure of CABAR == 0.2um.
33646 0 GRHVPWRES_Y3: OP enclosure of SP >= 1.68um.
33648 0 GRHVPWRES_Y4: BPCUS enclosure of SP >= 1.68um.
33655 0 GRHVPWRES_Y5: DP enclosure of SP == 1.0um.
33656 0 GRHVPWRES_Y6: NW to DP space >= 1.0um.
33661 0 GRHVPWRES_Y8: M1 to M1 space == 0.6um.
33672 0 GRHVPWRES_R1: (M1 over (OP over HVPWRES)) between OP holes is not allowed!
33676 0 GRHVPWRES_R2: (M2 over (OP over HVPWRES)) is not allowed!
33694 0 GRHVPWRES_Y7: NW enclosure of RX == 0.45
33697 0 GRPJFET_REV: PJFET Revision must be == 2.0 !
33699 0 GRPJFET_W: Minimum DP width >= 10.5
33704 0 GRPJFET_X1: DP to SN spacing == 1.5um
33711 0 GRPJFET_X2: DP enclosure of SP==2.05um
33716 0 GRPJFET_X3: SP width ==1um
33721 0 GRPJFET_X4: SP to SN spacing == 2.05um
33726 0 GRPJFET_X5: SN width == 2.5um
33733 0 GRPJFET_X6: SN enclosure of n+RX == 0.5um
33740 0 GRPJFET_X7: SP enclosure of RX == 0.2um.
33750 0 GRPJFET_Y1: n+RX spacing == 9.4
33752 0 GRPJFET_Y2: Minimum DP enclosure of n+RX >=4.95um.
33759 0 INFO PJFET_modeled: modeled area == 1.6um.
33762 0 GRVPNP_REV: VPNP Revision must be == 1.0 !
33763 0 GRVPNP_R1: The layout of VPNP is fixed and must not be changed!
33765 0 GRVPNP_A1: AREA == 122.04
33767 0 GRVPNP_P1: EMITTER-RX perimeter == 95.8um
33769 0 GRVPNP_P2: EMITTER-SP perimeter == 97.4um
33771 0 GRVPNP_P3: EMITTER-DP perimeter == 115um
33776 0 GRVPNP_P4: BASE-SN hole perimeter == 127um
33781 0 GRVPNP_P5: BASE-RX hole perimeter == 131um
33788 0 INFO VPNP_modeled: Oversize vpnp == 1.6um
33791 0 GRVNPN_REV: VNPN Revision must be == 2.0 !
33792 0 GRVNPN_R1: The layout of VNPN is fixed and must not be changed!
33794 0 GRVNPN_A1: AREA == 1.0816
33796 0 GRVNPN_P1: EMITTER-RX perimeter == 4.16um
33800 0 GRVNPN_P2: Base-RX hole perimeter == 11.2um
33802 0 GRVNPN_P3: Base-RX outer perimeter == 16.0um
33804 0 GRVNPN_P4: Base-DP perimeter == 26.8um
33806 0 GRVNPN_P5: COLLECTOR-SN hole perimeter/4 == 34.8um.
33810 0 GRVNPN_P6: COLLECTOR-RX hole perimeter/4 = 38.8
33815 0 GRVNPN_X1: COLLECTOR-RX width = 1.15
33822 0 INFO VNPN_modeled: Oversize vnpn ==  2.2um
33825 0 GRESDTDI20_REV: ESDTDI20 Revision must be == 3.0 !
33827 0 GRESDTDI20_L: (SP OR (SP HOLE)) length == 3.5um.
33839 0 GRESDTDI20_W1: Minimum (SP OR (SP HOLE)) width >= 32.5um
33840 0 GRESDTDI20_W2: Maximum (SP OR (SP HOLE)) width <= 32.50um
33842 0 GRESDTDI20_X1: p+RX length == 2.0um.
33857 0 GRESDTDI20_X2: SP width == 1.0um.
33862 0 GRESDTDI20_X3: SP overlap of p+RX==0.25um.
33869 0 INFO ESDTDI20_modeled: modeled area 2.0
33872 0 GRESDTDI25_REV: ESDTDI25 Revision must be == 2.0 !
33874 0 GRESDTDI25_L: SP OR SP Hole Length == 14.4
33876 0 GRESDTDI25_W1: (SP or (SP hole)) width >= 14.4um
33877 0 GRESDTDI25_W2: Maximum (SP OR (SP Hole)) width == 14.40um
33879 0 GRESDTDI25_X1: p+RX length == 12.8um
33884 0 GRESDTDI25_X2: SP width == 1.0um.
33891 0 GRESDTDI25_X3: SP overlap of p+RX == 0.2um
33898 0 GRESDTDI25_X4: SP to SN spacing == 4.0um
33916 0 GRESDTDI25_X5: SN width == 0.95um.
33924 0 GRESDTDI25_X6: SN enclosure of n+RX (inside) == 0.1um.
33937 0 GRESDTDI25_X7: SN enclosure of n+RX (outside) == 0.25um.
33939 0 GRESDTDI25_X8: Minimum DN enclosure of SN >=1.15um.
33946 0 INFO ESDTDI25_modeled: modeled area 2.0
33949 0 GRESDFDI25_REV: ESDFDI25 Revision must be == 2.0 !
33964 0 GRESDFDI25_L: DP length == 2.4um.
33977 0 GRESDFDI25_W1: Minimum dp width >= 12.4um.
33982 0 GRESDFDI25_W2: Maximum dp width <= 250um.
33985 0 GRESDFDI25_X1: sp enclosure of p+RX == 0um.
33988 0 GRESDFDI25_Y1: sp enclosure of p+RX == 0um.
33995 0 GRESDFDI25_Y2: dp enclosure of p+RX = 1.2um.
34002 0 GRESDFDI25_X2: dp enclosure of p+RX = 0.5um.
34007 0 GRESDFDI25_Y3: dp spacing SN = 2.8um.
34012 0 GRESDFDI25_X3: dp spacing SN = 1.0um.
34021 0 GRESDFDI25_X7: P+RX spacing to PC ==0.5um.
34041 0 GRESDFDI25_X8: PC width == 0.75um.
34046 0 GRESDFDI25_X4: SN width == 1.0um.
34053 0 GRESDFDI25_X6: SN enclosure of RX = 0.2um.
34058 0 GRESDFDI25_X5: Minimum dn enclosure of SN >=5.3um.
34063 0 GRESDFDI25_Y4: Minimum dn enclosure of SN >=5.3um.
34069 0 GRESDFDI25_X9: NW spacing SN == 3.5um.
34074 0 GRESDFDI25_Y5: NW spacing SN == 3.5um.
34079 0 GRESDFDI25_X10: NW enclosure of n+RX == 0.65um.
34086 0 INFO ESDFDI25_modeled: Oversize RXHV == 1.15um.
34089 0 GRESDFDI50_REV: ESDFDI50 Revision must be == 2.0 !
34104 0 GRESDFDI50_L: DP length == 5.4um.
34109 0 GRESDFDI50_W1: Minimum dp width >= 15.4um.
34110 0 GRESDFDI50_W2: Maximum dp width <= 250um.
34113 0 GRESDFDI50_X1: sp enclosure of p+RX == 0um.
34116 0 GRESDFDI50_Y1: sp enclosure of p+RX == 0um.
34123 0 GRESDFDI50_Y2: dp enclosure of p+RX = 2.7um.
34130 0 GRESDFDI50_X2: dp enclosure of p+RX = 2.0um.
34135 0 GRESDFDI50_Y3: dp spacing SN = 6.35um.
34140 0 GRESDFDI50_X3: dp spacing SN = 4.0um.
34149 0 GRESDFDI50_X7: P+RX spacing to PC ==0.5um.
34154 0 GRESDFDI50_X8: PC width == 2.25um.
34159 0 GRESDFDI50_X4: SN width == 1.0um.
34166 0 GRESDFDI50_X6: SN enclosure of RX = 0.2um.
34171 0 GRESDFDI50_X5: Minimum dn enclosure of SN >=5.3um.
34176 0 GRESDFDI50_Y4: Minimum dn enclosure of SN >=5.3um.
34183 0 GRESDFDI50_X9: NW spacing SN == 3.5um.
34187 0 GRESDFDI50_Y5: NW spacing SN == 3.5um.
34192 0 GRESDFDI50_X10: NW enclosure of n+RX == 0.65um.
34199 0 INFO ESDFDI50_modeled: Oversize RXHV == 1.15um.
34202 0 GRESDTDI50_REV: ESDTDI50 Revision must be == 3.0 !
34219 0 GRESDTDI50_W1: Minimum FCUS hole width >= 16.9um
34225 0 GRESDTDI50_W2: Maximum BFCUS HOLE width == 16.90um
34256 0 GRNFET12MH_REV: NFET12MH Revision must be == 1.0 !
34271 0 GRNFET12MH_L: NFET12MH Min Channel Length >= 0.4
34274 0 GRNFET12MH_W2: NFET12MH Min Channel Width >= 2.5
34280 0 GRNFET12MH_A1: RX doesn't match RX_NF1 !
34286 0 GRNFET12MH_A2: PC doesn't match PC_NF1!
34292 0 GRNFET12MH_A3: SN doesn't match SN_NF1!
34298 0 GRNFET12MH_A4: SP doesn't match SP_NF1!
34304 0 GRNFET12MH_A5: DP doesn't match DP_NF1!
34310 0 GRNFET12MH_A6: M1 doesn't match M1_NF1!
34316 0 GRNFET12MH_A7: NG doesn't match NG_NF1!
34323 0 GRNFET12MH_A8: (BP or BPCUS) doesn't match BP_NF1!
34329 0 GRNFET12MH_A9: DN doesn't match DN_NF1!
34335 0 GRNFET12MH_A10: BFCUS doesn't match BF_NF1!
34338 0 GRPFET12MH_REV: PFET12MH Revision must be == 1.0 !
34353 0 GRPFET12MH_L: PFET12MH Min Channel Length >= 0.6
34356 0 GRPFET12MH_W2: PFET12MH Min Channel Width >= 2.5
34361 0 GRPFET12MH_A1: RX doesn't match RX_NF1 !
34366 0 GRPFET12MH_A2: PC doesn't match PC_NF1!
34371 0 GRPFET12MH_A3: SN doesn't match SN_NF1!
34376 0 GRPFET12MH_A4: SP doesn't match SP_NF1!
34381 0 GRPFET12MH_A5: DP doesn't match DP_NF1!
34386 0 GRPFET12MH_A6: M1 doesn't match M1_NF1!
34391 0 GRPFET12MH_A7: NG doesn't match NG_NF1!
34397 0 GRPFET12MH_A8: (BP or BPCUS) doesn't match BP_NF1!
34402 0 GRPFET12MH_A9: DN doesn't match DN_NF1!
34407 0 GRPFET12MH_A10: BFCUS doesn't match BF_NF1!
34410 0 GRNFETI120M_REV: NFETI120M Revision must be == 1.0 !
34425 0 GRNFETI120M_L: NFETI120M Min Channel Length >= 1.0
34428 0 GRNFETI120M_W2: NFETI120M Min Channel Width >= 2.5
34433 0 GRNFETI120M_A1: RX doesn't match RX_NF1 !
34438 0 GRNFETI120M_A2: PC doesn't match PC_NF1!
34443 0 GRNFETI120M_A3: SN doesn't match SN_NF1!
34448 0 GRNFETI120M_A4: SP doesn't match SP_NF1!
34453 0 GRNFETI120M_A5: DP doesn't match DP_NF1!
34458 0 GRNFETI120M_A6: M1 doesn't match M1_NF1!
34463 0 GRNFETI120M_A7: NG doesn't match NG_NF1!
34469 0 GRNFETI120M_A8: (BP or BPCUS) doesn't match BP_NF1!
34474 0 GRNFETI120M_A9: DN doesn't match DN_NF1!
34479 0 GRNFETI120M_A10: BFCUS doesn't match BF_NF1!
34482 0 GRPFET120M_REV: PFET120M Revision must be == 1.0 !
34497 0 GRPFET120M_L: PFET120M Min Channel Length >= 1.0
34500 0 GRPFET120M_W2: PFET120M Min Channel Width >= 2.5
34505 0 GRPFET120M_A1: RX doesn't match RX_NF1 !
34510 0 GRPFET120M_A2: PC doesn't match PC_NF1!
34515 0 GRPFET120M_A3: SN doesn't match SN_NF1!
34520 0 GRPFET120M_A4: SP doesn't match SP_NF1!
34525 0 GRPFET120M_A5: DP doesn't match DP_NF1!
34530 0 GRPFET120M_A6: M1 doesn't match M1_NF1!
34535 0 GRPFET120M_A7: NG doesn't match NG_NF1!
34541 0 GRPFET120M_A8: (BP or BPCUS) doesn't match BP_NF1!
34546 0 GRPFET120M_A9: DN doesn't match DN_NF1!
34551 0 GRPFET120M_A10: BFCUS doesn't match BF_NF1!
34555 0 GRIBM_REV: All RXHV_IBM shapes must touch text on level RXHV_IBM = {NFET12MH_REV_1.0, NFETI120M_REV_1.0, PFET12MH_REV_1.0, PFET120M_REV_1.0 
34563 0 GR228: CABAR outside of (Resistors or Chip Guardring) found!
34568 0 qtHt_err_chipedge: GRQCAP1c: (QT+HT) area >= 2000000 sq.um.
35851 0 GRHV7: (DIODEDNSX not over (DIODE or GRLOGIC) is not connected in parallel to a similar diode in parallel to a similar diode in an LVS device
35871 0 GRHV8: (DIODEPWDN not over (DIODE or GRLOGIC)) is not connected in parallel to a similar diode in an LVS device
35887 0 GRHV9: (DIODENDPW not over (DIODE or GRLOGIC or FLTGATE)) is not connected in parallel to a similar diode in an LVS device
35903 0 GRHV10: (DIODENWX not over (DIODE or GRLOGIC)) is not connected in parallel to a similar diode in an LVS device
35913 0 GRHV11: (DIODENX not over (DIODE or GRLOGIC or FLTGATE)) is not connected in parallel to a similar diode in an LVS device
35932 0 GRHV13: (DIODEPNW not over (DIODE or GRLOGIC orFLTGATE)) is not connected in parallel to a similar diode in an LVS device
35937 0 GRVNCAPHV20: ((M1 intersect VNCAP_M1) touching VNCAPHV) to adjacent PC (diffnet) space >= 1.50 um.
35939 0 GRVNCAPHV20: ((M2 intersect VNCAP_M2) touching VNCAPHV) to adjacent PC (diffnet) space >= 1.50 um.
35941 0 GRVNCAPHV20: ((M3 intersect VNCAP_M3) touching VNCAPHV) to adjacent PC (diffnet) space >= 1.50 um.
35943 0 GRVNCAPHV20: ((M4 intersect VNCAP_M4) touching VNCAPHV) to adjacent PC (diffnet) space >= 1.50 um.
35945 0 GRVNCAPHV20: ((M5 intersect VNCAP_M5) touching VNCAPHV) to adjacent PC (diffnet) space >= 1.50 um.
35947 0 GRVNCAPHV20: ((MT intersect VNCAP_MT) touching VNCAPHV) to adjacent PC (diffnet) space >= 1.50 um.
36031 0 err_vncapm1gt_via: GRVNCAP2: VNCAP_M1 area must be < 100,000 um2 (whole chip)
36032 0 err_vncapm2gt_via: GRVNCAP2: VNCAP_M2 area must be < 100,000 um2 (whole chip)
36033 0 err_vncapm3gt_via: GRVNCAP2: VNCAP_M3 area must be < 100,000 um2 (whole chip)
36034 0 err_vncapm4gt_via: GRVNCAP2: VNCAP_M4 area must be < 100,000 um2 (whole chip)
36035 0 err_vncapm5gt_via: GRVNCAP2: VNCAP_M5 area must be < 100,000 um2 (whole chip)
36036 0 err_vncapmtgt_via: GRVNCAP2: VNCAP_MT area must be < 100,000 um2 (whole chip)
36055 0 err_vncapm1gt_via: GRVNCAP2b: VNCAP_M1 area must be < 1,000,000 um2 (whole chip)
36056 0 err_vncapm2gt_via: GRVNCAP2b: VNCAP_M2 area must be < 1,000,000 um2 (whole chip)
36057 0 err_vncapm3gt_via: GRVNCAP2b: VNCAP_M3 area must be < 1,000,000 um2 (whole chip)
36058 0 err_vncapm4gt_via: GRVNCAP2b: VNCAP_M4 area must be < 1,000,000 um2 (whole chip)
36059 0 err_vncapm5gt_via: GRVNCAP2b: VNCAP_M5 area must be < 1,000,000 um2 (whole chip)
36060 0 err_vncapmtgt_via: GRVNCAP2b: VNCAP_MT area must be < 1,000,000 um2 (whole chip)
36062 0 # INFO: H18REV5 ASSURA DRC DECK (REV DATE 20/02/2013) #
